import type { BrainDatasetContract, BrainEventContract, BrainSensitivity } from "../core";

const internal: readonly BrainSensitivity[] = ["internal", "confidential"];
const restricted: readonly BrainSensitivity[] = ["internal", "confidential", "restricted"];

export const BRAIN_CONSUMABLE_EVENT_TYPES = {
  fleet_dispatch: [
    "job.created",
    "job.assigned",
    "job.started",
    "job.delayed",
    "job.completed",
    "job.cancelled",
    "vehicle.availability.changed",
    "vehicle.restriction.changed",
    "driver.availability.changed",
    "maintenance.recorded",
    "incident.recorded",
  ],
  tracking: [
    "telemetry.ingested",
    "telemetry.quality.recorded",
    "tracking.session.changed",
    "route.deviation.detected",
    "stop.detected",
    "delay.threshold.exceeded",
    "route.performance.recorded",
  ],
  warehouse: [
    "warehouse.stock_risk.detected",
    "warehouse.inventory_threshold.breached",
    "warehouse.fulfilment.delayed",
    "warehouse.receiving.exception",
    "warehouse.picking.exception",
    "warehouse.loading.exception",
  ],
  crm: [
    "crm.case.created",
    "crm.case.escalated",
    "crm.sla.warning",
    "crm.sla.breached",
    "crm.account_health.changed",
    "crm.onboarding.delayed",
  ],
  hr: [
    "hr.shift_coverage.risk",
    "hr.training.required",
    "hr.certification.expiring",
    "hr.attendance.exception",
    "hr.onboarding.delayed",
  ],
  compliance: [
    "compliance.incident.classified",
    "compliance.risk.changed",
    "compliance.capa.overdue",
    "compliance.permit.expiring",
    "compliance.inspection.recorded",
    "compliance.audit_finding.recorded",
    "compliance.quality.recorded",
  ],
  procurement: [
    "procurement.supplier_compliance.risk",
    "procurement.purchase_order.delayed",
    "procurement.receipt.exception",
    "procurement.invoice.metadata_exception",
    "procurement.supplier_performance.updated",
  ],
  bi: [
    "bi.kpi.threshold_breached",
    "bi.kpi.freshness_warning",
    "bi.data_quality.warning",
    "bi.scorecard.status_changed",
  ],
  integrations: [
    "integration.sync.failed",
    "integration.connector_health.changed",
    "integration.retry.exhausted",
    "integration.dead_letter.created",
    "integration.mapping.validation_failed",
  ],
} as const;

const consumedContracts: BrainEventContract[] = Object.entries(
  BRAIN_CONSUMABLE_EVENT_TYPES,
).flatMap(([domain, types]) =>
  types.map((eventType) => ({
    code: `brain.consume.${eventType}.v1`,
    direction: "consume" as const,
    eventType,
    eventVersion: 1,
    sourceModules:
      domain === "fleet_dispatch"
        ? ["fleet", "dispatch"]
        : domain === "integrations"
          ? ["integration"]
          : [domain === "bi" ? "bi" : domain],
    allowedSensitivities: domain === "hr" ? restricted : internal,
  })),
);

export const BRAIN_EVENT_CONTRACTS: readonly BrainEventContract[] = [
  ...consumedContracts,
  ...[
    "brain.analysis.started",
    "brain.analysis.completed",
    "brain.analysis.failed",
    "brain.insight.created",
    "brain.insight.updated",
    "brain.recommendation.proposed",
    "brain.evidence.enriched",
    "brain.feedback.recorded",
    "brain.rule.calibration.proposed",
    "brain.model.evaluation.completed",
  ].map((eventType) => ({
    code: `${eventType}.v1`,
    direction: "publish" as const,
    eventType,
    eventVersion: 1,
    sourceModules: ["brain"],
    allowedSensitivities: restricted,
    experimental: eventType === "brain.model.evaluation.completed",
  })),
];

const commonRestricted = [
  "password_hash",
  "credential",
  "api_key",
  "access_token",
  "refresh_token",
  "bank_account",
  "medical_detail",
  "payroll_amount",
  "identity_document_number",
  "personal_address",
  "personal_contact",
];

export function defaultBrainDatasetContracts(
  companyId: string,
  effectiveAt: string,
): BrainDatasetContract[] {
  const template = (
    input: Omit<BrainDatasetContract, "companyId" | "effectiveAt">,
  ): BrainDatasetContract => ({ ...input, companyId, effectiveAt });
  return [
    template({
      datasetCode: "brain.fleet.operational-signals.v1",
      datasetVersion: 1,
      businessDomain: "fleet",
      owningModule: "fleet",
      purpose: "Deterministic operational-risk analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.fleet_dispatch,
      allowedFields: [
        "status",
        "severity",
        "occurred_at",
        "vehicle_id",
        "driver_id",
        "job_id",
        "reason_code",
      ],
      restrictedFields: commonRestricted,
      sensitivity: "confidential",
      minimumRole: "brain_analyst",
      useCases: ["operational insights", "maintenance risk"],
      retentionDays: 90,
      freshnessRequirementMinutes: 60,
      enabled: true,
    }),
    template({
      datasetCode: "brain.tracking.route-quality.v1",
      datasetVersion: 1,
      businessDomain: "tracking",
      owningModule: "tracking",
      purpose: "Telemetry and route-quality analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.tracking,
      allowedFields: [
        "tracking_session_id",
        "job_id",
        "vehicle_id",
        "quality_score",
        "telemetry_quality_score",
        "accepted_point_count",
        "rejected_point_count",
        "delay_minutes",
        "route_key",
      ],
      restrictedFields: commonRestricted,
      sensitivity: "confidential",
      minimumRole: "brain_analyst",
      useCases: ["route quality", "telemetry evidence"],
      retentionDays: 90,
      freshnessRequirementMinutes: 15,
      enabled: true,
    }),
    template({
      datasetCode: "brain.warehouse.exception-signals.v1",
      datasetVersion: 1,
      businessDomain: "warehouse",
      owningModule: "warehouse",
      purpose: "Warehouse exception analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.warehouse,
      allowedFields: [
        "status",
        "severity",
        "warehouse_id",
        "product_id",
        "exception_code",
        "occurred_at",
      ],
      restrictedFields: commonRestricted,
      sensitivity: "confidential",
      minimumRole: "brain_analyst",
      useCases: ["fulfilment risk"],
      retentionDays: 90,
      freshnessRequirementMinutes: 60,
      enabled: true,
    }),
    template({
      datasetCode: "brain.crm.account-health.v1",
      datasetVersion: 1,
      businessDomain: "crm",
      owningModule: "crm",
      purpose: "Customer-success risk analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.crm,
      allowedFields: [
        "account_id",
        "case_id",
        "sla_status",
        "health_status",
        "occurred_at",
        "reason_code",
      ],
      restrictedFields: [...commonRestricted, "email", "phone"],
      sensitivity: "confidential",
      minimumRole: "brain_analyst",
      useCases: ["SLA risk", "account health"],
      retentionDays: 90,
      freshnessRequirementMinutes: 60,
      enabled: true,
    }),
    template({
      datasetCode: "brain.hr.workforce-minimised.v1",
      datasetVersion: 1,
      businessDomain: "hr",
      owningModule: "hr",
      purpose: "Approved minimised workforce-risk analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.hr,
      allowedFields: [
        "department_id",
        "coverage_status",
        "training_status",
        "certification_expiry",
        "attendance_status",
        "occurred_at",
      ],
      restrictedFields: [...commonRestricted, "medical", "payroll", "bank", "disciplinary"],
      sensitivity: "restricted",
      minimumRole: "brain_administrator",
      useCases: ["coverage risk", "training and certification"],
      retentionDays: 30,
      freshnessRequirementMinutes: 1440,
      enabled: false,
    }),
    template({
      datasetCode: "brain.compliance.risk-signals.v1",
      datasetVersion: 1,
      businessDomain: "compliance",
      owningModule: "compliance",
      purpose: "Compliance and quality evidence analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.compliance,
      allowedFields: ["record_id", "risk_status", "due_at", "severity", "status", "occurred_at"],
      restrictedFields: commonRestricted,
      sensitivity: "confidential",
      minimumRole: "brain_analyst",
      useCases: ["risk evidence", "expiry warnings"],
      retentionDays: 365,
      freshnessRequirementMinutes: 1440,
      enabled: true,
    }),
    template({
      datasetCode: "brain.procurement.supplier-risk.v1",
      datasetVersion: 1,
      businessDomain: "procurement",
      owningModule: "procurement",
      purpose: "Supplier and purchasing exception analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.procurement,
      allowedFields: [
        "supplier_id",
        "purchase_order_id",
        "status",
        "exception_code",
        "occurred_at",
      ],
      restrictedFields: [...commonRestricted, "bank", "invoice_amount"],
      sensitivity: "confidential",
      minimumRole: "brain_analyst",
      useCases: ["supplier risk"],
      retentionDays: 180,
      freshnessRequirementMinutes: 1440,
      enabled: true,
    }),
    template({
      datasetCode: "brain.bi.kpi-signals.v1",
      datasetVersion: 1,
      businessDomain: "bi",
      owningModule: "bi",
      purpose: "KPI threshold, freshness and quality analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.bi,
      allowedFields: ["kpi_id", "status", "freshness", "quality_status", "occurred_at"],
      restrictedFields: commonRestricted,
      sensitivity: "internal",
      minimumRole: "brain_analyst",
      useCases: ["KPI evidence", "analysis freshness"],
      retentionDays: 90,
      freshnessRequirementMinutes: 1440,
      enabled: true,
    }),
    template({
      datasetCode: "brain.integrations.health-signals.v1",
      datasetVersion: 1,
      businessDomain: "integrations",
      owningModule: "integration",
      purpose: "Verified connector-health analysis",
      allowedEventTypes: BRAIN_CONSUMABLE_EVENT_TYPES.integrations,
      allowedFields: ["integration_id", "status", "failure_code", "occurred_at", "attempt_count"],
      restrictedFields: commonRestricted,
      sensitivity: "internal",
      minimumRole: "brain_analyst",
      useCases: ["integration health"],
      retentionDays: 90,
      freshnessRequirementMinutes: 60,
      enabled: true,
    }),
  ];
}
