/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  SimState,
  SimVehicle,
  SimDriver,
  SimCustomer,
  SimDepot,
  SimRoute,
  SimJob,
  SimIncident,
  SimWorkshopBooking,
  SimCompany,
} from '../zapp-simulator/types';

import { ZappBrainResult } from '../zapp-brain/types';

/**
 * Scale categorization for synthetic fleet generation.
 */
export type FleetScale = 'small' | 'medium' | 'enterprise';

/**
 * Unified representation of a generated synthetic company structure.
 */
export interface SyntheticFleet {
  scale: FleetScale;
  company: SimCompany;
  vehicles: SimVehicle[];
  drivers: SimDriver[];
  depots: SimDepot[];
  customers: SimCustomer[];
  routes: SimRoute[];
  jobs: SimJob[];
  workshops: SimWorkshopBooking[];
  complianceDocs: SyntheticComplianceDoc[];
  maintenanceHistory: SyntheticMaintenanceRecord[];
}

/**
 * Detailed compliance document details.
 */
export interface SyntheticComplianceDoc {
  id: string;
  entityType: 'driver' | 'vehicle' | 'company';
  entityId: string;
  docType: 'license' | 'PrDP' | 'COF' | 'permit' | 'insurance';
  docNumber: string;
  issueDate: string;
  expiryDate: string;
  status: 'valid' | 'expired' | 'expiring_soon';
}

/**
 * Detailed vehicle maintenance records.
 */
export interface SyntheticMaintenanceRecord {
  id: string;
  vehicleId: string;
  mileage: number;
  date: string;
  cost: number;
  type: 'preventative' | 'reactive' | 'scheduled';
  description: string;
  partsReplaced: string[];
}

/**
 * Scenario configurations applied during a run.
 */
export interface OperationalScenario {
  id: string;
  name: string;
  categories: string[]; // weather, traffic, mechanical, operational, telematics, compliance, emergency
  description: string;
  difficultyRating: number; // 0 - 100
  enabledIncidents: string[];
}

/**
 * Evaluation scorecard of operational outcomes.
 */
export interface OperationalOutcome {
  simulationId: string;
  wasSuccess: boolean;
  onTimeRate: number;
  incidentCount: number;
  totalDelayMinutes: number;
  totalCost: number;
  safetyScore: number;
  customerSatisfaction: number;
}

/**
 * Cognitive lessons learned generated by the Brain post-simulation.
 */
export interface LessonLearned {
  id: string;
  simulationId: string;
  whatHappened: string;
  whyDidItHappen: string;
  predictingIndicators: string[];
  couldBeDetectedEarlier: boolean;
  earlierDetectionStrategy: string;
  triggeredRules: string[];
  missedRules: string[];
  effectiveRecommendations: string[];
  failedRecommendations: string[];
  nextTimeBehaviorAdjustment: string;
  financialImpact: number;
  safetyImpact: 'low' | 'medium' | 'high' | 'critical';
  customerImpact: 'low' | 'medium' | 'high' | 'critical';
}

/**
 * Deep, multi-dimensional scoring of a simulation run.
 */
export interface ExperienceScore {
  noveltyScore: number; // 0 - 100
  operationalDifficulty: number; // 0 - 100
  learningValue: number; // 0 - 100
  replayValue: number; // 0 - 100
  riskScore: number; // 0 - 100
  knowledgeDensity: number; // 0 - 100
  financialImpact: number; // Cost in currency
  safetyImpact: number; // 0 - 100 rating
  confidence: number; // 0 - 100
  trust: number; // 0 - 100
  historicalImportance: 'routine' | 'significant' | 'critical' | 'milestone';
}

/**
 * Immutable block of a single simulation session.
 */
export interface ExperienceRecord {
  id: string;
  seed: number;
  timestamp: string;
  scenario: OperationalScenario;
  initialConditions: {
    fleetScale: FleetScale;
    vehicleCount: number;
    driverCount: number;
    depotCount: number;
    customerCount: number;
    weather: string;
    traffic: string;
  };
  telemetryMetrics: {
    totalPackets: number;
    signalReliability: number; // 0 - 100
    avgSpeed: number;
    fuelConsumed: number;
  };
  brainReasoning: string[];
  rulesTriggered: string[];
  recommendations: string[];
  dispatcherActions: string[];
  finalOutcome: OperationalOutcome;
  score: ExperienceScore;
  lessonsLearned: LessonLearned;
}

/**
 * Consolidated operational pattern discovered by the system.
 */
export interface OperationalPattern {
  id: string;
  category: string; // e.g. Fuel, Maintenance, Customer
  patternDescription: string;
  frequency: number;
  confidence: number; // 0 - 100
  evidenceCount: number;
  supportingEvidence: string[];
  estimatedFinancialRisk: number;
}

/**
 * Knowledge library category container.
 */
export interface KnowledgeTopic {
  category: string;
  commonPatterns: string[];
  historicalExamples: { simId: string; summary: string }[];
  frequentCauses: string[];
  bestResponses: string[];
  successRates: number; // percentage
  lessonsLearned: string[];
  relatedExperiences: string[]; // list of experience ids
}

/**
 * Graph structures representing operational nodes and relationships.
 */
export interface KnowledgeGraphNode {
  id: string;
  type: 'vehicle' | 'driver' | 'route' | 'customer' | 'depot' | 'workshop' | 'telemetry' | 'incident' | 'recommendation' | 'outcome';
  label: string;
  properties: Record<string, any>;
}

export interface KnowledgeGraphEdge {
  id: string;
  source: string;
  target: string;
  relationship: string;
  weight?: number;
}

export interface KnowledgeGraph {
  nodes: KnowledgeGraphNode[];
  edges: KnowledgeGraphEdge[];
}

/**
 * Formats representing overall synthetic knowledge databases.
 */
export interface SyntheticKnowledgeStore {
  experienceHistory: ExperienceRecord[];
  knowledgeGraph: KnowledgeGraph;
  knowledgeLibrary: Record<string, KnowledgeTopic>;
  discoveredPatterns: OperationalPattern[];
}

/**
 * Role-specific, action-oriented briefing models.
 */
export interface ExecutiveBriefReport {
  id: string;
  title: string;
  period: 'daily' | 'weekly' | 'monthly';
  dateGenerated: string;
  summary: string;
  keyStats: { label: string; value: string | number }[];
  topMechanicalRisks: string[];
  highestRiskDrivers: string[];
  worstRoutes: string[];
  customerServiceSummary: string;
  maintenanceForecast: string;
  safetyOverview: string;
  complianceOverview: string;
  explainabilityProof: {
    conclusions: string[];
    evidenceUsed: string[];
    rulesTriggered: string[];
    alternativeExplanations: string[];
  };
}
