BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT extensions.plan(25);
SELECT extensions.is((SELECT count(*)::int FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'predictive_%'),18,'all Phase 39 tables exist');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname LIKE 'predictive_%' AND c.relkind='r' AND NOT c.relrowsecurity),'all predictive tables have RLS');
SELECT extensions.is((SELECT count(*)::int FROM pg_policies WHERE schemaname='public' AND tablename LIKE 'predictive_%'),33,'reviewed predictive policy set exists');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM information_schema.table_privileges WHERE table_schema='public' AND table_name LIKE 'predictive_%' AND grantee IN('PUBLIC','anon')),'PUBLIC and anon have no predictive table grants');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM information_schema.table_privileges WHERE table_schema='public' AND table_name LIKE 'predictive_%' AND grantee='authenticated' AND privilege_type IN('UPDATE','DELETE')),'authenticated cannot mutate predictive evidence');
SELECT extensions.is((SELECT count(*)::int FROM pg_trigger WHERE NOT tgisinternal AND tgname LIKE 'predictive_%_immutable'),18,'all predictive evidence has immutable triggers');
SELECT extensions.ok(has_function_privilege('authenticated','public.predictive39_dashboard()','EXECUTE'),'dashboard RPC authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.predictive39_assessments(integer,integer)','EXECUTE'),'bounded assessment RPC authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.predictive39_review(uuid,text,text,text)','EXECUTE'),'controlled review RPC authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.predictive39_dispatch(uuid)','EXECUTE'),'dispatch projection authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.predictive39_driver()','EXECUTE'),'driver projection authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.predictive39_customer_care(uuid)','EXECUTE'),'Customer Care projection authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.predictive39_zip(text)','EXECUTE'),'ZIP boundary authenticated');
SELECT extensions.ok(NOT has_function_privilege('anon','public.predictive39_dashboard()','EXECUTE'),'anonymous dashboard denied');
SELECT extensions.ok(NOT has_function_privilege('anon','public.predictive39_review(uuid,text,text,text)','EXECUTE'),'anonymous review denied');
SELECT extensions.ok((SELECT prosecdef FROM pg_proc WHERE proname='predictive39_dashboard'),'dashboard is server-authorized');
SELECT extensions.ok((SELECT prosecdef FROM pg_proc WHERE proname='predictive39_review' AND pronargs=4),'review is server-authorized');
SELECT extensions.ok((SELECT count(*) FROM pg_policies WHERE tablename='predictive_vehicle_assessments' AND cmd='INSERT' AND with_check LIKE '%brain_is_service%')=1,'Brain service owns derived assessment writes');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.predictive_vehicle_assessments','INSERT'),'users cannot directly create assessments');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.predictive_feedback','INSERT'),'feedback requires controlled RPC');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.predictive_outcomes','INSERT'),'outcomes require controlled authority');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.predictive_audit_logs','INSERT'),'audit insertion is controlled');
SELECT extensions.ok((SELECT count(*) FROM brain_feature_registry WHERE feature_code IN('vehicle_maintenance_risk','vehicle_breakdown_recurrence','fuel_anomaly_score','battery_risk','cooling_risk','tyre_risk','device_reliability_risk','route_stress_score','driver_risk_trend','predicted_downtime_range','service_demand_score'))>0,'Phase 39 Brain features registered');
SELECT extensions.ok((SELECT rolbypassrls FROM pg_roles WHERE rolname='service_role'),'service role remains intentional server-only bypass');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM pg_policies WHERE tablename LIKE 'predictive_%' AND roles @> ARRAY['anon']::name[]),'no predictive policy applies to anon');
SELECT * FROM extensions.finish();
ROLLBACK;
