BEGIN;CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;SELECT extensions.plan(13);
CREATE TEMP TABLE phase34_fixture AS SELECT (SELECT company_id FROM public.user_roles WHERE role='admin' LIMIT 1) company_a,(SELECT user_id FROM public.user_roles WHERE role='admin' LIMIT 1) admin_user,(SELECT company_id FROM public.user_roles WHERE role='viewer' LIMIT 1) viewer_company,(SELECT user_id FROM public.user_roles WHERE role='viewer' LIMIT 1) viewer_user,(SELECT user_id FROM public.customer_portal_memberships WHERE status='active' LIMIT 1) customer_user;GRANT SELECT ON phase34_fixture TO authenticated;
SELECT extensions.ok(company_a IS NOT NULL AND admin_user IS NOT NULL AND viewer_user IS NOT NULL AND customer_user IS NOT NULL,'staging personas exist') FROM phase34_fixture;
INSERT INTO public.tracking_audit_logs(company_id,event_type,entity_type,entity_id,actor_id) SELECT company_a,'tracking_setting_changed','company',company_a,admin_user FROM phase34_fixture;
INSERT INTO public.tracking_operational_settings(company_id,updated_by) SELECT company_a,admin_user FROM phase34_fixture ON CONFLICT(company_id) DO NOTHING;
SELECT extensions.throws_ok($$UPDATE public.tracking_audit_logs SET event_type='replay_opened'$$,'P0001','Tracking evidence is append-only','audit is append-only');
SELECT extensions.ok(has_table_privilege('authenticated','public.tracking_vehicle_states','SELECT'),'authenticated RLS access exists');
SELECT extensions.ok(NOT has_table_privilege('anon','public.tracking_vehicle_states','SELECT'),'anonymous denied');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.tracking_vehicle_states','UPDATE'),'state evidence update denied');
SELECT set_config('request.jwt.claim.sub',(SELECT viewer_user::text FROM phase34_fixture),true);SELECT set_config('request.jwt.claim.role','authenticated',true);SET LOCAL ROLE authenticated;
SELECT extensions.throws_ok(format('INSERT INTO public.tracking_alerts(company_id,alert_type,priority,source_evidence) VALUES(%L,%L,%L,%L)',(SELECT viewer_company FROM phase34_fixture),'offline','high','[]'),'42501',NULL,'viewer is read-only');RESET ROLE;
SELECT set_config('request.jwt.claim.sub',(SELECT customer_user::text FROM phase34_fixture),true);SET LOCAL ROLE authenticated;
SELECT extensions.is((SELECT count(*)::bigint FROM public.tracking_vehicle_states),0::bigint,'customer denied internal states');
SELECT extensions.is((SELECT count(*)::bigint FROM public.tracking_alerts),0::bigint,'customer denied internal alerts');
SELECT extensions.ok((SELECT count(*) FROM public.tracking34_customer_locations())>=0,'customer location function is safely scoped');RESET ROLE;
SELECT extensions.ok(position('make_interval' in pg_get_functiondef('public.tracking34_customer_locations()'::regprocedure))>0,'location delay enforced server-side');
SELECT extensions.ok((SELECT count(*) FROM pg_policies WHERE schemaname='public' AND tablename LIKE 'tracking_%')>=17,'RLS source coverage');
SELECT extensions.ok((SELECT offline_regions_state='not_configured' FROM public.tracking_map_provider_configs WHERE false) IS NULL,'missing provider cannot claim configured offline tiles');
SELECT extensions.ok((SELECT eta FROM public.tracking_eta_assessments WHERE false) IS NULL,'missing ETA evidence stays unavailable');
SELECT * FROM extensions.finish();ROLLBACK;
