BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT extensions.plan(10);
CREATE TEMP TABLE phase32_fixture AS SELECT (SELECT company_id FROM public.user_roles WHERE role='admin' LIMIT 1) company_a,(SELECT user_id FROM public.user_roles WHERE role='admin' LIMIT 1) admin_user,(SELECT company_id FROM public.user_roles WHERE role='viewer' LIMIT 1) viewer_company,(SELECT user_id FROM public.user_roles WHERE role='viewer' LIMIT 1) viewer_user,(SELECT user_id FROM public.customer_portal_memberships WHERE status='active' LIMIT 1) customer_user;
GRANT SELECT ON phase32_fixture TO authenticated;
SELECT extensions.ok(company_a IS NOT NULL AND admin_user IS NOT NULL AND viewer_user IS NOT NULL AND customer_user IS NOT NULL,'staging security personas exist') FROM phase32_fixture;
INSERT INTO public.security_identities(id,company_id,auth_user_id,identity_type,display_name) SELECT '32000000-0000-0000-0000-000000000001',company_a,admin_user,'user','Phase32 fixture' FROM phase32_fixture;
INSERT INTO public.security_events(company_id,event_type,identity_id,actor_id,severity) SELECT company_a,'login','32000000-0000-0000-0000-000000000001',admin_user,'low' FROM phase32_fixture;
INSERT INTO public.security_legal_holds(id,company_id,name,scope,reason,starts_at,created_by,approved_by,approved_at) SELECT '32000000-0000-0000-0000-000000000002',company_a,'Fixture hold','{"record_type":"audit"}','Test evidence',now(),admin_user,admin_user,now() FROM phase32_fixture;
SELECT extensions.throws_ok($$UPDATE public.security_events SET severity='critical'$$,'P0001','Security evidence is append-only','security events are append-only');
SELECT extensions.throws_ok($$DELETE FROM public.security_legal_holds WHERE id='32000000-0000-0000-0000-000000000002'$$,'P0001','Active legal holds are immutable','active holds cannot be deleted');
SELECT extensions.ok(has_table_privilege('authenticated','public.security_sessions','SELECT'),'authenticated access is RLS governed');
SELECT extensions.ok(NOT has_table_privilege('anon','public.security_sessions','SELECT'),'anonymous session access denied');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.security_events','UPDATE'),'security event update denied');
SELECT set_config('request.jwt.claim.sub',(SELECT viewer_user::text FROM phase32_fixture),true); SELECT set_config('request.jwt.claim.role','authenticated',true); SET LOCAL ROLE authenticated;
SELECT extensions.throws_ok(format('INSERT INTO public.security_identities(company_id,identity_type,display_name) VALUES(%L,%L,%L)',(SELECT viewer_company FROM phase32_fixture),'user','denied'),'42501',NULL,'viewer is read-only');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub',(SELECT customer_user::text FROM phase32_fixture),true); SET LOCAL ROLE authenticated;
SELECT extensions.is((SELECT count(*)::bigint FROM public.security_identities),0::bigint,'customer cannot read internal identities');
SELECT extensions.is((SELECT count(*)::bigint FROM public.security_events),0::bigint,'customer cannot read security events');
RESET ROLE;
SELECT extensions.ok((SELECT status='pending' FROM public.security_auth_factors WHERE false) IS NULL,'missing MFA evidence cannot report success');
SELECT * FROM extensions.finish();
ROLLBACK;
