BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT extensions.plan(25);
SELECT extensions.is((SELECT count(*)::int FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'executive_%'),12,'all Phase 40 tables exist');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname LIKE 'executive_%' AND c.relkind='r' AND NOT c.relrowsecurity),'all executive tables have RLS');
SELECT extensions.is((SELECT count(*)::int FROM pg_policies WHERE schemaname='public' AND tablename LIKE 'executive_%'),24,'reviewed executive policy set exists');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM information_schema.table_privileges WHERE table_schema='public' AND table_name LIKE 'executive_%' AND grantee IN('PUBLIC','anon')),'PUBLIC and anon have no executive grants');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM information_schema.table_privileges WHERE table_schema='public' AND table_name LIKE 'executive_%' AND grantee='authenticated' AND privilege_type IN('INSERT','UPDATE','DELETE')),'authenticated cannot directly mutate evidence');
SELECT extensions.is((SELECT count(*)::int FROM pg_trigger WHERE NOT tgisinternal AND tgname LIKE 'executive_%_immutable'),12,'executive evidence immutable');
SELECT extensions.ok(has_function_privilege('authenticated','public.executive40_dashboard()','EXECUTE'),'dashboard authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.executive40_records(text,integer)','EXECUTE'),'bounded records authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.executive40_record_decision(text,text,timestamp with time zone,jsonb)','EXECUTE'),'controlled decision authenticated');
SELECT extensions.ok(has_function_privilege('authenticated','public.executive40_zip(text)','EXECUTE'),'ZIP authenticated');
SELECT extensions.ok(NOT has_function_privilege('anon','public.executive40_dashboard()','EXECUTE'),'anonymous dashboard denied');
SELECT extensions.ok(NOT has_function_privilege('anon','public.executive40_record_decision(text,text,timestamp with time zone,jsonb)','EXECUTE'),'anonymous decision denied');
SELECT extensions.ok((SELECT prosecdef FROM pg_proc WHERE proname='executive40_dashboard'),'dashboard server authorised');
SELECT extensions.ok((SELECT prosecdef FROM pg_proc WHERE proname='executive40_record_decision'),'decision server authorised');
SELECT extensions.ok((SELECT count(*) FROM pg_policies WHERE tablename='executive_operating_state' AND cmd='INSERT' AND with_check LIKE '%brain_is_service%')=1,'Brain owns derived writes');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.executive_operating_state','INSERT'),'users cannot create operating state');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.executive_decisions','INSERT'),'decisions require controlled RPC');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.executive_audit_logs','INSERT'),'audit requires controlled RPC');
SELECT extensions.ok((SELECT rolbypassrls FROM pg_roles WHERE rolname='service_role'),'service role intentional server bypass');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM pg_policies WHERE tablename LIKE 'executive_%' AND roles @> ARRAY['anon']::name[]),'no anon policy');
SELECT extensions.ok(position('customer_portal_memberships' in pg_get_functiondef('public.executive40_read(uuid)'::regprocedure))>0,'customer membership explicitly denied');
SELECT extensions.ok(position('driver' in pg_get_functiondef('public.executive40_read(uuid)'::regprocedure))>0,'driver explicitly denied');
SELECT extensions.ok(position('viewer' in pg_get_functiondef('public.executive40_read(uuid)'::regprocedure))>0,'viewer read-only supported');
SELECT extensions.ok(position('domain_workflow_mutated' in pg_get_functiondef('public.executive40_record_decision(text,text,timestamp with time zone,jsonb)'::regprocedure))>0,'decision cannot mutate domain workflow');
SELECT extensions.ok(position('read_only' in pg_get_functiondef('public.executive40_zip(text)'::regprocedure))>0,'ZIP explicitly read-only');
SELECT * FROM extensions.finish();
ROLLBACK;
