BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT extensions.plan(10);
CREATE TEMP TABLE phase33_fixture AS SELECT (SELECT company_id FROM public.user_roles WHERE role='admin' LIMIT 1) company_a,(SELECT user_id FROM public.user_roles WHERE role='admin' LIMIT 1) admin_user,(SELECT company_id FROM public.user_roles WHERE role='viewer' LIMIT 1) viewer_company,(SELECT user_id FROM public.user_roles WHERE role='viewer' LIMIT 1) viewer_user,(SELECT user_id FROM public.customer_portal_memberships WHERE status='active' LIMIT 1) customer_user;
GRANT SELECT ON phase33_fixture TO authenticated;
SELECT extensions.ok(company_a IS NOT NULL AND admin_user IS NOT NULL AND viewer_user IS NOT NULL AND customer_user IS NOT NULL,'staging intelligence personas exist') FROM phase33_fixture;
INSERT INTO public.operations_intelligence_simulations(id,company_id,scenario_type,input_metadata,confidence,requested_by) SELECT '33000000-0000-0000-0000-000000000001',company_a,'add_vehicles','{"amount":10}','unavailable',admin_user FROM phase33_fixture;
INSERT INTO public.operations_intelligence_observations(id,company_id,observation_type,scope_type,metric_code,observed_at,confidence,explanation) SELECT '33000000-0000-0000-0000-000000000002',company_a,'trend','company','revenue',now(),'unavailable','No source evidence' FROM phase33_fixture;
SELECT extensions.throws_ok($$UPDATE public.operations_intelligence_observations SET explanation='changed'$$,'P0001','Operations intelligence evidence is append-only','observations append-only');
SELECT extensions.throws_ok($$DELETE FROM public.operations_intelligence_simulations$$,'P0001','Operations intelligence evidence is append-only','simulations append-only');
SELECT extensions.ok(has_table_privilege('authenticated','public.operations_intelligence_forecasts','SELECT'),'authenticated access is RLS governed');
SELECT extensions.ok(NOT has_table_privilege('anon','public.operations_intelligence_forecasts','SELECT'),'anonymous access denied');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.operations_intelligence_forecasts','UPDATE'),'forecast updates denied');
SELECT set_config('request.jwt.claim.sub',(SELECT viewer_user::text FROM phase33_fixture),true);SELECT set_config('request.jwt.claim.role','authenticated',true);SET LOCAL ROLE authenticated;
SELECT extensions.throws_ok(format('INSERT INTO public.operations_intelligence_simulations(company_id,scenario_type,input_metadata,confidence) VALUES(%L,%L,%L,%L)',(SELECT viewer_company FROM phase33_fixture),'add_vehicles','{}','unavailable'),'42501',NULL,'viewer is read-only');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub',(SELECT customer_user::text FROM phase33_fixture),true);SET LOCAL ROLE authenticated;
SELECT extensions.is((SELECT count(*)::bigint FROM public.operations_intelligence_observations),0::bigint,'customer cannot read internal observations');
SELECT extensions.is((SELECT count(*)::bigint FROM public.operations_intelligence_simulations),0::bigint,'customer cannot read simulations');
RESET ROLE;
SELECT extensions.ok((SELECT predicted_value FROM public.operations_intelligence_forecasts WHERE false) IS NULL,'missing forecast evidence cannot imply a prediction');
SELECT * FROM extensions.finish();
ROLLBACK;
