import { SIMULATION_COMPANY_ID } from "./company-fixture";
import { vehicles } from "./fleet";

export const fleetIntelligenceSimulation = vehicles.map((vehicle, index) => ({
  companyId: SIMULATION_COMPANY_ID,
  marker: "simulation" as const,
  vehicleId: vehicle.id,
  day: index % 30,
  fuelLitres: vehicle.fuelType === "electric" ? 0 : 80 + (index % 12) * 4,
  fuelPurchasedLitres: vehicle.fuelType === "electric" ? 0 : 82 + (index % 10) * 4,
  engineHours: 900 + index * 37,
  batteryVoltage: 12.7 - (index % 8) * 0.11,
  engineTemperatureC: 88 + (index % 7) * 3,
  diagnosticTroubleCodes: index % 11 === 0 ? ["SIM-P001"] : [],
  engineWearPercent: Math.min(100, 20 + index * 1.3),
  tyreRemainingPercent: Math.max(5, 92 - index * 1.4),
  brakeRemainingPercent: Math.max(8, 88 - index * 1.2),
  maintenanceHistoryCount: index % 6,
  maintenanceRecurrence: index % 9 === 0,
  workshopRevisit: index % 13 === 0,
  downtimeHours: index % 12,
  idleMinutes: 20 + (index % 8) * 8,
  harshBrakingEvents: index % 9,
  harshAccelerationEvents: index % 7,
  harshCorneringEvents: index % 6,
  speedingEvents: index % 5,
  routeDeviationKm: index % 5 === 0 ? 12 : 0,
  trafficDelayMinutes: index % 3 === 0 ? 35 : 5,
  maintenanceCost: 900 + index * 55,
  fuelCost: vehicle.fuelType === "electric" ? 0 : 1800 + index * 35,
  telemetryQuality: index % 10 === 0 ? "stale" : "fresh",
  weatherEffect: index % 4 === 0 ? "heavy_rain" : "clear",
  trafficCondition: index % 3 === 0 ? "congested" : "normal",
  productionEligible: false,
  simulatedAt: "2026-08-01T00:00:00Z",
}));
