/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CustomerPortalRouteImport } from './routes/customer-portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerPortalIndexRouteImport } from './routes/customer-portal/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as CustomerPortalShipmentsRouteImport } from './routes/customer-portal/shipments'
import { Route as CustomerPortalSettingsRouteImport } from './routes/customer-portal/settings'
import { Route as CustomerPortalSecurityRouteImport } from './routes/customer-portal/security'
import { Route as CustomerPortalRequestsRouteImport } from './routes/customer-portal/requests'
import { Route as CustomerPortalQuotesRouteImport } from './routes/customer-portal/quotes'
import { Route as CustomerPortalProfileRouteImport } from './routes/customer-portal/profile'
import { Route as CustomerPortalNotificationsRouteImport } from './routes/customer-portal/notifications'
import { Route as CustomerPortalMessagesRouteImport } from './routes/customer-portal/messages'
import { Route as CustomerPortalInvoicesRouteImport } from './routes/customer-portal/invoices'
import { Route as CustomerPortalDocumentsRouteImport } from './routes/customer-portal/documents'
import { Route as CustomerPortalAssistantRouteImport } from './routes/customer-portal/assistant'
import { Route as CustomerPortalApiRouteImport } from './routes/customer-portal/api'
import { Route as CustomerPortalAnalyticsRouteImport } from './routes/customer-portal/analytics'
import { Route as AuthenticatedWarehouseRouteImport } from './routes/_authenticated/warehouse'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedRouteIntelligenceRouteImport } from './routes/_authenticated/route-intelligence'
import { Route as AuthenticatedReliabilityRouteImport } from './routes/_authenticated/reliability'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedOperationsIntelligenceRouteImport } from './routes/_authenticated/operations-intelligence'
import { Route as AuthenticatedOperationsControlRouteImport } from './routes/_authenticated/operations-control'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMobileRouteImport } from './routes/_authenticated/mobile'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedHardwareReadinessRouteImport } from './routes/_authenticated/hardware-readiness'
import { Route as AuthenticatedFleetIntelligenceRouteImport } from './routes/_authenticated/fleet-intelligence'
import { Route as AuthenticatedFleetBoardRouteImport } from './routes/_authenticated/fleet-board'
import { Route as AuthenticatedFieldDeploymentRouteImport } from './routes/_authenticated/field-deployment'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCustomerPortalRouteImport } from './routes/_authenticated/customer-portal'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCommandCentreRouteImport } from './routes/_authenticated/command-centre'
import { Route as AuthenticatedBusinessIntelligenceRouteImport } from './routes/_authenticated/business-intelligence'
import { Route as AuthenticatedBrainRouteImport } from './routes/_authenticated/brain'
import { Route as CustomerPortalShipmentsJobIdRouteImport } from './routes/customer-portal/shipments/$jobId'
import { Route as AuthenticatedTrackingWallRouteImport } from './routes/_authenticated/tracking/wall'
import { Route as AuthenticatedTrackingReplayRouteImport } from './routes/_authenticated/tracking/replay'
import { Route as AuthenticatedTrackingCustomerCareRouteImport } from './routes/_authenticated/tracking/customer-care'
import { Route as AuthenticatedTrackingControlRouteImport } from './routes/_authenticated/tracking/control'
import { Route as AuthenticatedMobileDriverRouteImport } from './routes/_authenticated/mobile/driver'
import { Route as AuthenticatedFleetBoardWallRouteImport } from './routes/_authenticated/fleet-board/wall'
import { Route as AuthenticatedFleetBoardTimelineRouteImport } from './routes/_authenticated/fleet-board/timeline'
import { Route as AuthenticatedFleetBoardReplayRouteImport } from './routes/_authenticated/fleet-board/replay'
import { Route as AuthenticatedFleetBoardLiveRouteImport } from './routes/_authenticated/fleet-board/live'
import { Route as AuthenticatedFleetBoardHourlyRouteImport } from './routes/_authenticated/fleet-board/hourly'
import { Route as AuthenticatedFleetBoardHandoversRouteImport } from './routes/_authenticated/fleet-board/handovers'
import { Route as AuthenticatedFleetBoardCustomerCareRouteImport } from './routes/_authenticated/fleet-board/customer-care'
import { Route as AuthenticatedDispatchWorkloadRouteImport } from './routes/_authenticated/dispatch/workload'
import { Route as AuthenticatedDispatchRoutesRouteImport } from './routes/_authenticated/dispatch/routes'
import { Route as AuthenticatedDispatchRecommendationsRouteImport } from './routes/_authenticated/dispatch/recommendations'
import { Route as AuthenticatedDispatchPlanningRouteImport } from './routes/_authenticated/dispatch/planning'
import { Route as AuthenticatedDispatchLiveRouteImport } from './routes/_authenticated/dispatch/live'
import { Route as AuthenticatedDispatchHistoryRouteImport } from './routes/_authenticated/dispatch/history'
import { Route as AuthenticatedDispatchExceptionsRouteImport } from './routes/_authenticated/dispatch/exceptions'
import { Route as AuthenticatedDispatchEtaRouteImport } from './routes/_authenticated/dispatch/eta'
import { Route as AuthenticatedBrainOperationsRouteImport } from './routes/_authenticated/brain/operations'
import { Route as AuthenticatedBrainEvaluationRouteImport } from './routes/_authenticated/brain/evaluation'
import { Route as AuthenticatedMobileDriverStopsRouteImport } from './routes/_authenticated/mobile/driver/stops'
import { Route as AuthenticatedMobileDriverPodRouteImport } from './routes/_authenticated/mobile/driver/pod'
import { Route as AuthenticatedMobileDriverOfflineRouteImport } from './routes/_authenticated/mobile/driver/offline'
import { Route as AuthenticatedMobileDriverNavigationRouteImport } from './routes/_authenticated/mobile/driver/navigation'
import { Route as AuthenticatedMobileDriverMessagesRouteImport } from './routes/_authenticated/mobile/driver/messages'
import { Route as AuthenticatedMobileDriverIssuesRouteImport } from './routes/_authenticated/mobile/driver/issues'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer-portal',
  path: '/customer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalIndexRoute = CustomerPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalShipmentsRoute = CustomerPortalShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalSettingsRoute = CustomerPortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalSecurityRoute = CustomerPortalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalRequestsRoute = CustomerPortalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalQuotesRoute = CustomerPortalQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalProfileRoute = CustomerPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalNotificationsRoute =
  CustomerPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => CustomerPortalRoute,
  } as any)
const CustomerPortalMessagesRoute = CustomerPortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalInvoicesRoute = CustomerPortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalDocumentsRoute = CustomerPortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalAssistantRoute = CustomerPortalAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalApiRoute = CustomerPortalApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const CustomerPortalAnalyticsRoute = CustomerPortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CustomerPortalRoute,
} as any)
const AuthenticatedWarehouseRoute = AuthenticatedWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRouteIntelligenceRoute =
  AuthenticatedRouteIntelligenceRouteImport.update({
    id: '/route-intelligence',
    path: '/route-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReliabilityRoute =
  AuthenticatedReliabilityRouteImport.update({
    id: '/reliability',
    path: '/reliability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsIntelligenceRoute =
  AuthenticatedOperationsIntelligenceRouteImport.update({
    id: '/operations-intelligence',
    path: '/operations-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsControlRoute =
  AuthenticatedOperationsControlRouteImport.update({
    id: '/operations-control',
    path: '/operations-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMobileRoute = AuthenticatedMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHardwareReadinessRoute =
  AuthenticatedHardwareReadinessRouteImport.update({
    id: '/hardware-readiness',
    path: '/hardware-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFleetIntelligenceRoute =
  AuthenticatedFleetIntelligenceRouteImport.update({
    id: '/fleet-intelligence',
    path: '/fleet-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFleetBoardRoute = AuthenticatedFleetBoardRouteImport.update({
  id: '/fleet-board',
  path: '/fleet-board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldDeploymentRoute =
  AuthenticatedFieldDeploymentRouteImport.update({
    id: '/field-deployment',
    path: '/field-deployment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerPortalRoute =
  AuthenticatedCustomerPortalRouteImport.update({
    id: '/customer-portal',
    path: '/customer-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCentreRoute =
  AuthenticatedCommandCentreRouteImport.update({
    id: '/command-centre',
    path: '/command-centre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessIntelligenceRoute =
  AuthenticatedBusinessIntelligenceRouteImport.update({
    id: '/business-intelligence',
    path: '/business-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrainRoute = AuthenticatedBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CustomerPortalShipmentsJobIdRoute =
  CustomerPortalShipmentsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => CustomerPortalShipmentsRoute,
  } as any)
const AuthenticatedTrackingWallRoute =
  AuthenticatedTrackingWallRouteImport.update({
    id: '/wall',
    path: '/wall',
    getParentRoute: () => AuthenticatedTrackingRoute,
  } as any)
const AuthenticatedTrackingReplayRoute =
  AuthenticatedTrackingReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => AuthenticatedTrackingRoute,
  } as any)
const AuthenticatedTrackingCustomerCareRoute =
  AuthenticatedTrackingCustomerCareRouteImport.update({
    id: '/customer-care',
    path: '/customer-care',
    getParentRoute: () => AuthenticatedTrackingRoute,
  } as any)
const AuthenticatedTrackingControlRoute =
  AuthenticatedTrackingControlRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => AuthenticatedTrackingRoute,
  } as any)
const AuthenticatedMobileDriverRoute =
  AuthenticatedMobileDriverRouteImport.update({
    id: '/driver',
    path: '/driver',
    getParentRoute: () => AuthenticatedMobileRoute,
  } as any)
const AuthenticatedFleetBoardWallRoute =
  AuthenticatedFleetBoardWallRouteImport.update({
    id: '/wall',
    path: '/wall',
    getParentRoute: () => AuthenticatedFleetBoardRoute,
  } as any)
const AuthenticatedFleetBoardTimelineRoute =
  AuthenticatedFleetBoardTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedFleetBoardRoute,
  } as any)
const AuthenticatedFleetBoardReplayRoute =
  AuthenticatedFleetBoardReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => AuthenticatedFleetBoardRoute,
  } as any)
const AuthenticatedFleetBoardLiveRoute =
  AuthenticatedFleetBoardLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedFleetBoardRoute,
  } as any)
const AuthenticatedFleetBoardHourlyRoute =
  AuthenticatedFleetBoardHourlyRouteImport.update({
    id: '/hourly',
    path: '/hourly',
    getParentRoute: () => AuthenticatedFleetBoardRoute,
  } as any)
const AuthenticatedFleetBoardHandoversRoute =
  AuthenticatedFleetBoardHandoversRouteImport.update({
    id: '/handovers',
    path: '/handovers',
    getParentRoute: () => AuthenticatedFleetBoardRoute,
  } as any)
const AuthenticatedFleetBoardCustomerCareRoute =
  AuthenticatedFleetBoardCustomerCareRouteImport.update({
    id: '/customer-care',
    path: '/customer-care',
    getParentRoute: () => AuthenticatedFleetBoardRoute,
  } as any)
const AuthenticatedDispatchWorkloadRoute =
  AuthenticatedDispatchWorkloadRouteImport.update({
    id: '/workload',
    path: '/workload',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedDispatchRoutesRoute =
  AuthenticatedDispatchRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedDispatchRecommendationsRoute =
  AuthenticatedDispatchRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedDispatchPlanningRoute =
  AuthenticatedDispatchPlanningRouteImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedDispatchLiveRoute =
  AuthenticatedDispatchLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedDispatchHistoryRoute =
  AuthenticatedDispatchHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedDispatchExceptionsRoute =
  AuthenticatedDispatchExceptionsRouteImport.update({
    id: '/exceptions',
    path: '/exceptions',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedDispatchEtaRoute =
  AuthenticatedDispatchEtaRouteImport.update({
    id: '/eta',
    path: '/eta',
    getParentRoute: () => AuthenticatedDispatchRoute,
  } as any)
const AuthenticatedBrainOperationsRoute =
  AuthenticatedBrainOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedBrainRoute,
  } as any)
const AuthenticatedBrainEvaluationRoute =
  AuthenticatedBrainEvaluationRouteImport.update({
    id: '/evaluation',
    path: '/evaluation',
    getParentRoute: () => AuthenticatedBrainRoute,
  } as any)
const AuthenticatedMobileDriverStopsRoute =
  AuthenticatedMobileDriverStopsRouteImport.update({
    id: '/stops',
    path: '/stops',
    getParentRoute: () => AuthenticatedMobileDriverRoute,
  } as any)
const AuthenticatedMobileDriverPodRoute =
  AuthenticatedMobileDriverPodRouteImport.update({
    id: '/pod',
    path: '/pod',
    getParentRoute: () => AuthenticatedMobileDriverRoute,
  } as any)
const AuthenticatedMobileDriverOfflineRoute =
  AuthenticatedMobileDriverOfflineRouteImport.update({
    id: '/offline',
    path: '/offline',
    getParentRoute: () => AuthenticatedMobileDriverRoute,
  } as any)
const AuthenticatedMobileDriverNavigationRoute =
  AuthenticatedMobileDriverNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AuthenticatedMobileDriverRoute,
  } as any)
const AuthenticatedMobileDriverMessagesRoute =
  AuthenticatedMobileDriverMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedMobileDriverRoute,
  } as any)
const AuthenticatedMobileDriverIssuesRoute =
  AuthenticatedMobileDriverIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedMobileDriverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customer-portal': typeof AuthenticatedCustomerPortalRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/brain': typeof AuthenticatedBrainRouteWithChildren
  '/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/command-centre': typeof AuthenticatedCommandCentreRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch': typeof AuthenticatedDispatchRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/field-deployment': typeof AuthenticatedFieldDeploymentRoute
  '/fleet-board': typeof AuthenticatedFleetBoardRouteWithChildren
  '/fleet-intelligence': typeof AuthenticatedFleetIntelligenceRoute
  '/hardware-readiness': typeof AuthenticatedHardwareReadinessRoute
  '/hr': typeof AuthenticatedHrRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/mobile': typeof AuthenticatedMobileRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/operations-control': typeof AuthenticatedOperationsControlRoute
  '/operations-intelligence': typeof AuthenticatedOperationsIntelligenceRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/reliability': typeof AuthenticatedReliabilityRoute
  '/route-intelligence': typeof AuthenticatedRouteIntelligenceRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracking': typeof AuthenticatedTrackingRouteWithChildren
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
  '/customer-portal/analytics': typeof CustomerPortalAnalyticsRoute
  '/customer-portal/api': typeof CustomerPortalApiRoute
  '/customer-portal/assistant': typeof CustomerPortalAssistantRoute
  '/customer-portal/documents': typeof CustomerPortalDocumentsRoute
  '/customer-portal/invoices': typeof CustomerPortalInvoicesRoute
  '/customer-portal/messages': typeof CustomerPortalMessagesRoute
  '/customer-portal/notifications': typeof CustomerPortalNotificationsRoute
  '/customer-portal/profile': typeof CustomerPortalProfileRoute
  '/customer-portal/quotes': typeof CustomerPortalQuotesRoute
  '/customer-portal/requests': typeof CustomerPortalRequestsRoute
  '/customer-portal/security': typeof CustomerPortalSecurityRoute
  '/customer-portal/settings': typeof CustomerPortalSettingsRoute
  '/customer-portal/shipments': typeof CustomerPortalShipmentsRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/customer-portal/': typeof CustomerPortalIndexRoute
  '/brain/evaluation': typeof AuthenticatedBrainEvaluationRoute
  '/brain/operations': typeof AuthenticatedBrainOperationsRoute
  '/dispatch/eta': typeof AuthenticatedDispatchEtaRoute
  '/dispatch/exceptions': typeof AuthenticatedDispatchExceptionsRoute
  '/dispatch/history': typeof AuthenticatedDispatchHistoryRoute
  '/dispatch/live': typeof AuthenticatedDispatchLiveRoute
  '/dispatch/planning': typeof AuthenticatedDispatchPlanningRoute
  '/dispatch/recommendations': typeof AuthenticatedDispatchRecommendationsRoute
  '/dispatch/routes': typeof AuthenticatedDispatchRoutesRoute
  '/dispatch/workload': typeof AuthenticatedDispatchWorkloadRoute
  '/fleet-board/customer-care': typeof AuthenticatedFleetBoardCustomerCareRoute
  '/fleet-board/handovers': typeof AuthenticatedFleetBoardHandoversRoute
  '/fleet-board/hourly': typeof AuthenticatedFleetBoardHourlyRoute
  '/fleet-board/live': typeof AuthenticatedFleetBoardLiveRoute
  '/fleet-board/replay': typeof AuthenticatedFleetBoardReplayRoute
  '/fleet-board/timeline': typeof AuthenticatedFleetBoardTimelineRoute
  '/fleet-board/wall': typeof AuthenticatedFleetBoardWallRoute
  '/mobile/driver': typeof AuthenticatedMobileDriverRouteWithChildren
  '/tracking/control': typeof AuthenticatedTrackingControlRoute
  '/tracking/customer-care': typeof AuthenticatedTrackingCustomerCareRoute
  '/tracking/replay': typeof AuthenticatedTrackingReplayRoute
  '/tracking/wall': typeof AuthenticatedTrackingWallRoute
  '/customer-portal/shipments/$jobId': typeof CustomerPortalShipmentsJobIdRoute
  '/mobile/driver/issues': typeof AuthenticatedMobileDriverIssuesRoute
  '/mobile/driver/messages': typeof AuthenticatedMobileDriverMessagesRoute
  '/mobile/driver/navigation': typeof AuthenticatedMobileDriverNavigationRoute
  '/mobile/driver/offline': typeof AuthenticatedMobileDriverOfflineRoute
  '/mobile/driver/pod': typeof AuthenticatedMobileDriverPodRoute
  '/mobile/driver/stops': typeof AuthenticatedMobileDriverStopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/brain': typeof AuthenticatedBrainRouteWithChildren
  '/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/command-centre': typeof AuthenticatedCommandCentreRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/customer-portal': typeof CustomerPortalIndexRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch': typeof AuthenticatedDispatchRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/field-deployment': typeof AuthenticatedFieldDeploymentRoute
  '/fleet-board': typeof AuthenticatedFleetBoardRouteWithChildren
  '/fleet-intelligence': typeof AuthenticatedFleetIntelligenceRoute
  '/hardware-readiness': typeof AuthenticatedHardwareReadinessRoute
  '/hr': typeof AuthenticatedHrRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/mobile': typeof AuthenticatedMobileRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/operations-control': typeof AuthenticatedOperationsControlRoute
  '/operations-intelligence': typeof AuthenticatedOperationsIntelligenceRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/reliability': typeof AuthenticatedReliabilityRoute
  '/route-intelligence': typeof AuthenticatedRouteIntelligenceRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracking': typeof AuthenticatedTrackingRouteWithChildren
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
  '/customer-portal/analytics': typeof CustomerPortalAnalyticsRoute
  '/customer-portal/api': typeof CustomerPortalApiRoute
  '/customer-portal/assistant': typeof CustomerPortalAssistantRoute
  '/customer-portal/documents': typeof CustomerPortalDocumentsRoute
  '/customer-portal/invoices': typeof CustomerPortalInvoicesRoute
  '/customer-portal/messages': typeof CustomerPortalMessagesRoute
  '/customer-portal/notifications': typeof CustomerPortalNotificationsRoute
  '/customer-portal/profile': typeof CustomerPortalProfileRoute
  '/customer-portal/quotes': typeof CustomerPortalQuotesRoute
  '/customer-portal/requests': typeof CustomerPortalRequestsRoute
  '/customer-portal/security': typeof CustomerPortalSecurityRoute
  '/customer-portal/settings': typeof CustomerPortalSettingsRoute
  '/customer-portal/shipments': typeof CustomerPortalShipmentsRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/brain/evaluation': typeof AuthenticatedBrainEvaluationRoute
  '/brain/operations': typeof AuthenticatedBrainOperationsRoute
  '/dispatch/eta': typeof AuthenticatedDispatchEtaRoute
  '/dispatch/exceptions': typeof AuthenticatedDispatchExceptionsRoute
  '/dispatch/history': typeof AuthenticatedDispatchHistoryRoute
  '/dispatch/live': typeof AuthenticatedDispatchLiveRoute
  '/dispatch/planning': typeof AuthenticatedDispatchPlanningRoute
  '/dispatch/recommendations': typeof AuthenticatedDispatchRecommendationsRoute
  '/dispatch/routes': typeof AuthenticatedDispatchRoutesRoute
  '/dispatch/workload': typeof AuthenticatedDispatchWorkloadRoute
  '/fleet-board/customer-care': typeof AuthenticatedFleetBoardCustomerCareRoute
  '/fleet-board/handovers': typeof AuthenticatedFleetBoardHandoversRoute
  '/fleet-board/hourly': typeof AuthenticatedFleetBoardHourlyRoute
  '/fleet-board/live': typeof AuthenticatedFleetBoardLiveRoute
  '/fleet-board/replay': typeof AuthenticatedFleetBoardReplayRoute
  '/fleet-board/timeline': typeof AuthenticatedFleetBoardTimelineRoute
  '/fleet-board/wall': typeof AuthenticatedFleetBoardWallRoute
  '/mobile/driver': typeof AuthenticatedMobileDriverRouteWithChildren
  '/tracking/control': typeof AuthenticatedTrackingControlRoute
  '/tracking/customer-care': typeof AuthenticatedTrackingCustomerCareRoute
  '/tracking/replay': typeof AuthenticatedTrackingReplayRoute
  '/tracking/wall': typeof AuthenticatedTrackingWallRoute
  '/customer-portal/shipments/$jobId': typeof CustomerPortalShipmentsJobIdRoute
  '/mobile/driver/issues': typeof AuthenticatedMobileDriverIssuesRoute
  '/mobile/driver/messages': typeof AuthenticatedMobileDriverMessagesRoute
  '/mobile/driver/navigation': typeof AuthenticatedMobileDriverNavigationRoute
  '/mobile/driver/offline': typeof AuthenticatedMobileDriverOfflineRoute
  '/mobile/driver/pod': typeof AuthenticatedMobileDriverPodRoute
  '/mobile/driver/stops': typeof AuthenticatedMobileDriverStopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/customer-portal': typeof CustomerPortalRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/brain': typeof AuthenticatedBrainRouteWithChildren
  '/_authenticated/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/_authenticated/command-centre': typeof AuthenticatedCommandCentreRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/customer-portal': typeof AuthenticatedCustomerPortalRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/field-deployment': typeof AuthenticatedFieldDeploymentRoute
  '/_authenticated/fleet-board': typeof AuthenticatedFleetBoardRouteWithChildren
  '/_authenticated/fleet-intelligence': typeof AuthenticatedFleetIntelligenceRoute
  '/_authenticated/hardware-readiness': typeof AuthenticatedHardwareReadinessRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/mobile': typeof AuthenticatedMobileRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/operations-control': typeof AuthenticatedOperationsControlRoute
  '/_authenticated/operations-intelligence': typeof AuthenticatedOperationsIntelligenceRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/reliability': typeof AuthenticatedReliabilityRoute
  '/_authenticated/route-intelligence': typeof AuthenticatedRouteIntelligenceRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRouteWithChildren
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/warehouse': typeof AuthenticatedWarehouseRoute
  '/customer-portal/analytics': typeof CustomerPortalAnalyticsRoute
  '/customer-portal/api': typeof CustomerPortalApiRoute
  '/customer-portal/assistant': typeof CustomerPortalAssistantRoute
  '/customer-portal/documents': typeof CustomerPortalDocumentsRoute
  '/customer-portal/invoices': typeof CustomerPortalInvoicesRoute
  '/customer-portal/messages': typeof CustomerPortalMessagesRoute
  '/customer-portal/notifications': typeof CustomerPortalNotificationsRoute
  '/customer-portal/profile': typeof CustomerPortalProfileRoute
  '/customer-portal/quotes': typeof CustomerPortalQuotesRoute
  '/customer-portal/requests': typeof CustomerPortalRequestsRoute
  '/customer-portal/security': typeof CustomerPortalSecurityRoute
  '/customer-portal/settings': typeof CustomerPortalSettingsRoute
  '/customer-portal/shipments': typeof CustomerPortalShipmentsRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/customer-portal/': typeof CustomerPortalIndexRoute
  '/_authenticated/brain/evaluation': typeof AuthenticatedBrainEvaluationRoute
  '/_authenticated/brain/operations': typeof AuthenticatedBrainOperationsRoute
  '/_authenticated/dispatch/eta': typeof AuthenticatedDispatchEtaRoute
  '/_authenticated/dispatch/exceptions': typeof AuthenticatedDispatchExceptionsRoute
  '/_authenticated/dispatch/history': typeof AuthenticatedDispatchHistoryRoute
  '/_authenticated/dispatch/live': typeof AuthenticatedDispatchLiveRoute
  '/_authenticated/dispatch/planning': typeof AuthenticatedDispatchPlanningRoute
  '/_authenticated/dispatch/recommendations': typeof AuthenticatedDispatchRecommendationsRoute
  '/_authenticated/dispatch/routes': typeof AuthenticatedDispatchRoutesRoute
  '/_authenticated/dispatch/workload': typeof AuthenticatedDispatchWorkloadRoute
  '/_authenticated/fleet-board/customer-care': typeof AuthenticatedFleetBoardCustomerCareRoute
  '/_authenticated/fleet-board/handovers': typeof AuthenticatedFleetBoardHandoversRoute
  '/_authenticated/fleet-board/hourly': typeof AuthenticatedFleetBoardHourlyRoute
  '/_authenticated/fleet-board/live': typeof AuthenticatedFleetBoardLiveRoute
  '/_authenticated/fleet-board/replay': typeof AuthenticatedFleetBoardReplayRoute
  '/_authenticated/fleet-board/timeline': typeof AuthenticatedFleetBoardTimelineRoute
  '/_authenticated/fleet-board/wall': typeof AuthenticatedFleetBoardWallRoute
  '/_authenticated/mobile/driver': typeof AuthenticatedMobileDriverRouteWithChildren
  '/_authenticated/tracking/control': typeof AuthenticatedTrackingControlRoute
  '/_authenticated/tracking/customer-care': typeof AuthenticatedTrackingCustomerCareRoute
  '/_authenticated/tracking/replay': typeof AuthenticatedTrackingReplayRoute
  '/_authenticated/tracking/wall': typeof AuthenticatedTrackingWallRoute
  '/customer-portal/shipments/$jobId': typeof CustomerPortalShipmentsJobIdRoute
  '/_authenticated/mobile/driver/issues': typeof AuthenticatedMobileDriverIssuesRoute
  '/_authenticated/mobile/driver/messages': typeof AuthenticatedMobileDriverMessagesRoute
  '/_authenticated/mobile/driver/navigation': typeof AuthenticatedMobileDriverNavigationRoute
  '/_authenticated/mobile/driver/offline': typeof AuthenticatedMobileDriverOfflineRoute
  '/_authenticated/mobile/driver/pod': typeof AuthenticatedMobileDriverPodRoute
  '/_authenticated/mobile/driver/stops': typeof AuthenticatedMobileDriverStopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/customer-portal'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/brain'
    | '/business-intelligence'
    | '/command-centre'
    | '/compliance'
    | '/connect'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/dispatch'
    | '/documents'
    | '/driver'
    | '/drivers'
    | '/field-deployment'
    | '/fleet-board'
    | '/fleet-intelligence'
    | '/hardware-readiness'
    | '/hr'
    | '/incidents'
    | '/integrations'
    | '/intelligence'
    | '/maintenance'
    | '/mobile'
    | '/notifications'
    | '/operations'
    | '/operations-control'
    | '/operations-intelligence'
    | '/platform'
    | '/procurement'
    | '/reliability'
    | '/route-intelligence'
    | '/security'
    | '/settings'
    | '/tracking'
    | '/vehicles'
    | '/warehouse'
    | '/customer-portal/analytics'
    | '/customer-portal/api'
    | '/customer-portal/assistant'
    | '/customer-portal/documents'
    | '/customer-portal/invoices'
    | '/customer-portal/messages'
    | '/customer-portal/notifications'
    | '/customer-portal/profile'
    | '/customer-portal/quotes'
    | '/customer-portal/requests'
    | '/customer-portal/security'
    | '/customer-portal/settings'
    | '/customer-portal/shipments'
    | '/share/$token'
    | '/customer-portal/'
    | '/brain/evaluation'
    | '/brain/operations'
    | '/dispatch/eta'
    | '/dispatch/exceptions'
    | '/dispatch/history'
    | '/dispatch/live'
    | '/dispatch/planning'
    | '/dispatch/recommendations'
    | '/dispatch/routes'
    | '/dispatch/workload'
    | '/fleet-board/customer-care'
    | '/fleet-board/handovers'
    | '/fleet-board/hourly'
    | '/fleet-board/live'
    | '/fleet-board/replay'
    | '/fleet-board/timeline'
    | '/fleet-board/wall'
    | '/mobile/driver'
    | '/tracking/control'
    | '/tracking/customer-care'
    | '/tracking/replay'
    | '/tracking/wall'
    | '/customer-portal/shipments/$jobId'
    | '/mobile/driver/issues'
    | '/mobile/driver/messages'
    | '/mobile/driver/navigation'
    | '/mobile/driver/offline'
    | '/mobile/driver/pod'
    | '/mobile/driver/stops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/brain'
    | '/business-intelligence'
    | '/command-centre'
    | '/compliance'
    | '/connect'
    | '/crm'
    | '/customer-portal'
    | '/customers'
    | '/dashboard'
    | '/dispatch'
    | '/documents'
    | '/driver'
    | '/drivers'
    | '/field-deployment'
    | '/fleet-board'
    | '/fleet-intelligence'
    | '/hardware-readiness'
    | '/hr'
    | '/incidents'
    | '/integrations'
    | '/intelligence'
    | '/maintenance'
    | '/mobile'
    | '/notifications'
    | '/operations'
    | '/operations-control'
    | '/operations-intelligence'
    | '/platform'
    | '/procurement'
    | '/reliability'
    | '/route-intelligence'
    | '/security'
    | '/settings'
    | '/tracking'
    | '/vehicles'
    | '/warehouse'
    | '/customer-portal/analytics'
    | '/customer-portal/api'
    | '/customer-portal/assistant'
    | '/customer-portal/documents'
    | '/customer-portal/invoices'
    | '/customer-portal/messages'
    | '/customer-portal/notifications'
    | '/customer-portal/profile'
    | '/customer-portal/quotes'
    | '/customer-portal/requests'
    | '/customer-portal/security'
    | '/customer-portal/settings'
    | '/customer-portal/shipments'
    | '/share/$token'
    | '/brain/evaluation'
    | '/brain/operations'
    | '/dispatch/eta'
    | '/dispatch/exceptions'
    | '/dispatch/history'
    | '/dispatch/live'
    | '/dispatch/planning'
    | '/dispatch/recommendations'
    | '/dispatch/routes'
    | '/dispatch/workload'
    | '/fleet-board/customer-care'
    | '/fleet-board/handovers'
    | '/fleet-board/hourly'
    | '/fleet-board/live'
    | '/fleet-board/replay'
    | '/fleet-board/timeline'
    | '/fleet-board/wall'
    | '/mobile/driver'
    | '/tracking/control'
    | '/tracking/customer-care'
    | '/tracking/replay'
    | '/tracking/wall'
    | '/customer-portal/shipments/$jobId'
    | '/mobile/driver/issues'
    | '/mobile/driver/messages'
    | '/mobile/driver/navigation'
    | '/mobile/driver/offline'
    | '/mobile/driver/pod'
    | '/mobile/driver/stops'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/customer-portal'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/brain'
    | '/_authenticated/business-intelligence'
    | '/_authenticated/command-centre'
    | '/_authenticated/compliance'
    | '/_authenticated/connect'
    | '/_authenticated/crm'
    | '/_authenticated/customer-portal'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispatch'
    | '/_authenticated/documents'
    | '/_authenticated/driver'
    | '/_authenticated/drivers'
    | '/_authenticated/field-deployment'
    | '/_authenticated/fleet-board'
    | '/_authenticated/fleet-intelligence'
    | '/_authenticated/hardware-readiness'
    | '/_authenticated/hr'
    | '/_authenticated/incidents'
    | '/_authenticated/integrations'
    | '/_authenticated/intelligence'
    | '/_authenticated/maintenance'
    | '/_authenticated/mobile'
    | '/_authenticated/notifications'
    | '/_authenticated/operations'
    | '/_authenticated/operations-control'
    | '/_authenticated/operations-intelligence'
    | '/_authenticated/platform'
    | '/_authenticated/procurement'
    | '/_authenticated/reliability'
    | '/_authenticated/route-intelligence'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/tracking'
    | '/_authenticated/vehicles'
    | '/_authenticated/warehouse'
    | '/customer-portal/analytics'
    | '/customer-portal/api'
    | '/customer-portal/assistant'
    | '/customer-portal/documents'
    | '/customer-portal/invoices'
    | '/customer-portal/messages'
    | '/customer-portal/notifications'
    | '/customer-portal/profile'
    | '/customer-portal/quotes'
    | '/customer-portal/requests'
    | '/customer-portal/security'
    | '/customer-portal/settings'
    | '/customer-portal/shipments'
    | '/share/$token'
    | '/customer-portal/'
    | '/_authenticated/brain/evaluation'
    | '/_authenticated/brain/operations'
    | '/_authenticated/dispatch/eta'
    | '/_authenticated/dispatch/exceptions'
    | '/_authenticated/dispatch/history'
    | '/_authenticated/dispatch/live'
    | '/_authenticated/dispatch/planning'
    | '/_authenticated/dispatch/recommendations'
    | '/_authenticated/dispatch/routes'
    | '/_authenticated/dispatch/workload'
    | '/_authenticated/fleet-board/customer-care'
    | '/_authenticated/fleet-board/handovers'
    | '/_authenticated/fleet-board/hourly'
    | '/_authenticated/fleet-board/live'
    | '/_authenticated/fleet-board/replay'
    | '/_authenticated/fleet-board/timeline'
    | '/_authenticated/fleet-board/wall'
    | '/_authenticated/mobile/driver'
    | '/_authenticated/tracking/control'
    | '/_authenticated/tracking/customer-care'
    | '/_authenticated/tracking/replay'
    | '/_authenticated/tracking/wall'
    | '/customer-portal/shipments/$jobId'
    | '/_authenticated/mobile/driver/issues'
    | '/_authenticated/mobile/driver/messages'
    | '/_authenticated/mobile/driver/navigation'
    | '/_authenticated/mobile/driver/offline'
    | '/_authenticated/mobile/driver/pod'
    | '/_authenticated/mobile/driver/stops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CustomerPortalRoute: typeof CustomerPortalRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal': {
      id: '/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal/': {
      id: '/customer-portal/'
      path: '/'
      fullPath: '/customer-portal/'
      preLoaderRoute: typeof CustomerPortalIndexRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal/shipments': {
      id: '/customer-portal/shipments'
      path: '/shipments'
      fullPath: '/customer-portal/shipments'
      preLoaderRoute: typeof CustomerPortalShipmentsRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/settings': {
      id: '/customer-portal/settings'
      path: '/settings'
      fullPath: '/customer-portal/settings'
      preLoaderRoute: typeof CustomerPortalSettingsRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/security': {
      id: '/customer-portal/security'
      path: '/security'
      fullPath: '/customer-portal/security'
      preLoaderRoute: typeof CustomerPortalSecurityRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/requests': {
      id: '/customer-portal/requests'
      path: '/requests'
      fullPath: '/customer-portal/requests'
      preLoaderRoute: typeof CustomerPortalRequestsRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/quotes': {
      id: '/customer-portal/quotes'
      path: '/quotes'
      fullPath: '/customer-portal/quotes'
      preLoaderRoute: typeof CustomerPortalQuotesRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/profile': {
      id: '/customer-portal/profile'
      path: '/profile'
      fullPath: '/customer-portal/profile'
      preLoaderRoute: typeof CustomerPortalProfileRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/notifications': {
      id: '/customer-portal/notifications'
      path: '/notifications'
      fullPath: '/customer-portal/notifications'
      preLoaderRoute: typeof CustomerPortalNotificationsRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/messages': {
      id: '/customer-portal/messages'
      path: '/messages'
      fullPath: '/customer-portal/messages'
      preLoaderRoute: typeof CustomerPortalMessagesRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/invoices': {
      id: '/customer-portal/invoices'
      path: '/invoices'
      fullPath: '/customer-portal/invoices'
      preLoaderRoute: typeof CustomerPortalInvoicesRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/documents': {
      id: '/customer-portal/documents'
      path: '/documents'
      fullPath: '/customer-portal/documents'
      preLoaderRoute: typeof CustomerPortalDocumentsRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/assistant': {
      id: '/customer-portal/assistant'
      path: '/assistant'
      fullPath: '/customer-portal/assistant'
      preLoaderRoute: typeof CustomerPortalAssistantRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/api': {
      id: '/customer-portal/api'
      path: '/api'
      fullPath: '/customer-portal/api'
      preLoaderRoute: typeof CustomerPortalApiRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/customer-portal/analytics': {
      id: '/customer-portal/analytics'
      path: '/analytics'
      fullPath: '/customer-portal/analytics'
      preLoaderRoute: typeof CustomerPortalAnalyticsRouteImport
      parentRoute: typeof CustomerPortalRoute
    }
    '/_authenticated/warehouse': {
      id: '/_authenticated/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthenticatedWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/route-intelligence': {
      id: '/_authenticated/route-intelligence'
      path: '/route-intelligence'
      fullPath: '/route-intelligence'
      preLoaderRoute: typeof AuthenticatedRouteIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reliability': {
      id: '/_authenticated/reliability'
      path: '/reliability'
      fullPath: '/reliability'
      preLoaderRoute: typeof AuthenticatedReliabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations-intelligence': {
      id: '/_authenticated/operations-intelligence'
      path: '/operations-intelligence'
      fullPath: '/operations-intelligence'
      preLoaderRoute: typeof AuthenticatedOperationsIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations-control': {
      id: '/_authenticated/operations-control'
      path: '/operations-control'
      fullPath: '/operations-control'
      preLoaderRoute: typeof AuthenticatedOperationsControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile': {
      id: '/_authenticated/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthenticatedMobileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hardware-readiness': {
      id: '/_authenticated/hardware-readiness'
      path: '/hardware-readiness'
      fullPath: '/hardware-readiness'
      preLoaderRoute: typeof AuthenticatedHardwareReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet-intelligence': {
      id: '/_authenticated/fleet-intelligence'
      path: '/fleet-intelligence'
      fullPath: '/fleet-intelligence'
      preLoaderRoute: typeof AuthenticatedFleetIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet-board': {
      id: '/_authenticated/fleet-board'
      path: '/fleet-board'
      fullPath: '/fleet-board'
      preLoaderRoute: typeof AuthenticatedFleetBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-deployment': {
      id: '/_authenticated/field-deployment'
      path: '/field-deployment'
      fullPath: '/field-deployment'
      preLoaderRoute: typeof AuthenticatedFieldDeploymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-portal': {
      id: '/_authenticated/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof AuthenticatedCustomerPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-centre': {
      id: '/_authenticated/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof AuthenticatedCommandCentreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-intelligence': {
      id: '/_authenticated/business-intelligence'
      path: '/business-intelligence'
      fullPath: '/business-intelligence'
      preLoaderRoute: typeof AuthenticatedBusinessIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brain': {
      id: '/_authenticated/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AuthenticatedBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/customer-portal/shipments/$jobId': {
      id: '/customer-portal/shipments/$jobId'
      path: '/$jobId'
      fullPath: '/customer-portal/shipments/$jobId'
      preLoaderRoute: typeof CustomerPortalShipmentsJobIdRouteImport
      parentRoute: typeof CustomerPortalShipmentsRoute
    }
    '/_authenticated/tracking/wall': {
      id: '/_authenticated/tracking/wall'
      path: '/wall'
      fullPath: '/tracking/wall'
      preLoaderRoute: typeof AuthenticatedTrackingWallRouteImport
      parentRoute: typeof AuthenticatedTrackingRoute
    }
    '/_authenticated/tracking/replay': {
      id: '/_authenticated/tracking/replay'
      path: '/replay'
      fullPath: '/tracking/replay'
      preLoaderRoute: typeof AuthenticatedTrackingReplayRouteImport
      parentRoute: typeof AuthenticatedTrackingRoute
    }
    '/_authenticated/tracking/customer-care': {
      id: '/_authenticated/tracking/customer-care'
      path: '/customer-care'
      fullPath: '/tracking/customer-care'
      preLoaderRoute: typeof AuthenticatedTrackingCustomerCareRouteImport
      parentRoute: typeof AuthenticatedTrackingRoute
    }
    '/_authenticated/tracking/control': {
      id: '/_authenticated/tracking/control'
      path: '/control'
      fullPath: '/tracking/control'
      preLoaderRoute: typeof AuthenticatedTrackingControlRouteImport
      parentRoute: typeof AuthenticatedTrackingRoute
    }
    '/_authenticated/mobile/driver': {
      id: '/_authenticated/mobile/driver'
      path: '/driver'
      fullPath: '/mobile/driver'
      preLoaderRoute: typeof AuthenticatedMobileDriverRouteImport
      parentRoute: typeof AuthenticatedMobileRoute
    }
    '/_authenticated/fleet-board/wall': {
      id: '/_authenticated/fleet-board/wall'
      path: '/wall'
      fullPath: '/fleet-board/wall'
      preLoaderRoute: typeof AuthenticatedFleetBoardWallRouteImport
      parentRoute: typeof AuthenticatedFleetBoardRoute
    }
    '/_authenticated/fleet-board/timeline': {
      id: '/_authenticated/fleet-board/timeline'
      path: '/timeline'
      fullPath: '/fleet-board/timeline'
      preLoaderRoute: typeof AuthenticatedFleetBoardTimelineRouteImport
      parentRoute: typeof AuthenticatedFleetBoardRoute
    }
    '/_authenticated/fleet-board/replay': {
      id: '/_authenticated/fleet-board/replay'
      path: '/replay'
      fullPath: '/fleet-board/replay'
      preLoaderRoute: typeof AuthenticatedFleetBoardReplayRouteImport
      parentRoute: typeof AuthenticatedFleetBoardRoute
    }
    '/_authenticated/fleet-board/live': {
      id: '/_authenticated/fleet-board/live'
      path: '/live'
      fullPath: '/fleet-board/live'
      preLoaderRoute: typeof AuthenticatedFleetBoardLiveRouteImport
      parentRoute: typeof AuthenticatedFleetBoardRoute
    }
    '/_authenticated/fleet-board/hourly': {
      id: '/_authenticated/fleet-board/hourly'
      path: '/hourly'
      fullPath: '/fleet-board/hourly'
      preLoaderRoute: typeof AuthenticatedFleetBoardHourlyRouteImport
      parentRoute: typeof AuthenticatedFleetBoardRoute
    }
    '/_authenticated/fleet-board/handovers': {
      id: '/_authenticated/fleet-board/handovers'
      path: '/handovers'
      fullPath: '/fleet-board/handovers'
      preLoaderRoute: typeof AuthenticatedFleetBoardHandoversRouteImport
      parentRoute: typeof AuthenticatedFleetBoardRoute
    }
    '/_authenticated/fleet-board/customer-care': {
      id: '/_authenticated/fleet-board/customer-care'
      path: '/customer-care'
      fullPath: '/fleet-board/customer-care'
      preLoaderRoute: typeof AuthenticatedFleetBoardCustomerCareRouteImport
      parentRoute: typeof AuthenticatedFleetBoardRoute
    }
    '/_authenticated/dispatch/workload': {
      id: '/_authenticated/dispatch/workload'
      path: '/workload'
      fullPath: '/dispatch/workload'
      preLoaderRoute: typeof AuthenticatedDispatchWorkloadRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/dispatch/routes': {
      id: '/_authenticated/dispatch/routes'
      path: '/routes'
      fullPath: '/dispatch/routes'
      preLoaderRoute: typeof AuthenticatedDispatchRoutesRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/dispatch/recommendations': {
      id: '/_authenticated/dispatch/recommendations'
      path: '/recommendations'
      fullPath: '/dispatch/recommendations'
      preLoaderRoute: typeof AuthenticatedDispatchRecommendationsRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/dispatch/planning': {
      id: '/_authenticated/dispatch/planning'
      path: '/planning'
      fullPath: '/dispatch/planning'
      preLoaderRoute: typeof AuthenticatedDispatchPlanningRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/dispatch/live': {
      id: '/_authenticated/dispatch/live'
      path: '/live'
      fullPath: '/dispatch/live'
      preLoaderRoute: typeof AuthenticatedDispatchLiveRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/dispatch/history': {
      id: '/_authenticated/dispatch/history'
      path: '/history'
      fullPath: '/dispatch/history'
      preLoaderRoute: typeof AuthenticatedDispatchHistoryRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/dispatch/exceptions': {
      id: '/_authenticated/dispatch/exceptions'
      path: '/exceptions'
      fullPath: '/dispatch/exceptions'
      preLoaderRoute: typeof AuthenticatedDispatchExceptionsRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/dispatch/eta': {
      id: '/_authenticated/dispatch/eta'
      path: '/eta'
      fullPath: '/dispatch/eta'
      preLoaderRoute: typeof AuthenticatedDispatchEtaRouteImport
      parentRoute: typeof AuthenticatedDispatchRoute
    }
    '/_authenticated/brain/operations': {
      id: '/_authenticated/brain/operations'
      path: '/operations'
      fullPath: '/brain/operations'
      preLoaderRoute: typeof AuthenticatedBrainOperationsRouteImport
      parentRoute: typeof AuthenticatedBrainRoute
    }
    '/_authenticated/brain/evaluation': {
      id: '/_authenticated/brain/evaluation'
      path: '/evaluation'
      fullPath: '/brain/evaluation'
      preLoaderRoute: typeof AuthenticatedBrainEvaluationRouteImport
      parentRoute: typeof AuthenticatedBrainRoute
    }
    '/_authenticated/mobile/driver/stops': {
      id: '/_authenticated/mobile/driver/stops'
      path: '/stops'
      fullPath: '/mobile/driver/stops'
      preLoaderRoute: typeof AuthenticatedMobileDriverStopsRouteImport
      parentRoute: typeof AuthenticatedMobileDriverRoute
    }
    '/_authenticated/mobile/driver/pod': {
      id: '/_authenticated/mobile/driver/pod'
      path: '/pod'
      fullPath: '/mobile/driver/pod'
      preLoaderRoute: typeof AuthenticatedMobileDriverPodRouteImport
      parentRoute: typeof AuthenticatedMobileDriverRoute
    }
    '/_authenticated/mobile/driver/offline': {
      id: '/_authenticated/mobile/driver/offline'
      path: '/offline'
      fullPath: '/mobile/driver/offline'
      preLoaderRoute: typeof AuthenticatedMobileDriverOfflineRouteImport
      parentRoute: typeof AuthenticatedMobileDriverRoute
    }
    '/_authenticated/mobile/driver/navigation': {
      id: '/_authenticated/mobile/driver/navigation'
      path: '/navigation'
      fullPath: '/mobile/driver/navigation'
      preLoaderRoute: typeof AuthenticatedMobileDriverNavigationRouteImport
      parentRoute: typeof AuthenticatedMobileDriverRoute
    }
    '/_authenticated/mobile/driver/messages': {
      id: '/_authenticated/mobile/driver/messages'
      path: '/messages'
      fullPath: '/mobile/driver/messages'
      preLoaderRoute: typeof AuthenticatedMobileDriverMessagesRouteImport
      parentRoute: typeof AuthenticatedMobileDriverRoute
    }
    '/_authenticated/mobile/driver/issues': {
      id: '/_authenticated/mobile/driver/issues'
      path: '/issues'
      fullPath: '/mobile/driver/issues'
      preLoaderRoute: typeof AuthenticatedMobileDriverIssuesRouteImport
      parentRoute: typeof AuthenticatedMobileDriverRoute
    }
  }
}

interface AuthenticatedBrainRouteChildren {
  AuthenticatedBrainEvaluationRoute: typeof AuthenticatedBrainEvaluationRoute
  AuthenticatedBrainOperationsRoute: typeof AuthenticatedBrainOperationsRoute
}

const AuthenticatedBrainRouteChildren: AuthenticatedBrainRouteChildren = {
  AuthenticatedBrainEvaluationRoute: AuthenticatedBrainEvaluationRoute,
  AuthenticatedBrainOperationsRoute: AuthenticatedBrainOperationsRoute,
}

const AuthenticatedBrainRouteWithChildren =
  AuthenticatedBrainRoute._addFileChildren(AuthenticatedBrainRouteChildren)

interface AuthenticatedDispatchRouteChildren {
  AuthenticatedDispatchEtaRoute: typeof AuthenticatedDispatchEtaRoute
  AuthenticatedDispatchExceptionsRoute: typeof AuthenticatedDispatchExceptionsRoute
  AuthenticatedDispatchHistoryRoute: typeof AuthenticatedDispatchHistoryRoute
  AuthenticatedDispatchLiveRoute: typeof AuthenticatedDispatchLiveRoute
  AuthenticatedDispatchPlanningRoute: typeof AuthenticatedDispatchPlanningRoute
  AuthenticatedDispatchRecommendationsRoute: typeof AuthenticatedDispatchRecommendationsRoute
  AuthenticatedDispatchRoutesRoute: typeof AuthenticatedDispatchRoutesRoute
  AuthenticatedDispatchWorkloadRoute: typeof AuthenticatedDispatchWorkloadRoute
}

const AuthenticatedDispatchRouteChildren: AuthenticatedDispatchRouteChildren = {
  AuthenticatedDispatchEtaRoute: AuthenticatedDispatchEtaRoute,
  AuthenticatedDispatchExceptionsRoute: AuthenticatedDispatchExceptionsRoute,
  AuthenticatedDispatchHistoryRoute: AuthenticatedDispatchHistoryRoute,
  AuthenticatedDispatchLiveRoute: AuthenticatedDispatchLiveRoute,
  AuthenticatedDispatchPlanningRoute: AuthenticatedDispatchPlanningRoute,
  AuthenticatedDispatchRecommendationsRoute:
    AuthenticatedDispatchRecommendationsRoute,
  AuthenticatedDispatchRoutesRoute: AuthenticatedDispatchRoutesRoute,
  AuthenticatedDispatchWorkloadRoute: AuthenticatedDispatchWorkloadRoute,
}

const AuthenticatedDispatchRouteWithChildren =
  AuthenticatedDispatchRoute._addFileChildren(
    AuthenticatedDispatchRouteChildren,
  )

interface AuthenticatedFleetBoardRouteChildren {
  AuthenticatedFleetBoardCustomerCareRoute: typeof AuthenticatedFleetBoardCustomerCareRoute
  AuthenticatedFleetBoardHandoversRoute: typeof AuthenticatedFleetBoardHandoversRoute
  AuthenticatedFleetBoardHourlyRoute: typeof AuthenticatedFleetBoardHourlyRoute
  AuthenticatedFleetBoardLiveRoute: typeof AuthenticatedFleetBoardLiveRoute
  AuthenticatedFleetBoardReplayRoute: typeof AuthenticatedFleetBoardReplayRoute
  AuthenticatedFleetBoardTimelineRoute: typeof AuthenticatedFleetBoardTimelineRoute
  AuthenticatedFleetBoardWallRoute: typeof AuthenticatedFleetBoardWallRoute
}

const AuthenticatedFleetBoardRouteChildren: AuthenticatedFleetBoardRouteChildren =
  {
    AuthenticatedFleetBoardCustomerCareRoute:
      AuthenticatedFleetBoardCustomerCareRoute,
    AuthenticatedFleetBoardHandoversRoute:
      AuthenticatedFleetBoardHandoversRoute,
    AuthenticatedFleetBoardHourlyRoute: AuthenticatedFleetBoardHourlyRoute,
    AuthenticatedFleetBoardLiveRoute: AuthenticatedFleetBoardLiveRoute,
    AuthenticatedFleetBoardReplayRoute: AuthenticatedFleetBoardReplayRoute,
    AuthenticatedFleetBoardTimelineRoute: AuthenticatedFleetBoardTimelineRoute,
    AuthenticatedFleetBoardWallRoute: AuthenticatedFleetBoardWallRoute,
  }

const AuthenticatedFleetBoardRouteWithChildren =
  AuthenticatedFleetBoardRoute._addFileChildren(
    AuthenticatedFleetBoardRouteChildren,
  )

interface AuthenticatedMobileDriverRouteChildren {
  AuthenticatedMobileDriverIssuesRoute: typeof AuthenticatedMobileDriverIssuesRoute
  AuthenticatedMobileDriverMessagesRoute: typeof AuthenticatedMobileDriverMessagesRoute
  AuthenticatedMobileDriverNavigationRoute: typeof AuthenticatedMobileDriverNavigationRoute
  AuthenticatedMobileDriverOfflineRoute: typeof AuthenticatedMobileDriverOfflineRoute
  AuthenticatedMobileDriverPodRoute: typeof AuthenticatedMobileDriverPodRoute
  AuthenticatedMobileDriverStopsRoute: typeof AuthenticatedMobileDriverStopsRoute
}

const AuthenticatedMobileDriverRouteChildren: AuthenticatedMobileDriverRouteChildren =
  {
    AuthenticatedMobileDriverIssuesRoute: AuthenticatedMobileDriverIssuesRoute,
    AuthenticatedMobileDriverMessagesRoute:
      AuthenticatedMobileDriverMessagesRoute,
    AuthenticatedMobileDriverNavigationRoute:
      AuthenticatedMobileDriverNavigationRoute,
    AuthenticatedMobileDriverOfflineRoute:
      AuthenticatedMobileDriverOfflineRoute,
    AuthenticatedMobileDriverPodRoute: AuthenticatedMobileDriverPodRoute,
    AuthenticatedMobileDriverStopsRoute: AuthenticatedMobileDriverStopsRoute,
  }

const AuthenticatedMobileDriverRouteWithChildren =
  AuthenticatedMobileDriverRoute._addFileChildren(
    AuthenticatedMobileDriverRouteChildren,
  )

interface AuthenticatedMobileRouteChildren {
  AuthenticatedMobileDriverRoute: typeof AuthenticatedMobileDriverRouteWithChildren
}

const AuthenticatedMobileRouteChildren: AuthenticatedMobileRouteChildren = {
  AuthenticatedMobileDriverRoute: AuthenticatedMobileDriverRouteWithChildren,
}

const AuthenticatedMobileRouteWithChildren =
  AuthenticatedMobileRoute._addFileChildren(AuthenticatedMobileRouteChildren)

interface AuthenticatedTrackingRouteChildren {
  AuthenticatedTrackingControlRoute: typeof AuthenticatedTrackingControlRoute
  AuthenticatedTrackingCustomerCareRoute: typeof AuthenticatedTrackingCustomerCareRoute
  AuthenticatedTrackingReplayRoute: typeof AuthenticatedTrackingReplayRoute
  AuthenticatedTrackingWallRoute: typeof AuthenticatedTrackingWallRoute
}

const AuthenticatedTrackingRouteChildren: AuthenticatedTrackingRouteChildren = {
  AuthenticatedTrackingControlRoute: AuthenticatedTrackingControlRoute,
  AuthenticatedTrackingCustomerCareRoute:
    AuthenticatedTrackingCustomerCareRoute,
  AuthenticatedTrackingReplayRoute: AuthenticatedTrackingReplayRoute,
  AuthenticatedTrackingWallRoute: AuthenticatedTrackingWallRoute,
}

const AuthenticatedTrackingRouteWithChildren =
  AuthenticatedTrackingRoute._addFileChildren(
    AuthenticatedTrackingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrainRoute: typeof AuthenticatedBrainRouteWithChildren
  AuthenticatedBusinessIntelligenceRoute: typeof AuthenticatedBusinessIntelligenceRoute
  AuthenticatedCommandCentreRoute: typeof AuthenticatedCommandCentreRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedCustomerPortalRoute: typeof AuthenticatedCustomerPortalRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRouteWithChildren
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedFieldDeploymentRoute: typeof AuthenticatedFieldDeploymentRoute
  AuthenticatedFleetBoardRoute: typeof AuthenticatedFleetBoardRouteWithChildren
  AuthenticatedFleetIntelligenceRoute: typeof AuthenticatedFleetIntelligenceRoute
  AuthenticatedHardwareReadinessRoute: typeof AuthenticatedHardwareReadinessRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMobileRoute: typeof AuthenticatedMobileRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedOperationsControlRoute: typeof AuthenticatedOperationsControlRoute
  AuthenticatedOperationsIntelligenceRoute: typeof AuthenticatedOperationsIntelligenceRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedReliabilityRoute: typeof AuthenticatedReliabilityRoute
  AuthenticatedRouteIntelligenceRoute: typeof AuthenticatedRouteIntelligenceRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRouteWithChildren
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedWarehouseRoute: typeof AuthenticatedWarehouseRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrainRoute: AuthenticatedBrainRouteWithChildren,
  AuthenticatedBusinessIntelligenceRoute:
    AuthenticatedBusinessIntelligenceRoute,
  AuthenticatedCommandCentreRoute: AuthenticatedCommandCentreRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedCustomerPortalRoute: AuthenticatedCustomerPortalRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRouteWithChildren,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedFieldDeploymentRoute: AuthenticatedFieldDeploymentRoute,
  AuthenticatedFleetBoardRoute: AuthenticatedFleetBoardRouteWithChildren,
  AuthenticatedFleetIntelligenceRoute: AuthenticatedFleetIntelligenceRoute,
  AuthenticatedHardwareReadinessRoute: AuthenticatedHardwareReadinessRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMobileRoute: AuthenticatedMobileRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedOperationsControlRoute: AuthenticatedOperationsControlRoute,
  AuthenticatedOperationsIntelligenceRoute:
    AuthenticatedOperationsIntelligenceRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedReliabilityRoute: AuthenticatedReliabilityRoute,
  AuthenticatedRouteIntelligenceRoute: AuthenticatedRouteIntelligenceRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRouteWithChildren,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedWarehouseRoute: AuthenticatedWarehouseRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CustomerPortalShipmentsRouteChildren {
  CustomerPortalShipmentsJobIdRoute: typeof CustomerPortalShipmentsJobIdRoute
}

const CustomerPortalShipmentsRouteChildren: CustomerPortalShipmentsRouteChildren =
  {
    CustomerPortalShipmentsJobIdRoute: CustomerPortalShipmentsJobIdRoute,
  }

const CustomerPortalShipmentsRouteWithChildren =
  CustomerPortalShipmentsRoute._addFileChildren(
    CustomerPortalShipmentsRouteChildren,
  )

interface CustomerPortalRouteChildren {
  CustomerPortalAnalyticsRoute: typeof CustomerPortalAnalyticsRoute
  CustomerPortalApiRoute: typeof CustomerPortalApiRoute
  CustomerPortalAssistantRoute: typeof CustomerPortalAssistantRoute
  CustomerPortalDocumentsRoute: typeof CustomerPortalDocumentsRoute
  CustomerPortalInvoicesRoute: typeof CustomerPortalInvoicesRoute
  CustomerPortalMessagesRoute: typeof CustomerPortalMessagesRoute
  CustomerPortalNotificationsRoute: typeof CustomerPortalNotificationsRoute
  CustomerPortalProfileRoute: typeof CustomerPortalProfileRoute
  CustomerPortalQuotesRoute: typeof CustomerPortalQuotesRoute
  CustomerPortalRequestsRoute: typeof CustomerPortalRequestsRoute
  CustomerPortalSecurityRoute: typeof CustomerPortalSecurityRoute
  CustomerPortalSettingsRoute: typeof CustomerPortalSettingsRoute
  CustomerPortalShipmentsRoute: typeof CustomerPortalShipmentsRouteWithChildren
  CustomerPortalIndexRoute: typeof CustomerPortalIndexRoute
}

const CustomerPortalRouteChildren: CustomerPortalRouteChildren = {
  CustomerPortalAnalyticsRoute: CustomerPortalAnalyticsRoute,
  CustomerPortalApiRoute: CustomerPortalApiRoute,
  CustomerPortalAssistantRoute: CustomerPortalAssistantRoute,
  CustomerPortalDocumentsRoute: CustomerPortalDocumentsRoute,
  CustomerPortalInvoicesRoute: CustomerPortalInvoicesRoute,
  CustomerPortalMessagesRoute: CustomerPortalMessagesRoute,
  CustomerPortalNotificationsRoute: CustomerPortalNotificationsRoute,
  CustomerPortalProfileRoute: CustomerPortalProfileRoute,
  CustomerPortalQuotesRoute: CustomerPortalQuotesRoute,
  CustomerPortalRequestsRoute: CustomerPortalRequestsRoute,
  CustomerPortalSecurityRoute: CustomerPortalSecurityRoute,
  CustomerPortalSettingsRoute: CustomerPortalSettingsRoute,
  CustomerPortalShipmentsRoute: CustomerPortalShipmentsRouteWithChildren,
  CustomerPortalIndexRoute: CustomerPortalIndexRoute,
}

const CustomerPortalRouteWithChildren = CustomerPortalRoute._addFileChildren(
  CustomerPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CustomerPortalRoute: CustomerPortalRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
