-- Phase 36: governed dispatch decision support.  Evidence is append-only and
-- recommendations never own or mutate jobs, trips, routes, or assignments.
CREATE OR REPLACE FUNCTION public.dispatch36_read(c uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT public.is_company_member(c) AND public.has_any_role(c, ARRAY[
    'admin','dispatcher','fleet_controller','operations_manager','fleet_manager',
    'route_planner','customer_care','commercial_manager','compliance_manager',
    'executive','brain_analyst','brain_reviewer','viewer'
  ]::public.app_role[])
$$;
CREATE OR REPLACE FUNCTION public.dispatch36_write(c uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT public.dispatch36_read(c) AND public.has_any_role(c, ARRAY[
    'admin','dispatcher','fleet_controller','operations_manager','fleet_manager','route_planner'
  ]::public.app_role[])
$$;

CREATE TABLE public.dispatch_candidate_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, job_id uuid, candidate_type text NOT NULL, candidate_id uuid NOT NULL, eligibility jsonb NOT NULL DEFAULT '{}', score jsonb NOT NULL DEFAULT '{}', evidence jsonb NOT NULL DEFAULT '[]', freshness jsonb NOT NULL DEFAULT '{}', input_hash text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_candidate_scores (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, assessment_id uuid REFERENCES public.dispatch_candidate_assessments(id) ON DELETE CASCADE, score numeric CHECK(score BETWEEN 0 AND 100), score_version text NOT NULL, weighting_version text NOT NULL, raw_factors jsonb NOT NULL DEFAULT '{}', normalised_factors jsonb NOT NULL DEFAULT '{}', risk_penalties jsonb NOT NULL DEFAULT '[]', confidence text NOT NULL, missing_data jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_eligibility_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, job_id uuid, candidate_type text NOT NULL, candidate_id uuid NOT NULL, eligible boolean NOT NULL, checks jsonb NOT NULL DEFAULT '{}', rejection_reasons jsonb NOT NULL DEFAULT '[]', missing_data jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_eta_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, job_id uuid, trip_id uuid, eta timestamptz, eta_range_minutes integer, confidence text NOT NULL, primary_factors jsonb NOT NULL DEFAULT '[]', delay_factors jsonb NOT NULL DEFAULT '[]', missing_inputs jsonb NOT NULL DEFAULT '[]', assumptions jsonb NOT NULL DEFAULT '[]', source_inputs jsonb NOT NULL DEFAULT '{}', model_version text NOT NULL DEFAULT 'phase36-deterministic-v1', calculated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_eta_outcomes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, eta_assessment_id uuid NOT NULL REFERENCES public.dispatch_eta_assessments(id) ON DELETE CASCADE, predicted_eta timestamptz NOT NULL, actual_arrival timestamptz, absolute_error_minutes numeric, direction text, confidence_band_minutes integer, route_id uuid, customer_id uuid, depot_id uuid, vehicle_class text, data_quality jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_delay_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, job_id uuid, trip_id uuid, delay_type text NOT NULL, detected_at timestamptz NOT NULL, duration_minutes integer NOT NULL DEFAULT 0, severity text NOT NULL, confidence text NOT NULL, evidence jsonb NOT NULL DEFAULT '[]', customer_impact jsonb NOT NULL DEFAULT '{}', affected_jobs uuid[] NOT NULL DEFAULT '{}', recommended_response text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_customer_impact_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, job_id uuid, recommendation_id uuid, affected_shipments uuid[] NOT NULL DEFAULT '{}', affected_customers uuid[] NOT NULL DEFAULT '{}', eta_change_minutes numeric, sla_risk boolean NOT NULL DEFAULT false, delivery_window_risk boolean NOT NULL DEFAULT false, downstream_stop_impact integer NOT NULL DEFAULT 0, customer_safe_summary text, communication_required boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_consolidation_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, job_ids uuid[] NOT NULL, proposed_trip jsonb NOT NULL DEFAULT '{}', comparison jsonb NOT NULL DEFAULT '{}', constraints jsonb NOT NULL DEFAULT '[]', confidence text NOT NULL, risks jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_backhaul_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, vehicle_id uuid, job_id uuid, opportunity_type text NOT NULL, demand jsonb NOT NULL DEFAULT '{}', remaining_capacity jsonb NOT NULL DEFAULT '{}', confidence text NOT NULL, risks jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_stop_sequence_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, trip_id uuid, current_sequence jsonb NOT NULL, proposed_sequence jsonb NOT NULL, comparison jsonb NOT NULL DEFAULT '{}', constraints jsonb NOT NULL DEFAULT '[]', confidence text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_driver_hours_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, driver_id uuid, job_id uuid, shift_start timestamptz, driving_minutes numeric, duty_minutes numeric, remaining_driving_minutes numeric, remaining_duty_minutes numeric, next_required_rest_minutes numeric, policy_version text NOT NULL, eligible boolean NOT NULL, violations jsonb NOT NULL DEFAULT '[]', freshness jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_capacity_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, vehicle_id uuid, job_id uuid, used_capacity jsonb NOT NULL DEFAULT '{}', remaining_capacity jsonb NOT NULL DEFAULT '{}', utilisation numeric, violated_constraints jsonb NOT NULL DEFAULT '[]', missing_data jsonb NOT NULL DEFAULT '[]', confidence text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_depot_readiness_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, depot_id uuid, job_id uuid, ready boolean NOT NULL, inventory jsonb NOT NULL DEFAULT '{}', dock jsonb NOT NULL DEFAULT '{}', queue_length integer, estimated_loading_minutes integer, failures jsonb NOT NULL DEFAULT '[]', confidence text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.dispatch_recommendations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, job_id uuid, recommendation_type text NOT NULL, status text NOT NULL DEFAULT 'generated', candidate_list jsonb NOT NULL DEFAULT '[]', feature_versions jsonb NOT NULL DEFAULT '{}', rule_versions jsonb NOT NULL DEFAULT '{}', scoring_configuration jsonb NOT NULL DEFAULT '{}', input_hash text, output_hash text, evidence jsonb NOT NULL DEFAULT '[]', generated_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz);
CREATE TABLE public.dispatch_recommendation_decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, recommendation_id uuid NOT NULL REFERENCES public.dispatch_recommendations(id) ON DELETE RESTRICT, decision text NOT NULL CHECK(decision IN ('accepted','rejected','modified','deferred')), reason text, modified_values jsonb NOT NULL DEFAULT '{}', evidence_viewed jsonb NOT NULL DEFAULT '[]', decided_by uuid NOT NULL DEFAULT auth.uid(), decided_at timestamptz NOT NULL DEFAULT now(), resulting_record jsonb NOT NULL DEFAULT '{}');
CREATE TABLE public.dispatch_simulation_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, scenario text NOT NULL, inputs jsonb NOT NULL DEFAULT '{}', started_by uuid NOT NULL DEFAULT auth.uid(), started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, state_unchanged boolean NOT NULL DEFAULT true);
CREATE TABLE public.dispatch_simulation_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, run_id uuid NOT NULL REFERENCES public.dispatch_simulation_runs(id) ON DELETE CASCADE, affected_jobs uuid[] NOT NULL DEFAULT '{}', eta_changes jsonb NOT NULL DEFAULT '[]', capacity_changes jsonb NOT NULL DEFAULT '[]', customer_impact jsonb NOT NULL DEFAULT '{}', assumptions jsonb NOT NULL DEFAULT '[]', unresolved_constraints jsonb NOT NULL DEFAULT '[]');
CREATE TABLE public.dispatch_configuration_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, version text NOT NULL, scoring_weights jsonb NOT NULL DEFAULT '{}', policy jsonb NOT NULL DEFAULT '{}', lifecycle text NOT NULL DEFAULT 'draft', changed_by uuid DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,version));
CREATE TABLE public.dispatch_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, event_type text NOT NULL, entity_type text NOT NULL, entity_id uuid NOT NULL, actor_id uuid DEFAULT auth.uid(), metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());

CREATE OR REPLACE FUNCTION public.dispatch36_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Phase 36 evidence is append-only'; END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['dispatch_candidate_assessments','dispatch_candidate_scores','dispatch_eligibility_results','dispatch_eta_assessments','dispatch_eta_outcomes','dispatch_delay_assessments','dispatch_customer_impact_assessments','dispatch_consolidation_assessments','dispatch_backhaul_assessments','dispatch_stop_sequence_assessments','dispatch_driver_hours_assessments','dispatch_capacity_assessments','dispatch_depot_readiness_assessments','dispatch_recommendations','dispatch_recommendation_decisions','dispatch_simulation_runs','dispatch_simulation_results','dispatch_audit_logs'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon',t); EXECUTE format('GRANT SELECT,INSERT ON public.%I TO authenticated',t); EXECUTE format('CREATE POLICY %I_read ON public.%I FOR SELECT TO authenticated USING(public.dispatch36_read(company_id))',t,t); EXECUTE format('CREATE POLICY %I_insert ON public.%I FOR INSERT TO authenticated WITH CHECK(public.dispatch36_write(company_id))',t,t); EXECUTE format('CREATE TRIGGER %I_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.dispatch36_append_only()',t,t); END LOOP; END $$;
CREATE POLICY dispatch36_customer_safe_read ON public.dispatch_customer_impact_assessments FOR SELECT TO authenticated USING(public.is_company_member(dispatch_customer_impact_assessments.company_id) AND EXISTS(SELECT 1 FROM public.customer_portal_memberships m WHERE m.company_id=dispatch_customer_impact_assessments.company_id AND m.user_id=auth.uid() AND m.status='active'));
