CREATE OR REPLACE FUNCTION public.integration_reader(_company UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.has_any_role(_company, ARRAY['admin','integration_manager','system_administrator','technical_administrator','api_developer','support_engineer','viewer']::public.app_role[]) $$;
CREATE OR REPLACE FUNCTION public.integration_manager(_company UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.has_any_role(_company, ARRAY['admin','integration_manager','system_administrator','technical_administrator']::public.app_role[]) $$;
CREATE OR REPLACE FUNCTION public.integration_developer(_company UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.integration_manager(_company) OR public.has_role(_company,'api_developer') $$;
CREATE OR REPLACE FUNCTION public.integration_owner_or_manager(_company UUID,_owner UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT _owner=auth.uid() OR public.integration_manager(_company) $$;
CREATE OR REPLACE FUNCTION public.integration_secure_reference(_value TEXT) RETURNS BOOLEAN LANGUAGE sql IMMUTABLE AS $$ SELECT _value IS NULL OR _value ~ '^(vault|kms|secret-manager|keychain|external):' $$;

ALTER TABLE public.integration_connections ADD CONSTRAINT integration_connections_secret_reference CHECK(public.integration_secure_reference(secret_reference) AND public.integration_secure_reference(service_account_reference) AND public.integration_secure_reference(refresh_reference));
ALTER TABLE public.integration_api_keys ADD CONSTRAINT integration_api_keys_secret_reference CHECK(public.integration_secure_reference(secret_reference));
ALTER TABLE public.integration_webhook_endpoints ADD CONSTRAINT integration_webhooks_secret_reference CHECK(public.integration_secure_reference(secret_reference));

CREATE OR REPLACE FUNCTION public.integration_lifecycle_guard() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
  IF TG_TABLE_NAME='integration_webhook_deliveries' AND TG_OP='INSERT' AND NEW.status <> 'queued' THEN RAISE EXCEPTION 'Webhook deliveries must start queued'; END IF;
  IF TG_TABLE_NAME='integration_webhook_deliveries' AND TG_OP='UPDATE' AND NOT ((OLD.status='queued' AND NEW.status IN ('queued','delivering','failed','retry_scheduled')) OR (OLD.status='delivering' AND NEW.status IN ('succeeded','failed','retry_scheduled')) OR (OLD.status='retry_scheduled' AND NEW.status IN ('queued','dead_letter')) OR (OLD.status='failed' AND NEW.status IN ('retry_scheduled','dead_letter')) OR (OLD.status IN ('succeeded','dead_letter') AND NEW.status=OLD.status)) THEN RAISE EXCEPTION 'Invalid webhook lifecycle transition'; END IF;
  IF TG_TABLE_NAME='integration_sync_jobs' AND TG_OP='INSERT' AND NEW.status <> 'queued' THEN RAISE EXCEPTION 'Sync jobs must start queued'; END IF;
  IF TG_TABLE_NAME='integration_sync_jobs' AND TG_OP='UPDATE' AND NOT ((OLD.status='queued' AND NEW.status IN ('running','cancelled')) OR (OLD.status='running' AND NEW.status IN ('succeeded','failed','cancelled')) OR (OLD.status='failed' AND NEW.status='queued') OR (OLD.status IN ('succeeded','cancelled') AND NEW.status=OLD.status)) THEN RAISE EXCEPTION 'Invalid sync lifecycle transition'; END IF;
  IF TG_TABLE_NAME='integration_export_jobs' AND TG_OP='INSERT' AND NEW.status <> 'requested' THEN RAISE EXCEPTION 'Exports must start requested'; END IF;
  IF TG_TABLE_NAME='integration_export_jobs' AND TG_OP='UPDATE' AND NOT ((OLD.status='requested' AND NEW.status IN ('running','failed','cancelled')) OR (OLD.status='running' AND NEW.status IN ('completed','failed','cancelled')) OR (OLD.status IN ('completed','failed','cancelled') AND NEW.status=OLD.status)) THEN RAISE EXCEPTION 'Invalid export lifecycle transition'; END IF;
  IF TG_TABLE_NAME='integration_export_jobs' AND NEW.status='completed' AND NEW.delivery_metadata='{}'::jsonb THEN RAISE EXCEPTION 'Completed exports require verified delivery metadata'; END IF;
  IF TG_TABLE_NAME='integration_retry_queue' AND NEW.attempt >= NEW.maximum_attempts AND NEW.status <> 'exhausted' THEN RAISE EXCEPTION 'Retry exhaustion must be explicit'; END IF;
  IF TG_TABLE_NAME='integration_retry_queue' AND NEW.status='exhausted' AND NEW.next_retry_at IS NOT NULL THEN RAISE EXCEPTION 'Exhausted retries cannot be scheduled'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER integration_webhook_delivery_lifecycle BEFORE INSERT OR UPDATE ON public.integration_webhook_deliveries FOR EACH ROW EXECUTE FUNCTION public.integration_lifecycle_guard();
CREATE TRIGGER integration_sync_lifecycle BEFORE INSERT OR UPDATE ON public.integration_sync_jobs FOR EACH ROW EXECUTE FUNCTION public.integration_lifecycle_guard();
CREATE TRIGGER integration_export_lifecycle BEFORE INSERT OR UPDATE ON public.integration_export_jobs FOR EACH ROW EXECUTE FUNCTION public.integration_lifecycle_guard();
CREATE TRIGGER integration_retry_lifecycle BEFORE INSERT OR UPDATE ON public.integration_retry_queue FOR EACH ROW EXECUTE FUNCTION public.integration_lifecycle_guard();
CREATE OR REPLACE FUNCTION public.integration_retry_to_dlq() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NEW.status='exhausted' THEN INSERT INTO public.integration_dead_letter_queue(company_id,integration_id,source_type,source_id,payload_metadata,last_error,retry_history) VALUES(NEW.company_id,NEW.integration_id,NEW.source_type,NEW.source_id,NEW.backoff_metadata,NEW.reason,jsonb_build_array(jsonb_build_object('attempt',NEW.attempt,'maximum_attempts',NEW.maximum_attempts))) ON CONFLICT(company_id,source_type,source_id) DO NOTHING; END IF; RETURN NEW; END $$;
CREATE TRIGGER integration_retry_dlq AFTER INSERT OR UPDATE ON public.integration_retry_queue FOR EACH ROW EXECUTE FUNCTION public.integration_retry_to_dlq();

DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['integration_registry','integration_connections','integration_health','integration_api_catalogue','integration_api_keys','integration_webhook_endpoints','integration_webhook_deliveries','integration_event_bus','integration_sync_jobs','integration_retry_queue','integration_dead_letter_queue','integration_field_mappings','integration_import_jobs','integration_export_jobs','integration_alerts','integration_audit_logs'] LOOP EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t); END LOOP; END $$;
GRANT INSERT,UPDATE,DELETE ON public.integration_registry,public.integration_connections,public.integration_api_catalogue,public.integration_api_keys,public.integration_webhook_endpoints,public.integration_field_mappings,public.integration_sync_jobs,public.integration_import_jobs,public.integration_export_jobs,public.integration_alerts TO authenticated;

CREATE POLICY integration_registry_read ON public.integration_registry FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_registry_insert ON public.integration_registry FOR INSERT TO authenticated WITH CHECK(public.integration_manager(company_id) AND owner_id=auth.uid() AND status IN ('configured','awaiting_authentication','disabled'));
CREATE POLICY integration_registry_update ON public.integration_registry FOR UPDATE TO authenticated USING(public.integration_owner_or_manager(company_id,owner_id)) WITH CHECK(public.integration_manager(company_id) AND (owner_id=auth.uid() OR public.integration_manager(company_id)) AND status IN ('configured','awaiting_authentication','disabled'));
CREATE POLICY integration_registry_delete ON public.integration_registry FOR DELETE TO authenticated USING(public.integration_owner_or_manager(company_id,owner_id));
CREATE POLICY integration_connections_read ON public.integration_connections FOR SELECT TO authenticated USING(public.integration_manager(company_id));
CREATE POLICY integration_connections_insert ON public.integration_connections FOR INSERT TO authenticated WITH CHECK(public.integration_manager(company_id) AND status IN ('configured','awaiting_authentication','disabled'));
CREATE POLICY integration_connections_update ON public.integration_connections FOR UPDATE TO authenticated USING(public.integration_manager(company_id)) WITH CHECK(public.integration_manager(company_id) AND status IN ('configured','awaiting_authentication','disabled'));
CREATE POLICY integration_connections_delete ON public.integration_connections FOR DELETE TO authenticated USING(public.integration_manager(company_id));
CREATE POLICY integration_health_read ON public.integration_health FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_api_catalogue_read ON public.integration_api_catalogue FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_api_catalogue_insert ON public.integration_api_catalogue FOR INSERT TO authenticated WITH CHECK(public.integration_developer(company_id) AND owner_id=auth.uid());
CREATE POLICY integration_api_catalogue_update ON public.integration_api_catalogue FOR UPDATE TO authenticated USING(public.integration_developer(company_id) AND public.integration_owner_or_manager(company_id,owner_id)) WITH CHECK(public.integration_developer(company_id) AND (owner_id=auth.uid() OR public.integration_manager(company_id)));
CREATE POLICY integration_api_catalogue_delete ON public.integration_api_catalogue FOR DELETE TO authenticated USING(public.integration_developer(company_id) AND public.integration_owner_or_manager(company_id,owner_id));
CREATE POLICY integration_api_keys_owner ON public.integration_api_keys FOR SELECT TO authenticated USING(public.integration_owner_or_manager(company_id,owner_id));
CREATE POLICY integration_api_keys_write ON public.integration_api_keys FOR ALL TO authenticated USING(public.integration_owner_or_manager(company_id,owner_id)) WITH CHECK((public.integration_developer(company_id) OR public.integration_manager(company_id)) AND (owner_id=auth.uid() OR public.integration_manager(company_id)));
CREATE POLICY integration_webhooks_manage ON public.integration_webhook_endpoints FOR ALL TO authenticated USING(public.integration_manager(company_id)) WITH CHECK(public.integration_manager(company_id));
CREATE POLICY integration_deliveries_read ON public.integration_webhook_deliveries FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_events_read ON public.integration_event_bus FOR SELECT TO authenticated USING(public.integration_manager(company_id));
CREATE POLICY integration_sync_read ON public.integration_sync_jobs FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_sync_insert ON public.integration_sync_jobs FOR INSERT TO authenticated WITH CHECK(status='queued' AND public.integration_manager(company_id) AND created_by=auth.uid());
CREATE POLICY integration_retry_read ON public.integration_retry_queue FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_dlq_read ON public.integration_dead_letter_queue FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_mappings_read ON public.integration_field_mappings FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_mappings_write ON public.integration_field_mappings FOR ALL TO authenticated USING(public.integration_manager(company_id)) WITH CHECK(public.integration_manager(company_id));
CREATE POLICY integration_import_read ON public.integration_import_jobs FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_import_insert ON public.integration_import_jobs FOR INSERT TO authenticated WITH CHECK(status='queued' AND public.integration_manager(company_id) AND requested_by=auth.uid());
CREATE POLICY integration_export_read ON public.integration_export_jobs FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_export_insert ON public.integration_export_jobs FOR INSERT TO authenticated WITH CHECK(status='requested' AND public.integration_manager(company_id) AND requested_by=auth.uid());
CREATE POLICY integration_alerts_read ON public.integration_alerts FOR SELECT TO authenticated USING(public.integration_reader(company_id));
CREATE POLICY integration_alerts_ack ON public.integration_alerts FOR UPDATE TO authenticated USING(public.integration_manager(company_id)) WITH CHECK(public.integration_manager(company_id));
CREATE POLICY integration_audit_read ON public.integration_audit_logs FOR SELECT TO authenticated USING(public.integration_manager(company_id));
CREATE OR REPLACE FUNCTION public.integration_append_audit() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE c UUID; i UUID; BEGIN c:=coalesce(NEW.company_id,OLD.company_id); i:=coalesce(NEW.id,OLD.id); INSERT INTO public.integration_audit_logs(company_id,entity_type,entity_id,event_type,actor_id,metadata) VALUES(c,TG_TABLE_NAME,i,lower(TG_OP),auth.uid(),jsonb_build_object('phase','22')); IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['integration_registry','integration_connections','integration_api_catalogue','integration_api_keys','integration_webhook_endpoints','integration_sync_jobs','integration_retry_queue','integration_field_mappings','integration_import_jobs','integration_export_jobs','integration_alerts'] LOOP EXECUTE format('CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.integration_append_audit()',t||'_audit',t); END LOOP; END $$;
REVOKE ALL ON FUNCTION public.integration_reader(UUID),public.integration_manager(UUID),public.integration_developer(UUID),public.integration_owner_or_manager(UUID,UUID) FROM public,anon;
GRANT EXECUTE ON FUNCTION public.integration_reader(UUID),public.integration_manager(UUID),public.integration_developer(UUID),public.integration_owner_or_manager(UUID,UUID) TO authenticated;
