-- Phase 31: governed reliability evidence. Phase 22 remains event/retry/DLQ authority;
-- Brain, ZIP, integration health, BI, Command Centre and platform deployments remain authoritative.
CREATE OR REPLACE FUNCTION public.reliability_can_read(p_company UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT public.has_any_role(p_company,ARRAY['admin','executive','managing_director','operations_manager','viewer']::public.app_role[])
$$;
CREATE OR REPLACE FUNCTION public.reliability_can_write(p_company UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT public.has_any_role(p_company,ARRAY['admin','operations_manager']::public.app_role[])
$$;
CREATE OR REPLACE FUNCTION public.reliability_can_approve(p_company UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT public.has_any_role(p_company,ARRAY['admin']::public.app_role[])
$$;

CREATE TABLE public.reliability_services(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
 name TEXT NOT NULL,service_type TEXT NOT NULL,owner_id UUID REFERENCES auth.users(id),environment TEXT NOT NULL,region TEXT,version TEXT,deployment_id UUID,
 health_endpoint_metadata JSONB NOT NULL DEFAULT '{}',criticality TEXT NOT NULL CHECK(criticality IN('low','moderate','high','critical')),
 support_contact_metadata JSONB NOT NULL DEFAULT '{}',runbook_id UUID,recovery_objectives JSONB NOT NULL DEFAULT '{}',
 monitoring_state TEXT NOT NULL DEFAULT 'not_configured' CHECK(monitoring_state IN('monitored','disabled','not_configured','not_monitored')),
 customer_visibility TEXT NOT NULL DEFAULT 'internal' CHECK(customer_visibility IN('internal','customer_safe','hidden')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(company_id,environment,name)
);
CREATE TABLE public.reliability_service_dependencies(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,service_id UUID NOT NULL REFERENCES public.reliability_services(id) ON DELETE CASCADE,dependency_service_id UUID NOT NULL REFERENCES public.reliability_services(id) ON DELETE CASCADE,critical BOOLEAN NOT NULL DEFAULT true,UNIQUE(service_id,dependency_service_id),CHECK(service_id<>dependency_service_id));
CREATE TABLE public.reliability_health_checks(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,service_id UUID NOT NULL REFERENCES public.reliability_services(id) ON DELETE CASCADE,
 check_type TEXT NOT NULL CHECK(check_type IN('liveness','readiness','dependency','synthetic','auth','database','storage','queue','worker_heartbeat','integration','telemetry','customer_portal')),
 state TEXT NOT NULL CHECK(state IN('healthy','degraded','unavailable','unknown','disabled','not_configured')),
 source_authority TEXT NOT NULL,source_record_id UUID,scope_metadata JSONB NOT NULL DEFAULT '{}',confidence NUMERIC CHECK(confidence BETWEEN 0 AND 1),checked_at TIMESTAMPTZ NOT NULL,
 expected_next_at TIMESTAMPTZ,last_successful_at TIMESTAMPTZ,failure_reason_redacted TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE public.reliability_error_groups(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,fingerprint TEXT NOT NULL,service_id UUID REFERENCES public.reliability_services(id) ON DELETE SET NULL,environment TEXT NOT NULL,version TEXT,severity TEXT NOT NULL CHECK(severity IN('low','moderate','high','critical')),first_seen TIMESTAMPTZ NOT NULL,last_seen TIMESTAMPTZ NOT NULL,occurrence_count BIGINT NOT NULL DEFAULT 1 CHECK(occurrence_count>0),affected_company_count INTEGER NOT NULL DEFAULT 0,affected_user_count INTEGER NOT NULL DEFAULT 0,route_operation TEXT,redacted_stack TEXT,status TEXT NOT NULL DEFAULT 'open' CHECK(status IN('open','acknowledged','investigating','resolved')),owner_id UUID REFERENCES auth.users(id),related_incident_id UUID,resolution TEXT,UNIQUE(company_id,environment,fingerprint));
CREATE TABLE public.reliability_error_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,error_group_id UUID NOT NULL REFERENCES public.reliability_error_groups(id) ON DELETE CASCADE,source_type TEXT NOT NULL,correlation_id TEXT,occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),safe_metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE public.reliability_performance_samples(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,service_id UUID REFERENCES public.reliability_services(id) ON DELETE SET NULL,metric TEXT NOT NULL,environment TEXT NOT NULL,duration_ms NUMERIC CHECK(duration_ms>=0),value NUMERIC,sample_count INTEGER NOT NULL DEFAULT 1,error_count INTEGER NOT NULL DEFAULT 0,timeout_count INTEGER NOT NULL DEFAULT 0,source_authority TEXT NOT NULL,period_start TIMESTAMPTZ NOT NULL,period_end TIMESTAMPTZ NOT NULL,safe_dimensions JSONB NOT NULL DEFAULT '{}',CHECK(period_end>=period_start));
CREATE TABLE public.reliability_slo_definitions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,service_id UUID NOT NULL REFERENCES public.reliability_services(id) ON DELETE CASCADE,name TEXT NOT NULL,indicator TEXT NOT NULL,target NUMERIC NOT NULL CHECK(target>0 AND target<=1),window_seconds BIGINT NOT NULL CHECK(window_seconds>0),measurement_source TEXT NOT NULL,owner_id UUID REFERENCES auth.users(id),severity TEXT NOT NULL,customer_impact TEXT,review_frequency TEXT NOT NULL,contractual BOOLEAN NOT NULL DEFAULT false,active BOOLEAN NOT NULL DEFAULT true,UNIQUE(company_id,name));
CREATE TABLE public.reliability_slo_measurements(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,slo_id UUID NOT NULL REFERENCES public.reliability_slo_definitions(id) ON DELETE CASCADE,period_start TIMESTAMPTZ NOT NULL,period_end TIMESTAMPTZ NOT NULL,good_events BIGINT,total_events BIGINT,allowed_failures NUMERIC,consumed_budget NUMERIC,remaining_budget NUMERIC,burn_rate NUMERIC,status TEXT NOT NULL CHECK(status IN('healthy','at_risk','exhausted','unavailable')),source_record_ids UUID[] NOT NULL DEFAULT '{}',calculated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.reliability_incidents(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,title TEXT NOT NULL,severity TEXT NOT NULL CHECK(severity IN('SEV-1','SEV-2','SEV-3','SEV-4')),status TEXT NOT NULL DEFAULT 'declared' CHECK(status IN('declared','acknowledged','investigating','mitigating','recovering','validation','resolved','closed')),affected_service_ids UUID[] NOT NULL DEFAULT '{}',affected_customer_count INTEGER NOT NULL DEFAULT 0,detection_source TEXT NOT NULL,commander_id UUID REFERENCES auth.users(id),responder_ids UUID[] NOT NULL DEFAULT '{}',customer_communication_state TEXT NOT NULL DEFAULT 'not_sent' CHECK(customer_communication_state IN('not_required','draft','queued','sent','delivered','failed','not_sent')),mitigation TEXT,resolution TEXT,root_cause TEXT,declared_by UUID NOT NULL DEFAULT auth.uid(),declared_at TIMESTAMPTZ NOT NULL DEFAULT now(),resolved_at TIMESTAMPTZ,closed_at TIMESTAMPTZ,closed_by UUID REFERENCES auth.users(id));
ALTER TABLE public.reliability_error_groups ADD CONSTRAINT reliability_error_incident_fk FOREIGN KEY(related_incident_id) REFERENCES public.reliability_incidents(id) ON DELETE SET NULL;
CREATE TABLE public.reliability_incident_timeline(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,incident_id UUID NOT NULL REFERENCES public.reliability_incidents(id) ON DELETE CASCADE,event_type TEXT NOT NULL CHECK(event_type IN('detection','acknowledgement','escalation','investigation','mitigation','recovery','validation','communication','closure','follow_up')),summary TEXT NOT NULL,safe_evidence JSONB NOT NULL DEFAULT '{}',actor_id UUID NOT NULL DEFAULT auth.uid(),occurred_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.reliability_post_incident_reviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,incident_id UUID NOT NULL UNIQUE REFERENCES public.reliability_incidents(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','under_review','approved')),review JSONB NOT NULL DEFAULT '{}',corrective_actions JSONB NOT NULL DEFAULT '[]',approved_by UUID REFERENCES auth.users(id),approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.reliability_releases(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,version TEXT NOT NULL,environment TEXT NOT NULL,commit_sha TEXT NOT NULL,build_evidence JSONB NOT NULL DEFAULT '{}',test_evidence JSONB NOT NULL DEFAULT '{}',migration_set TEXT[] NOT NULL DEFAULT '{}',state TEXT NOT NULL DEFAULT 'draft' CHECK(state IN('draft','ready_for_review','approved','deploying','deployed','validation_pending','validated','failed','rolled_back','cancelled')),rollback_target TEXT,feature_flag_ids UUID[] NOT NULL DEFAULT '{}',known_risks JSONB NOT NULL DEFAULT '[]',release_notes TEXT,created_by UUID NOT NULL DEFAULT auth.uid(),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),validated_at TIMESTAMPTZ,UNIQUE(company_id,environment,version));
CREATE TABLE public.reliability_deployments(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,release_id UUID NOT NULL REFERENCES public.reliability_releases(id) ON DELETE RESTRICT,platform_deployment_id UUID,environment TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('draft','approved','deploying','deployed','validation_pending','validated','failed','rolled_back','cancelled')),evidence JSONB NOT NULL DEFAULT '{}',rollback_plan JSONB NOT NULL DEFAULT '{}',requested_by UUID NOT NULL DEFAULT auth.uid(),started_at TIMESTAMPTZ,completed_at TIMESTAMPTZ);
CREATE TABLE public.reliability_release_approvals(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,release_id UUID REFERENCES public.reliability_releases(id) ON DELETE CASCADE,deployment_id UUID REFERENCES public.reliability_deployments(id) ON DELETE CASCADE,approval_type TEXT NOT NULL CHECK(approval_type IN('staging_deployment','production_deployment','database_migration','feature_activation','emergency_hotfix','rollback')),requester_id UUID NOT NULL,approver_id UUID,decision TEXT NOT NULL DEFAULT 'pending' CHECK(decision IN('pending','approved','rejected','conditions')),risk TEXT NOT NULL,evidence JSONB NOT NULL DEFAULT '{}',conditions TEXT,decided_at TIMESTAMPTZ,CHECK(approver_id IS NULL OR requester_id<>approver_id));
CREATE TABLE public.reliability_feature_flags(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,key TEXT NOT NULL,environment TEXT NOT NULL,company_scope UUID[] NOT NULL DEFAULT '{}',role_scope TEXT[] NOT NULL DEFAULT '{}',rollout_percentage NUMERIC NOT NULL DEFAULT 0 CHECK(rollout_percentage BETWEEN 0 AND 100),rollout_stage TEXT NOT NULL DEFAULT 'internal' CHECK(rollout_stage IN('internal','staging_company','pilot','percentage','full','paused','rolled_back')),starts_at TIMESTAMPTZ,ends_at TIMESTAMPTZ,owner_id UUID NOT NULL,approval_id UUID REFERENCES public.reliability_release_approvals(id),kill_switch BOOLEAN NOT NULL DEFAULT false,reason TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT false,server_enforced BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(company_id,environment,key),CHECK(server_enforced));
CREATE TABLE public.reliability_maintenance_windows(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,planned_start TIMESTAMPTZ NOT NULL,planned_end TIMESTAMPTZ NOT NULL,affected_service_ids UUID[] NOT NULL DEFAULT '{}',expected_impact TEXT NOT NULL,owner_id UUID NOT NULL,approval_id UUID REFERENCES public.reliability_release_approvals(id),customer_visibility BOOLEAN NOT NULL DEFAULT false,internal_notification_id UUID,customer_delivery_state TEXT NOT NULL DEFAULT 'not_sent',status TEXT NOT NULL DEFAULT 'planned' CHECK(status IN('planned','active','completed','extended','cancelled')),completed_at TIMESTAMPTZ,CHECK(planned_end>planned_start));
CREATE TABLE public.reliability_backup_policies(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,asset_type TEXT NOT NULL CHECK(asset_type IN('database','storage','configuration','secrets_metadata','critical_documents','audit_records','migration_history')),environment TEXT NOT NULL,frequency_seconds BIGINT NOT NULL,retention_seconds BIGINT NOT NULL,encryption_expectation TEXT NOT NULL,location_metadata JSONB NOT NULL DEFAULT '{}',owner_id UUID NOT NULL,last_successful_backup_at TIMESTAMPTZ,next_backup_at TIMESTAMPTZ,failure_reason_redacted TEXT,verification_status TEXT NOT NULL DEFAULT 'unavailable' CHECK(verification_status IN('verified','failed','pending','unavailable')),UNIQUE(company_id,asset_type,environment));
CREATE TABLE public.reliability_backup_records(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,policy_id UUID NOT NULL REFERENCES public.reliability_backup_policies(id) ON DELETE RESTRICT,backup_id TEXT NOT NULL,source TEXT NOT NULL,environment TEXT NOT NULL,started_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ,size_bytes BIGINT,status TEXT NOT NULL CHECK(status IN('running','completed','failed','unavailable')),verification TEXT NOT NULL DEFAULT 'unavailable',retention_expires_at TIMESTAMPTZ,provider_reference TEXT,failure_reason_redacted TEXT,evidence JSONB NOT NULL DEFAULT '{}',UNIQUE(company_id,environment,backup_id));
CREATE TABLE public.reliability_restore_tests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,backup_record_id UUID NOT NULL REFERENCES public.reliability_backup_records(id) ON DELETE RESTRICT,target_environment TEXT NOT NULL CHECK(target_environment NOT IN('production','prod')),authorised_by UUID NOT NULL,started_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,data_integrity BOOLEAN,migration_parity BOOLEAN,auth_validation BOOLEAN,storage_validation BOOLEAN,rls_validation BOOLEAN,smoke_tests BOOLEAN,outcome TEXT NOT NULL DEFAULT 'planned' CHECK(outcome IN('planned','running','passed','failed','inconclusive')),evidence JSONB NOT NULL DEFAULT '{}');
CREATE TABLE public.reliability_dr_plans(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,scenario TEXT NOT NULL,environment TEXT NOT NULL,detection TEXT NOT NULL,containment TEXT NOT NULL,recovery TEXT NOT NULL,validation TEXT NOT NULL,communication TEXT NOT NULL,escalation TEXT NOT NULL,owner_id UUID NOT NULL,runbook_id UUID,rto_seconds BIGINT NOT NULL,rpo_seconds BIGINT NOT NULL,last_tested_at TIMESTAMPTZ,actual_recovery_seconds BIGINT,actual_loss_window_seconds BIGINT,next_review_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','reviewed','tested')),UNIQUE(company_id,environment,scenario));
CREATE TABLE public.reliability_capacity_snapshots(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,environment TEXT NOT NULL,metric TEXT NOT NULL,value NUMERIC NOT NULL,unit TEXT NOT NULL,threshold NUMERIC,monthly_growth NUMERIC,forecast_threshold_at TIMESTAMPTZ,confidence TEXT NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),assumptions JSONB NOT NULL DEFAULT '[]',missing_data JSONB NOT NULL DEFAULT '[]',cost_value NUMERIC,cost_classification TEXT CHECK(cost_classification IN('actual','estimated','forecast','unavailable')),source TEXT NOT NULL,recorded_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.reliability_runbooks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,code TEXT NOT NULL,title TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>0),lifecycle TEXT NOT NULL DEFAULT 'draft' CHECK(lifecycle IN('draft','under_review','approved','retired')),content JSONB NOT NULL DEFAULT '{}',owner_id UUID NOT NULL,approved_by UUID REFERENCES auth.users(id),approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(company_id,code,version));
ALTER TABLE public.reliability_services ADD CONSTRAINT reliability_service_runbook_fk FOREIGN KEY(runbook_id) REFERENCES public.reliability_runbooks(id) ON DELETE SET NULL;
ALTER TABLE public.reliability_dr_plans ADD CONSTRAINT reliability_dr_runbook_fk FOREIGN KEY(runbook_id) REFERENCES public.reliability_runbooks(id) ON DELETE SET NULL;
CREATE TABLE public.reliability_readiness_reviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,release_id UUID REFERENCES public.reliability_releases(id) ON DELETE CASCADE,checklist JSONB NOT NULL DEFAULT '{}',known_risks JSONB NOT NULL DEFAULT '[]',result TEXT NOT NULL CHECK(result IN('not_ready','ready_with_conditions','ready')),conditions TEXT,decided_by UUID NOT NULL,decided_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.reliability_status_updates(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,incident_id UUID REFERENCES public.reliability_incidents(id) ON DELETE CASCADE,audience TEXT NOT NULL CHECK(audience IN('internal','customer_safe')),service_state TEXT NOT NULL CHECK(service_state IN('healthy','degraded','unavailable','unknown','not_configured')),affected_capability TEXT NOT NULL,description_redacted TEXT NOT NULL,resolution_state TEXT NOT NULL,source_record_ids UUID[] NOT NULL DEFAULT '{}',published_by UUID NOT NULL DEFAULT auth.uid(),published_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.reliability_audit_logs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,event_type TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id UUID NOT NULL,actor_id UUID NOT NULL DEFAULT auth.uid(),safe_metadata JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT now());

-- Aggregation views reference, rather than duplicate, owning operational systems.
CREATE VIEW public.reliability_phase22_queue_health WITH (security_invoker=true) AS SELECT company_id,'phase22_retry'::TEXT source,count(*) FILTER(WHERE status IN('scheduled','processing')) backlog,count(*) FILTER(WHERE status='exhausted') failures,min(next_retry_at) FILTER(WHERE status='scheduled') oldest_due FROM public.integration_retry_queue GROUP BY company_id;
CREATE VIEW public.reliability_phase22_dlq_health WITH (security_invoker=true) AS SELECT company_id,'phase22_dlq'::TEXT source,count(*) FILTER(WHERE closed_at IS NULL) backlog,min(created_at) FILTER(WHERE closed_at IS NULL) oldest_due FROM public.integration_dead_letter_queue GROUP BY company_id;
CREATE VIEW public.reliability_integration_health_source WITH (security_invoker=true) AS SELECT company_id,integration_id,health_area,status,checked_at,detail_metadata FROM public.integration_health;

CREATE OR REPLACE FUNCTION public.reliability_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Reliability evidence is append-only or immutable'; END $$;
CREATE TRIGGER reliability_health_append_only BEFORE UPDATE OR DELETE ON public.reliability_health_checks FOR EACH ROW EXECUTE FUNCTION public.reliability_immutable();
CREATE TRIGGER reliability_error_events_append_only BEFORE UPDATE OR DELETE ON public.reliability_error_events FOR EACH ROW EXECUTE FUNCTION public.reliability_immutable();
CREATE TRIGGER reliability_incident_timeline_append_only BEFORE UPDATE OR DELETE ON public.reliability_incident_timeline FOR EACH ROW EXECUTE FUNCTION public.reliability_immutable();
CREATE TRIGGER reliability_audit_append_only BEFORE UPDATE OR DELETE ON public.reliability_audit_logs FOR EACH ROW EXECUTE FUNCTION public.reliability_immutable();
CREATE OR REPLACE FUNCTION public.reliability_protect_approved() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.lifecycle='approved' THEN RAISE EXCEPTION 'Approved runbook versions are immutable'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
CREATE TRIGGER reliability_runbook_approved_immutable BEFORE UPDATE OR DELETE ON public.reliability_runbooks FOR EACH ROW EXECUTE FUNCTION public.reliability_protect_approved();
CREATE OR REPLACE FUNCTION public.reliability_protect_validated_release() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.state='validated' THEN RAISE EXCEPTION 'Validated releases are immutable'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
CREATE TRIGGER reliability_validated_release_immutable BEFORE UPDATE OR DELETE ON public.reliability_releases FOR EACH ROW EXECUTE FUNCTION public.reliability_protect_validated_release();
CREATE OR REPLACE FUNCTION public.reliability_human_close_incident(p_incident UUID,p_resolution TEXT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v public.reliability_incidents; BEGIN SELECT * INTO v FROM public.reliability_incidents WHERE id=p_incident FOR UPDATE; IF NOT public.reliability_can_approve(v.company_id) THEN RAISE EXCEPTION 'Authorised human decision required'; END IF; UPDATE public.reliability_incidents SET status='closed',resolution=p_resolution,closed_at=now(),closed_by=auth.uid() WHERE id=p_incident; INSERT INTO public.reliability_incident_timeline(company_id,incident_id,event_type,summary) VALUES(v.company_id,p_incident,'closure','Incident closed by authorised human decision'); END $$;

DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['reliability_services','reliability_service_dependencies','reliability_health_checks','reliability_error_events','reliability_error_groups','reliability_performance_samples','reliability_slo_definitions','reliability_slo_measurements','reliability_incidents','reliability_incident_timeline','reliability_post_incident_reviews','reliability_releases','reliability_deployments','reliability_release_approvals','reliability_feature_flags','reliability_maintenance_windows','reliability_backup_policies','reliability_backup_records','reliability_restore_tests','reliability_dr_plans','reliability_capacity_snapshots','reliability_runbooks','reliability_readiness_reviews','reliability_status_updates','reliability_audit_logs'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon',t); EXECUTE format('GRANT ALL ON public.%I TO service_role',t); EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING(public.reliability_can_read(company_id))',t||'_read',t); END LOOP; END $$;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['reliability_services','reliability_service_dependencies','reliability_health_checks','reliability_error_events','reliability_error_groups','reliability_performance_samples','reliability_slo_definitions','reliability_slo_measurements','reliability_incidents','reliability_incident_timeline','reliability_post_incident_reviews','reliability_releases','reliability_deployments','reliability_feature_flags','reliability_maintenance_windows','reliability_backup_policies','reliability_backup_records','reliability_restore_tests','reliability_dr_plans','reliability_capacity_snapshots','reliability_runbooks','reliability_readiness_reviews','reliability_status_updates'] LOOP EXECUTE format('GRANT INSERT,UPDATE,DELETE ON public.%I TO authenticated',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING(public.reliability_can_write(company_id)) WITH CHECK(public.reliability_can_write(company_id))',t||'_write',t); END LOOP; END $$;
GRANT INSERT ON public.reliability_audit_logs TO authenticated;
CREATE POLICY reliability_audit_insert ON public.reliability_audit_logs FOR INSERT TO authenticated WITH CHECK(public.reliability_can_write(company_id) AND actor_id=auth.uid());
GRANT INSERT,UPDATE ON public.reliability_release_approvals TO authenticated;
CREATE POLICY reliability_approvals_write ON public.reliability_release_approvals FOR ALL TO authenticated USING(public.reliability_can_approve(company_id)) WITH CHECK(public.reliability_can_approve(company_id) AND (approver_id IS NULL OR requester_id<>approver_id));
CREATE POLICY reliability_customer_safe_status_read ON public.reliability_status_updates FOR SELECT TO authenticated USING(audience='customer_safe' AND EXISTS(SELECT 1 FROM public.customer_portal_memberships m WHERE m.company_id=reliability_status_updates.company_id AND m.user_id=auth.uid() AND m.status='active'));
GRANT EXECUTE ON FUNCTION public.reliability_human_close_incident(UUID,TEXT) TO authenticated;
GRANT SELECT ON public.reliability_phase22_queue_health,public.reliability_phase22_dlq_health,public.reliability_integration_health_source TO authenticated;
REVOKE UPDATE,DELETE ON public.reliability_incident_timeline,public.reliability_audit_logs,public.reliability_health_checks,public.reliability_error_events FROM authenticated;

COMMENT ON TABLE public.reliability_health_checks IS 'Evidence-backed checks; missing or stale evidence must aggregate to unknown, never healthy.';
COMMENT ON TABLE public.reliability_backup_records IS 'Actual provider evidence only. No record means provider backup status unavailable.';
COMMENT ON TABLE public.reliability_restore_tests IS 'Disposable or explicitly authorised non-production recovery environments only.';
COMMENT ON VIEW public.reliability_phase22_queue_health IS 'Read-only aggregation over Phase 22 authority; not a new queue.';
