-- Phase 23D runtime controls and truthful observability. Metrics are persisted observations, never fabricated health.
CREATE TABLE public.brain_capability_flags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, capability_code TEXT NOT NULL CHECK(capability_code IN ('brain_event_consumption','brain_scheduled_analysis','brain_manual_analysis','brain_recovery_replay','brain_dry_run','brain_recommendation_generation','brain_derived_event_publication','brain_evaluation','brain_shadow_comparison','brain_external_provider_evaluation','brain_production_external_provider_execution')), environment TEXT CHECK(environment IS NULL OR environment IN ('local','development','test','staging','production')), enabled BOOLEAN NOT NULL DEFAULT false, effective_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, reviewer_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(expires_at IS NULL OR effective_at IS NULL OR expires_at > effective_at), CHECK(capability_code <> 'brain_production_external_provider_execution' OR enabled=false), UNIQUE(company_id,capability_code,environment)
);
CREATE TABLE public.brain_kill_switches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), scope_type TEXT NOT NULL CHECK(scope_type IN ('all_processing','event_consumption','scheduling','recommendation_generation','derived_event_publication','company','consumer','schedule','rule','dataset_contract','capability','experimental_execution')), scope_reference TEXT, active BOOLEAN NOT NULL DEFAULT true, reason TEXT NOT NULL, owner_id UUID NOT NULL REFERENCES auth.users(id), expires_at TIMESTAMPTZ, released_by UUID REFERENCES auth.users(id), released_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(scope_type IN ('all_processing','event_consumption','scheduling','recommendation_generation','derived_event_publication','experimental_execution') OR scope_reference IS NOT NULL)
);
CREATE TABLE public.brain_resource_limits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), limit_type TEXT NOT NULL CHECK(limit_type IN ('maximum_concurrent_jobs','maximum_jobs_per_minute','maximum_events_per_minute','maximum_records_per_dataset_load','maximum_evidence_records','maximum_features_per_run','maximum_rules_per_run','maximum_execution_duration','maximum_retry_attempts','maximum_output_records','maximum_stored_explanation_size','maximum_query_range','maximum_replay_period')), maximum_value BIGINT NOT NULL CHECK(maximum_value > 0), action_on_exceed TEXT NOT NULL CHECK(action_on_exceed IN ('defer','fail','partial_with_warning')), owner_id UUID REFERENCES auth.users(id), reviewer_id UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,environment,limit_type)
);
CREATE TABLE public.brain_service_health (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), component TEXT NOT NULL CHECK(component IN ('event_consumer','scheduler','analysis_executor','dataset_adapter','persistence','derived_event_publisher','query_service','evaluation_service','audit_service')), health_state TEXT NOT NULL CHECK(health_state IN ('healthy','degraded','backlogged','paused','draining','failed','unknown')), checked_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_success_at TIMESTAMPTZ, last_failure_at TIMESTAMPTZ, error_rate_percent NUMERIC(5,2), throughput_per_minute NUMERIC(12,2), lag_seconds INTEGER, backlog_count INTEGER, dependency_health JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(dependency_health)='object'), runtime_version TEXT, deployment_identifier TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(metadata)='object'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,environment,component)
);
CREATE TABLE public.brain_operational_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), component TEXT NOT NULL, metric_code TEXT NOT NULL CHECK(metric_code IN ('jobs_created','jobs_succeeded','jobs_failed','jobs_retried','jobs_dead_lettered','jobs_cancelled','processing_latency_ms','queue_wait_ms','event_lag_seconds','throughput','dataset_load_failures','rule_evaluation_failures','insight_generation_failures','derived_publication_failures','duplicate_rate','checkpoint_lag_seconds','schedule_delay_seconds','worker_availability','recovery_success_rate','dry_run_failure_rate','resource_limit_events','database_reads','database_writes','event_publications','provider_usage_metadata')), metric_value NUMERIC NOT NULL, unit TEXT NOT NULL, window_start TIMESTAMPTZ NOT NULL, window_end TIMESTAMPTZ NOT NULL, runtime_version TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(metadata)='object'), recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(window_start <= window_end)
);
CREATE TABLE public.brain_trace_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), trace_id TEXT NOT NULL, span_id TEXT NOT NULL, parent_span_id TEXT, job_id UUID, brain_run_id UUID, component TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('event_validation','dataset_contract_resolution','dataset_load','feature_calculation','rule_evaluation','evidence_validation','confidence_calculation','ranking','insight_persistence','recommendation_persistence','derived_event_publication','checkpoint_advancement')), status TEXT NOT NULL CHECK(status IN ('started','succeeded','failed','skipped')), started_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ, duration_ms INTEGER, error_classification TEXT, redaction_state TEXT NOT NULL DEFAULT 'redacted' CHECK(redaction_state IN ('redacted','metadata_only')), metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(metadata)='object'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY(company_id,job_id) REFERENCES public.brain_jobs(company_id,id) ON DELETE SET NULL, FOREIGN KEY(company_id,brain_run_id) REFERENCES public.zapp_brain_runs(company_id,id) ON DELETE SET NULL, UNIQUE(company_id,trace_id,span_id)
);
CREATE TABLE public.brain_operational_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), alert_type TEXT NOT NULL CHECK(alert_type IN ('worker_heartbeat_missing','consumer_lag','backlog_threshold','failure_rate','dlq_growth','schedule_missed','schedule_overlap_blocked','dataset_contract_unavailable','dataset_freshness_failure','output_schema_failure','derived_publication_failure','rule_pack_failure','rls_permission_failure','resource_limit_exceeded','kill_switch_activated','deployment_health_regression','privacy_or_security_block','recovery_replay_in_progress')), severity TEXT NOT NULL CHECK(severity IN ('info','low','medium','high','critical')), component TEXT, source_reference TEXT, status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','acknowledged','resolved')), title TEXT NOT NULL, redacted_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(redacted_metadata)='object'), detected_at TIMESTAMPTZ NOT NULL DEFAULT now(), acknowledged_by UUID REFERENCES auth.users(id), acknowledged_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE public.brain_incidents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), severity TEXT NOT NULL CHECK(severity IN ('sev_1','sev_2','sev_3','sev_4','informational')), incident_type TEXT NOT NULL, component TEXT NOT NULL, detected_at TIMESTAMPTZ NOT NULL DEFAULT now(), status TEXT NOT NULL DEFAULT 'detected' CHECK(status IN ('detected','investigating','mitigating','monitoring','resolved','closed')), summary TEXT NOT NULL, impact TEXT, affected_consumers JSONB NOT NULL DEFAULT '[]'::jsonb, affected_schedules JSONB NOT NULL DEFAULT '[]'::jsonb, affected_companies JSONB NOT NULL DEFAULT '[]'::jsonb, affected_runs JSONB NOT NULL DEFAULT '[]'::jsonb, related_alerts JSONB NOT NULL DEFAULT '[]'::jsonb, related_dlq_entries JSONB NOT NULL DEFAULT '[]'::jsonb, owner_id UUID REFERENCES auth.users(id), commander_id UUID REFERENCES auth.users(id), mitigation TEXT, root_cause_status TEXT NOT NULL DEFAULT 'unknown' CHECK(root_cause_status IN ('unknown','investigating','identified','resolved')), resolution TEXT, resolved_at TIMESTAMPTZ, post_incident_review_required BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX brain_metrics_window_idx ON public.brain_operational_metrics(company_id,environment,metric_code,window_end DESC);
CREATE INDEX brain_alerts_open_idx ON public.brain_operational_alerts(company_id,environment,severity,detected_at DESC) WHERE status <> 'resolved';
