CREATE OR REPLACE FUNCTION public.bi_prevent_target_overlap() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$ BEGIN IF NEW.approval_status='approved' AND EXISTS(SELECT 1 FROM public.bi_kpi_targets t WHERE t.id<>NEW.id AND t.company_id=NEW.company_id AND t.kpi_id=NEW.kpi_id AND t.scope_type=NEW.scope_type AND t.scope_id IS NOT DISTINCT FROM NEW.scope_id AND t.approval_status='approved' AND daterange(t.effective_date,COALESCE(t.end_date,'infinity'::date),'[]') && daterange(NEW.effective_date,COALESCE(NEW.end_date,'infinity'::date),'[]')) THEN RAISE EXCEPTION 'Overlapping approved KPI targets are not allowed'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER bi_kpi_target_overlap BEFORE INSERT OR UPDATE ON public.bi_kpi_targets FOR EACH ROW EXECUTE FUNCTION public.bi_prevent_target_overlap();
CREATE OR REPLACE FUNCTION public.bi_signed_report_immutable() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$ BEGIN IF EXISTS(SELECT 1 FROM public.bi_report_commentary c WHERE c.report_id=OLD.id AND c.sign_off_date IS NOT NULL) THEN RAISE EXCEPTION 'Signed reports are immutable'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER bi_saved_report_signed_guard BEFORE UPDATE OR DELETE ON public.bi_saved_reports FOR EACH ROW EXECUTE FUNCTION public.bi_signed_report_immutable();
CREATE OR REPLACE FUNCTION public.bi_validate_report_config() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$ DECLARE d public.bi_report_datasets; BEGIN SELECT * INTO d FROM public.bi_report_datasets WHERE company_id=NEW.company_id AND code=NEW.dataset_code AND active; IF NOT FOUND THEN RAISE EXCEPTION 'Approved reporting dataset is required'; END IF; IF NOT (NEW.columns_config <@ d.allowed_fields) THEN RAISE EXCEPTION 'Report contains unapproved fields'; END IF; IF NOT (NEW.filters_config <@ d.allowed_filters) THEN RAISE EXCEPTION 'Report contains unapproved filters'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER bi_saved_report_config_guard BEFORE INSERT OR UPDATE ON public.bi_saved_reports FOR EACH ROW EXECUTE FUNCTION public.bi_validate_report_config();
GRANT INSERT,UPDATE,DELETE ON public.bi_kpi_definitions,public.bi_kpi_targets,public.bi_saved_reports,public.bi_report_schedules,public.bi_report_commentary TO authenticated;
CREATE POLICY bi_kpis_manage ON public.bi_kpi_definitions FOR ALL TO authenticated USING(public.has_any_role(company_id,ARRAY['admin','executive','managing_director','analyst']::public.app_role[])) WITH CHECK(public.has_any_role(company_id,ARRAY['admin','executive','managing_director','analyst']::public.app_role[]));
CREATE POLICY bi_reports_owner_write ON public.bi_saved_reports FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_any_role(company_id,ARRAY['admin','executive','managing_director']::public.app_role[])) WITH CHECK(owner_id=auth.uid() OR public.has_any_role(company_id,ARRAY['admin','executive','managing_director']::public.app_role[]));
