-- Phase 23B: deterministic derived-intelligence metadata. No domain copies, workflows, or model execution.
ALTER TABLE public.brain_recommendations DROP CONSTRAINT IF EXISTS brain_recommendations_risk_classification_check;
ALTER TABLE public.brain_recommendations ADD CONSTRAINT brain_recommendations_risk_classification_check CHECK(risk_classification IN ('informational','low','medium','moderate','high','critical'));
ALTER TABLE public.brain_recommendations DROP CONSTRAINT IF EXISTS brain_recommendations_review_status_check;
ALTER TABLE public.brain_recommendations ADD CONSTRAINT brain_recommendations_review_status_check CHECK(review_status IN ('proposed','awaiting_review','accepted','accepted_for_domain_review','partially_accepted','rejected','superseded','expired','dismissed'));
CREATE TABLE public.brain_feature_registry (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  feature_code TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, business_domain TEXT NOT NULL,
  dataset_contract_id UUID,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, experimental BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(company_id, feature_code), UNIQUE(company_id, id), FOREIGN KEY(company_id,dataset_contract_id) REFERENCES public.brain_dataset_contracts(company_id,id) ON DELETE RESTRICT
);
CREATE TABLE public.brain_feature_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, feature_id UUID NOT NULL, version INTEGER NOT NULL CHECK(version > 0),
  source_fields JSONB NOT NULL DEFAULT '[]'::jsonb, calculation_type TEXT NOT NULL CHECK(calculation_type IN ('count','sum','average','minimum','maximum','median','percentage','ratio','duration','frequency','recency','trend','moving_average','change_rate','threshold_breach_count','status_transition_count','unique_count','repetition_score','missing_data_rate','data_freshness','variance','standard_deviation','sequence_pattern','category_distribution','time_of_day_pattern','day_of_week_pattern')),
  output_type TEXT NOT NULL, unit TEXT, window_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, minimum_records INTEGER NOT NULL DEFAULT 1 CHECK(minimum_records >= 0), freshness_requirement_minutes INTEGER NOT NULL DEFAULT 0 CHECK(freshness_requirement_minutes >= 0), data_quality_requirement INTEGER NOT NULL DEFAULT 0 CHECK(data_quality_requirement BETWEEN 0 AND 100), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','under_review','approved','active','retired','archived')),
  effective_at TIMESTAMPTZ, retired_at TIMESTAMPTZ, created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(company_id, feature_id, version), UNIQUE(company_id, id), FOREIGN KEY(company_id, feature_id) REFERENCES public.brain_feature_registry(company_id,id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX brain_feature_one_active_version_idx ON public.brain_feature_versions(company_id, feature_id) WHERE status='active';
CREATE TABLE public.brain_feature_calculations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, feature_version_id UUID NOT NULL, source_domain TEXT NOT NULL, source_entity_type TEXT, source_entity_id UUID,
  value_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, unit TEXT, period_start TIMESTAMPTZ, period_end TIMESTAMPTZ, calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(), data_freshness TEXT NOT NULL CHECK(data_freshness IN ('fresh','stale','unavailable')), data_quality INTEGER NOT NULL CHECK(data_quality BETWEEN 0 AND 100), evidence_count INTEGER NOT NULL DEFAULT 0 CHECK(evidence_count >= 0), input_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('calculated','partial','invalid','stale','superseded')), metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(company_id, feature_version_id, input_hash), FOREIGN KEY(company_id, feature_version_id) REFERENCES public.brain_feature_versions(company_id,id) ON DELETE RESTRICT
);
CREATE TABLE public.brain_rule_evaluations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, rule_version_id UUID NOT NULL, brain_run_id UUID, subject_type TEXT NOT NULL, subject_id UUID, features_used JSONB NOT NULL DEFAULT '[]'::jsonb, conditions_evaluated JSONB NOT NULL DEFAULT '[]'::jsonb, condition_results JSONB NOT NULL DEFAULT '[]'::jsonb, evidence JSONB NOT NULL DEFAULT '[]'::jsonb, triggered BOOLEAN NOT NULL, severity TEXT, confidence_inputs JSONB NOT NULL DEFAULT '{}'::jsonb, recommendation_eligible BOOLEAN NOT NULL DEFAULT false, evaluated_at TIMESTAMPTZ NOT NULL DEFAULT now(), duration_ms INTEGER NOT NULL DEFAULT 0 CHECK(duration_ms >= 0), input_hash TEXT NOT NULL, output_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(company_id, rule_version_id, input_hash), FOREIGN KEY(company_id, rule_version_id) REFERENCES public.brain_rule_versions(company_id,id) ON DELETE RESTRICT, FOREIGN KEY(company_id,brain_run_id) REFERENCES public.zapp_brain_runs(company_id,id) ON DELETE RESTRICT
);
CREATE TABLE public.brain_evidence_conflicts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, brain_run_id UUID REFERENCES public.zapp_brain_runs(id) ON DELETE SET NULL, conflicting_fields JSONB NOT NULL DEFAULT '[]'::jsonb, sources JSONB NOT NULL DEFAULT '[]'::jsonb, freshness_difference_minutes INTEGER, reliability_difference INTEGER, preferred_source TEXT, resolution_status TEXT NOT NULL DEFAULT 'open' CHECK(resolution_status IN ('open','reviewed','resolved','dismissed')), created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE public.brain_confidence_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, policy_code TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), minimum_persist INTEGER NOT NULL CHECK(minimum_persist BETWEEN 0 AND 100), minimum_display INTEGER NOT NULL CHECK(minimum_display BETWEEN 0 AND 100), minimum_recommendation INTEGER NOT NULL CHECK(minimum_recommendation BETWEEN 0 AND 100), policy_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','under_review','approved','active','retired','archived')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(policy_code,version)
);
CREATE TABLE public.brain_insight_correlations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, related_insight_ids JSONB NOT NULL CHECK(jsonb_array_length(related_insight_ids)>=2), related_source_records JSONB NOT NULL DEFAULT '[]'::jsonb, correlation_type TEXT NOT NULL CHECK(correlation_type LIKE 'non_causal%'), shared_window JSONB NOT NULL DEFAULT '{}'::jsonb, shared_entity TEXT, evidence_strength INTEGER NOT NULL CHECK(evidence_strength BETWEEN 0 AND 100), confidence_score INTEGER NOT NULL CHECK(confidence_score BETWEEN 0 AND 100), explanation TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE public.brain_explanations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, brain_insight_id UUID, brain_run_id UUID, structured_explanation JSONB NOT NULL CHECK(jsonb_typeof(structured_explanation)='object'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(brain_insight_id IS NOT NULL OR brain_run_id IS NOT NULL), FOREIGN KEY(company_id,brain_insight_id) REFERENCES public.zapp_brain_insights(company_id,id) ON DELETE CASCADE, FOREIGN KEY(company_id,brain_run_id) REFERENCES public.zapp_brain_runs(company_id,id) ON DELETE CASCADE
);
CREATE TABLE public.brain_query_definitions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, query_code TEXT NOT NULL, intent TEXT NOT NULL CHECK(intent IN ('critical_insights','explain_insight','insight_evidence','low_confidence','stale_insights','repeated_patterns','recommendations_awaiting_review','rule_performance','calibration_proposals','compare_periods','domain_summary','analysis_failures')), filters_schema JSONB NOT NULL DEFAULT '{}'::jsonb, owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,query_code), UNIQUE(company_id,id));
CREATE TABLE public.brain_query_executions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, query_definition_id UUID NOT NULL, executed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL, filters_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, result_count INTEGER NOT NULL DEFAULT 0 CHECK(result_count>=0), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY(company_id,query_definition_id) REFERENCES public.brain_query_definitions(company_id,id) ON DELETE CASCADE);
CREATE TABLE public.brain_prompt_registry (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, prompt_code TEXT NOT NULL, name TEXT NOT NULL, purpose TEXT NOT NULL, domain TEXT NOT NULL, intended_request_type TEXT NOT NULL, safety_classification TEXT NOT NULL, owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, experimental BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(prompt_code));
CREATE TABLE public.brain_prompt_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), prompt_id UUID NOT NULL REFERENCES public.brain_prompt_registry(id) ON DELETE CASCADE, version INTEGER NOT NULL CHECK(version>0), allowed_dataset_contracts JSONB NOT NULL DEFAULT '[]'::jsonb, restricted_fields JSONB NOT NULL DEFAULT '[]'::jsonb, expected_input_schema JSONB NOT NULL DEFAULT '{}'::jsonb, expected_output_schema JSONB NOT NULL DEFAULT '{}'::jsonb, status TEXT NOT NULL DEFAULT 'proposed' CHECK(status IN ('proposed','under_review','approved_for_evaluation','evaluation_only','restricted','retired')), reviewer_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(prompt_id,version));
CREATE TABLE public.brain_model_registry (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, provider_type TEXT NOT NULL, model_code TEXT NOT NULL, model_name TEXT NOT NULL, model_version TEXT, capabilities JSONB NOT NULL DEFAULT '[]'::jsonb, approved_domains JSONB NOT NULL DEFAULT '[]'::jsonb, restricted_domains JSONB NOT NULL DEFAULT '[]'::jsonb, data_classification_limit TEXT NOT NULL CHECK(data_classification_limit IN ('public','internal','confidential','restricted','highly_restricted')), status TEXT NOT NULL CHECK(status IN ('proposed','under_review','approved_for_evaluation','evaluation_only','restricted','retired')), context_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, cost_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, evaluation_status TEXT NOT NULL DEFAULT 'not_evaluated', experimental BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(status <> 'production_approved'), UNIQUE(model_code, model_version));
CREATE TABLE public.brain_intelligence_quality (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, quality_type TEXT NOT NULL CHECK(quality_type IN ('dataset_freshness','missing_required_fields','evidence_coverage','conflicting_evidence','failed_feature_calculations','invalid_rule_evaluations','low_confidence_rate','duplicate_insight_rate','stale_insight_rate','reviewer_rejection_rate','calibration_backlog','analysis_run_failure_rate','consumer_backlog','dataset_contract_disabled')), severity TEXT NOT NULL CHECK(severity IN ('info','low','medium','high','critical')), status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','acknowledged','resolved')), measurement_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, observed_at TIMESTAMPTZ NOT NULL DEFAULT now(), resolved_at TIMESTAMPTZ);
CREATE TABLE public.brain_outcome_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, recommendation_id UUID REFERENCES public.brain_recommendations(id) ON DELETE SET NULL, outcome_type TEXT NOT NULL CHECK(outcome_type IN ('domain_review_created','follow_up_completed','issue_resolved','no_change','negative_outcome','outcome_unknown')), outcome_date TIMESTAMPTZ, reviewer_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, evidence JSONB NOT NULL DEFAULT '[]'::jsonb, attribution_confidence INTEGER CHECK(attribution_confidence BETWEEN 0 AND 100), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
