-- Phase 24: Zapp Intelligence Platform. ZIP stores governed intelligence records only; ZappOS remains the system of record.
CREATE TABLE public.zip_prompt_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  prompt_code TEXT NOT NULL, name TEXT NOT NULL, purpose TEXT NOT NULL, target_module TEXT NOT NULL CHECK(target_module IN ('fleet','warehouse','crm','hr','compliance','procurement','executive','business_intelligence')),
  owner_id UUID NOT NULL REFERENCES auth.users(id), data_classification_limit TEXT NOT NULL CHECK(data_classification_limit IN ('public','internal','confidential','restricted')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(company_id,prompt_code), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_prompt_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, prompt_template_id UUID NOT NULL, version INTEGER NOT NULL CHECK(version > 0),
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','under_review','approved','retired')), body_template TEXT NOT NULL, owner_id UUID NOT NULL REFERENCES auth.users(id), reviewer_id UUID REFERENCES auth.users(id), approved_by UUID REFERENCES auth.users(id),
  allowed_dataset_contract_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(allowed_dataset_contract_ids)='array'), redaction_rules JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(redaction_rules)='array'), expected_input_schema JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(expected_input_schema)='object'), expected_output_schema JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(expected_output_schema)='object'),
  safety_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(safety_metadata)='object'), review_note TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,prompt_template_id) REFERENCES public.zip_prompt_templates(company_id,id) ON DELETE CASCADE, UNIQUE(company_id,prompt_template_id,version), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_provider_configurations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  provider_code TEXT NOT NULL CHECK(provider_code IN ('openai','anthropic','google','ollama','zapp_model')), environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')),
  model_reference TEXT NOT NULL, secret_reference TEXT CHECK(secret_reference IS NULL OR secret_reference ~ '^(vault|kms|secret-manager|keychain|external):'), enabled BOOLEAN NOT NULL DEFAULT false, production_enabled BOOLEAN NOT NULL DEFAULT false,
  maximum_data_classification TEXT NOT NULL DEFAULT 'internal' CHECK(maximum_data_classification IN ('public','internal','confidential','restricted')), allowed_prompt_version_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(allowed_prompt_version_ids)='array'), owner_id UUID NOT NULL REFERENCES auth.users(id), reviewer_id UUID REFERENCES auth.users(id), approved_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK(NOT production_enabled), CHECK(environment <> 'production' OR NOT enabled), UNIQUE(company_id,provider_code,environment), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_knowledge_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL CHECK(source_type IN ('sop','policy','maintenance_manual','vehicle_manual','compliance_document','contract','customer_documentation','internal_procedure','technical_documentation')),
  source_record_id UUID, title TEXT NOT NULL, owning_module TEXT NOT NULL CHECK(owning_module IN ('fleet','warehouse','crm','hr','compliance','procurement','executive','business_intelligence','shared')),
  data_classification TEXT NOT NULL CHECK(data_classification IN ('public','internal','confidential','restricted','highly_restricted')), allowed_roles JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(allowed_roles)='array'), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','under_review','approved','retired','blocked')), owner_id UUID NOT NULL REFERENCES auth.users(id), reviewer_id UUID REFERENCES auth.users(id), approved_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(company_id,id)
);
CREATE TABLE public.zip_knowledge_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, source_id UUID NOT NULL, document_code TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','under_review','approved','retired','blocked')), current_version_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,source_id) REFERENCES public.zip_knowledge_sources(company_id,id) ON DELETE CASCADE, UNIQUE(company_id,document_code), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_knowledge_document_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, document_id UUID NOT NULL, version INTEGER NOT NULL CHECK(version > 0), source_content_hash TEXT NOT NULL, extracted_content_redacted TEXT NOT NULL, data_classification TEXT NOT NULL CHECK(data_classification IN ('public','internal','confidential','restricted','highly_restricted')), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','indexed','approved','blocked','retired')), owner_id UUID NOT NULL REFERENCES auth.users(id), reviewer_id UUID REFERENCES auth.users(id), approved_by UUID REFERENCES auth.users(id), indexed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,document_id) REFERENCES public.zip_knowledge_documents(company_id,id) ON DELETE CASCADE, UNIQUE(company_id,document_id,version), UNIQUE(company_id,id)
);
ALTER TABLE public.zip_knowledge_documents ADD CONSTRAINT zip_knowledge_documents_current_version_fk FOREIGN KEY(company_id,current_version_id) REFERENCES public.zip_knowledge_document_versions(company_id,id) ON DELETE SET NULL;
CREATE TABLE public.zip_knowledge_chunks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, document_version_id UUID NOT NULL, chunk_index INTEGER NOT NULL CHECK(chunk_index >= 0), content_redacted TEXT NOT NULL, content_hash TEXT NOT NULL, token_count INTEGER CHECK(token_count IS NULL OR token_count >= 0), embedding_status TEXT NOT NULL DEFAULT 'not_indexed' CHECK(embedding_status IN ('not_indexed','queued','indexed','failed','blocked')), embedding_provider TEXT, embedding_model TEXT, embedding_reference TEXT, lexical_terms JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(lexical_terms)='array'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,document_version_id) REFERENCES public.zip_knowledge_document_versions(company_id,id) ON DELETE CASCADE, UNIQUE(company_id,document_version_id,chunk_index), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_retrieval_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, requested_by UUID NOT NULL REFERENCES auth.users(id), source_module TEXT NOT NULL CHECK(source_module IN ('fleet','warehouse','crm','hr','compliance','procurement','executive','business_intelligence')), query_redacted TEXT NOT NULL, query_hash TEXT NOT NULL, requested_classification TEXT NOT NULL CHECK(requested_classification IN ('public','internal','confidential','restricted')), status TEXT NOT NULL DEFAULT 'requested' CHECK(status IN ('requested','completed','blocked','failed')), blocked_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ, UNIQUE(company_id,id)
);
CREATE TABLE public.zip_retrieval_citations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, retrieval_request_id UUID NOT NULL, knowledge_chunk_id UUID NOT NULL, rank INTEGER NOT NULL CHECK(rank > 0), score NUMERIC(5,2) CHECK(score IS NULL OR score BETWEEN 0 AND 100), excerpt_redacted TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,retrieval_request_id) REFERENCES public.zip_retrieval_requests(company_id,id) ON DELETE CASCADE, FOREIGN KEY(company_id,knowledge_chunk_id) REFERENCES public.zip_knowledge_chunks(company_id,id) ON DELETE RESTRICT, UNIQUE(company_id,retrieval_request_id,knowledge_chunk_id), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_intelligence_api_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, request_token TEXT NOT NULL, source_module TEXT NOT NULL CHECK(source_module IN ('fleet','warehouse','crm','hr','compliance','procurement','executive','business_intelligence')), request_kind TEXT NOT NULL CHECK(request_kind IN ('ask_brain','chat','executive_brief','department_copilot','knowledge_retrieval','record_explanation')), requested_by UUID NOT NULL REFERENCES auth.users(id), prompt_version_id UUID, retrieval_request_id UUID, subject_reference JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(subject_reference)='object'), question_redacted TEXT NOT NULL, question_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'requested' CHECK(status IN ('requested','processing','available','unavailable','blocked','failed')), blocked_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ,
  FOREIGN KEY(company_id,prompt_version_id) REFERENCES public.zip_prompt_versions(company_id,id) ON DELETE SET NULL, FOREIGN KEY(company_id,retrieval_request_id) REFERENCES public.zip_retrieval_requests(company_id,id) ON DELETE SET NULL, UNIQUE(company_id,request_token), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_intelligence_api_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, request_id UUID NOT NULL, state TEXT NOT NULL CHECK(state IN ('available','unavailable','blocked','pending')), insight_redacted TEXT, explanation_redacted TEXT, recommendation_redacted TEXT, confidence NUMERIC(5,2) CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 100), priority TEXT NOT NULL CHECK(priority IN ('low','medium','high','critical','unavailable')), unknowns JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(unknowns)='array'), related_records JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(related_records)='array'), advisory_only BOOLEAN NOT NULL DEFAULT true CHECK(advisory_only), generated_by TEXT NOT NULL CHECK(generated_by IN ('deterministic_retrieval','governed_provider','human_authored')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,request_id) REFERENCES public.zip_intelligence_api_requests(company_id,id) ON DELETE CASCADE, UNIQUE(company_id,request_id), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_intelligence_response_citations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, response_id UUID NOT NULL, retrieval_citation_id UUID, knowledge_chunk_id UUID, claim_reference TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,response_id) REFERENCES public.zip_intelligence_api_responses(company_id,id) ON DELETE CASCADE, FOREIGN KEY(company_id,retrieval_citation_id) REFERENCES public.zip_retrieval_citations(company_id,id) ON DELETE SET NULL, FOREIGN KEY(company_id,knowledge_chunk_id) REFERENCES public.zip_knowledge_chunks(company_id,id) ON DELETE RESTRICT, UNIQUE(company_id,response_id,knowledge_chunk_id), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_provider_gateway_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, api_request_id UUID, provider_configuration_id UUID, prompt_version_id UUID, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), status TEXT NOT NULL DEFAULT 'blocked' CHECK(status IN ('requested','validated','blocked','completed','failed')), input_hash TEXT NOT NULL, redaction_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(redaction_metadata)='object'), classification_checked TEXT NOT NULL CHECK(classification_checked IN ('public','internal','confidential','restricted')), safety_check_status TEXT NOT NULL DEFAULT 'pending' CHECK(safety_check_status IN ('pending','passed','blocked','failed')), blocked_reason TEXT, requested_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ,
  FOREIGN KEY(company_id,api_request_id) REFERENCES public.zip_intelligence_api_requests(company_id,id) ON DELETE SET NULL, FOREIGN KEY(company_id,provider_configuration_id) REFERENCES public.zip_provider_configurations(company_id,id) ON DELETE SET NULL, FOREIGN KEY(company_id,prompt_version_id) REFERENCES public.zip_prompt_versions(company_id,id) ON DELETE SET NULL, UNIQUE(company_id,id)
);
CREATE TABLE public.zip_provider_gateway_calls (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, gateway_request_id UUID NOT NULL, provider_code TEXT NOT NULL CHECK(provider_code IN ('openai','anthropic','google','ollama','zapp_model')), model_reference TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('not_called','completed','failed','blocked')), input_token_count INTEGER CHECK(input_token_count IS NULL OR input_token_count >= 0), output_token_count INTEGER CHECK(output_token_count IS NULL OR output_token_count >= 0), cost_amount NUMERIC(12,4), duration_ms INTEGER CHECK(duration_ms IS NULL OR duration_ms >= 0), response_hash TEXT, failure_classification TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,gateway_request_id) REFERENCES public.zip_provider_gateway_requests(company_id,id) ON DELETE CASCADE, UNIQUE(company_id,gateway_request_id), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_chat_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES auth.users(id), source_module TEXT NOT NULL CHECK(source_module IN ('fleet','warehouse','crm','hr','compliance','procurement','executive','business_intelligence')), title_redacted TEXT, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','closed','archived')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, session_id UUID NOT NULL, sender_type TEXT NOT NULL CHECK(sender_type IN ('user','zip','system')), content_redacted TEXT NOT NULL, content_hash TEXT NOT NULL, api_request_id UUID, response_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,session_id) REFERENCES public.zip_chat_sessions(company_id,id) ON DELETE CASCADE, FOREIGN KEY(company_id,api_request_id) REFERENCES public.zip_intelligence_api_requests(company_id,id) ON DELETE SET NULL, FOREIGN KEY(company_id,response_id) REFERENCES public.zip_intelligence_api_responses(company_id,id) ON DELETE SET NULL, UNIQUE(company_id,id)
);
CREATE TABLE public.zip_memory_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, memory_scope TEXT NOT NULL CHECK(memory_scope IN ('session','user','team','company')), session_id UUID, user_id UUID REFERENCES auth.users(id), team_reference TEXT, memory_key TEXT NOT NULL, value_redacted TEXT NOT NULL, value_hash TEXT NOT NULL, expires_at TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','expired','revoked')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,memory_scope,session_id,user_id,team_reference,memory_key), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_copilot_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, module_code TEXT NOT NULL CHECK(module_code IN ('fleet','warehouse','crm','hr','compliance','procurement','executive','business_intelligence')), name TEXT NOT NULL, purpose TEXT NOT NULL, allowed_prompt_version_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(allowed_prompt_version_ids)='array'), allowed_dataset_contract_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(allowed_dataset_contract_ids)='array'), enabled BOOLEAN NOT NULL DEFAULT false, owner_id UUID NOT NULL REFERENCES auth.users(id), reviewer_id UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,module_code), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_agent_registry (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, agent_code TEXT NOT NULL, module_code TEXT NOT NULL CHECK(module_code IN ('fleet','warehouse','crm','hr','compliance','procurement','executive','business_intelligence')), purpose TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','under_review','approved','retired')), autonomous_actions_allowed BOOLEAN NOT NULL DEFAULT false CHECK(NOT autonomous_actions_allowed), owner_id UUID NOT NULL REFERENCES auth.users(id), reviewer_id UUID REFERENCES auth.users(id), approved_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,agent_code), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_agent_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, agent_id UUID NOT NULL, api_request_id UUID, status TEXT NOT NULL DEFAULT 'requested' CHECK(status IN ('requested','analysed','blocked','failed','completed')), recommendation_redacted TEXT, requires_human_review BOOLEAN NOT NULL DEFAULT true CHECK(requires_human_review), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ,
  FOREIGN KEY(company_id,agent_id) REFERENCES public.zip_agent_registry(company_id,id) ON DELETE CASCADE, FOREIGN KEY(company_id,api_request_id) REFERENCES public.zip_intelligence_api_requests(company_id,id) ON DELETE SET NULL, UNIQUE(company_id,id)
);
CREATE TABLE public.zip_executive_briefings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, briefing_date DATE NOT NULL, period_start TIMESTAMPTZ NOT NULL, period_end TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','available','unavailable','reviewed','retired')), summary_redacted TEXT, risks JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(risks)='array'), recommended_reviews JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(recommended_reviews)='array'), confidence NUMERIC(5,2) CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 100), generated_by TEXT NOT NULL CHECK(generated_by IN ('deterministic_retrieval','governed_provider','human_authored')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), reviewed_by UUID REFERENCES auth.users(id), reviewed_at TIMESTAMPTZ, UNIQUE(company_id,briefing_date), UNIQUE(company_id,id), CHECK(period_start <= period_end)
);
CREATE TABLE public.zip_safety_assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, api_request_id UUID, gateway_request_id UUID, assessment_type TEXT NOT NULL CHECK(assessment_type IN ('hallucination','citation_enforcement','confidence_threshold','restricted_field','pii','prompt_injection','jailbreak','output_schema','human_escalation')), status TEXT NOT NULL CHECK(status IN ('passed','blocked','warning','failed','unavailable')), findings_redacted JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(findings_redacted)='array'), action TEXT NOT NULL CHECK(action IN ('allow','block','require_human_review','mark_unavailable')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,api_request_id) REFERENCES public.zip_intelligence_api_requests(company_id,id) ON DELETE SET NULL, FOREIGN KEY(company_id,gateway_request_id) REFERENCES public.zip_provider_gateway_requests(company_id,id) ON DELETE SET NULL, UNIQUE(company_id,id)
);
CREATE TABLE public.zip_ai_evaluations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, response_id UUID, evaluation_type TEXT NOT NULL CHECK(evaluation_type IN ('answer_quality','groundedness','citation_quality','hallucination_rate','latency','token_usage','cost','user_feedback')), score NUMERIC(7,2), availability TEXT NOT NULL CHECK(availability IN ('available','unavailable','insufficient_data')), measurement_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(measurement_metadata)='object'), evaluated_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY(company_id,response_id) REFERENCES public.zip_intelligence_api_responses(company_id,id) ON DELETE SET NULL, UNIQUE(company_id,id)
);
CREATE TABLE public.zip_user_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, response_id UUID NOT NULL, user_id UUID NOT NULL REFERENCES auth.users(id), feedback TEXT NOT NULL CHECK(feedback IN ('helpful','not_helpful','incorrect','unsafe','needs_review')), note_redacted TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY(company_id,response_id) REFERENCES public.zip_intelligence_api_responses(company_id,id) ON DELETE CASCADE, UNIQUE(company_id,response_id,user_id)
);
CREATE TABLE public.zip_model_deployment_metadata (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, model_registry_id UUID, purpose TEXT NOT NULL, fine_tuning_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(fine_tuning_metadata)='object'), evaluation_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(evaluation_metadata)='object'), deployment_status TEXT NOT NULL DEFAULT 'metadata_only' CHECK(deployment_status IN ('metadata_only','evaluation_only','retired')), rollback_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(rollback_metadata)='object'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,id)
);
CREATE TABLE public.zip_audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, entity_type TEXT NOT NULL, entity_id UUID NOT NULL, event_type TEXT NOT NULL, actor_id UUID REFERENCES auth.users(id), metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(metadata)='object'), created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX zip_knowledge_chunk_lookup_idx ON public.zip_knowledge_chunks(company_id,document_version_id,embedding_status);
CREATE INDEX zip_api_request_status_idx ON public.zip_intelligence_api_requests(company_id,source_module,status,created_at DESC);
CREATE INDEX zip_safety_assessment_idx ON public.zip_safety_assessments(company_id,status,created_at DESC);
