-- Phase 38: Customer Visibility 3.0. Phase 26 remains the portal authority;
-- Phase 34 remains the location-policy authority; Fleet Timeline, Connect,
-- documents/POD, support and notifications remain authoritative.

CREATE TABLE public.customer_delivery_preferences(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,
 eta_change_threshold_minutes integer NOT NULL DEFAULT 15 CHECK(eta_change_threshold_minutes BETWEEN 1 AND 240),delay_threshold_minutes integer NOT NULL DEFAULT 15 CHECK(delay_threshold_minutes BETWEEN 1 AND 1440),arriving_soon_minutes integer NOT NULL DEFAULT 30 CHECK(arriving_soon_minutes IN(15,30,60)),distance_threshold_km numeric CHECK(distance_threshold_km IS NULL OR distance_threshold_km>0),channels jsonb NOT NULL DEFAULT '["portal"]',quiet_hours jsonb NOT NULL DEFAULT '{}',language text NOT NULL DEFAULT 'en',timezone text NOT NULL DEFAULT 'UTC',shipment_types jsonb NOT NULL DEFAULT '[]',priority_only boolean NOT NULL DEFAULT false,appointment_reminders boolean NOT NULL DEFAULT true,delivery_reminders boolean NOT NULL DEFAULT true,pod_available boolean NOT NULL DEFAULT true,support_updates boolean NOT NULL DEFAULT true,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE NULLS NOT DISTINCT(company_id,customer_id,user_id,branch_id)
);
CREATE TABLE public.customer_eta_change_events(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,previous_eta timestamptz,current_eta timestamptz,change_minutes integer,confidence text NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),internal_reason_code text,safe_reason text,meaningful boolean NOT NULL DEFAULT false,communication_message_id uuid REFERENCES public.communication_messages(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.customer_delivery_windows(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,eta timestamptz,window_start timestamptz,window_end timestamptz,confidence text NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),next_milestone text,safe_status text,general_area text,source_references jsonb NOT NULL DEFAULT '[]',calculated_at timestamptz NOT NULL DEFAULT now(),CHECK(window_end IS NULL OR window_start IS NULL OR window_end>=window_start)
);
CREATE TABLE public.customer_milestone_preferences(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,milestone text NOT NULL,enabled boolean NOT NULL DEFAULT true,channels jsonb NOT NULL DEFAULT '["portal"]',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,customer_id,user_id,milestone)
);
CREATE TABLE public.customer_safe_exception_mappings(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,internal_code text NOT NULL,customer_type text NOT NULL CHECK(customer_type IN('delay','customer_closed','access_problem','delivery_rejected','partial_delivery','damaged_goods','missing_goods','wrong_address','appointment_issue','document_missing','temperature_issue','vehicle_breakdown','other')),safe_message text NOT NULL,safe_action text,temperature_authorised boolean NOT NULL DEFAULT false,approved_by uuid REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,internal_code)
);
CREATE TABLE public.customer_tracking_link_records(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,created_by uuid NOT NULL REFERENCES auth.users(id),token_hash text NOT NULL,visibility_mode text NOT NULL CHECK(visibility_mode IN('hidden','milestone_only','approximate_area','delayed_location','delivery_window_only')),expires_at timestamptz NOT NULL,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(token_hash),CHECK(expires_at>created_at)
);
CREATE TABLE public.customer_delivery_feedback(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES auth.users(id),rating integer NOT NULL CHECK(rating BETWEEN 1 AND 5),delivery_comment text CHECK(length(delivery_comment)<=2000),portal_comment text CHECK(length(portal_comment)<=2000),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(job_id,user_id)
);
CREATE TABLE public.customer_delivery_issue_requests(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES auth.users(id),issue_type text NOT NULL CHECK(issue_type IN('missing_goods','damaged_goods','partial_delivery','wrong_goods','temperature_concern','pod_dispute','delivery_timing_dispute','appointment_confirmation','appointment_change','site_instruction','contact_update','delay_acknowledgement','delivery_exception')),summary text NOT NULL CHECK(length(summary) BETWEEN 1 AND 2000),status text NOT NULL DEFAULT 'submitted' CHECK(status IN('submitted','under_review','waiting_customer','resolved','closed')),support_request_id uuid REFERENCES public.customer_service_requests(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.customer_experience_metrics(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,period_start date NOT NULL,period_end date NOT NULL,metric_name text NOT NULL,value numeric,unit text,methodology text,data_coverage numeric CHECK(data_coverage IS NULL OR data_coverage BETWEEN 0 AND 100),confidence text CHECK(confidence IS NULL OR confidence IN('high','medium','low','unavailable')),estimated boolean NOT NULL DEFAULT false,dimensions jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),CHECK(period_end>=period_start),UNIQUE(company_id,customer_id,branch_id,period_start,period_end,metric_name)
);
CREATE TABLE public.customer_audit_logs(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,branch_id uuid REFERENCES public.customer_portal_branches(id) ON DELETE SET NULL,event_type text NOT NULL CHECK(event_type IN('shipment_viewed','tracking_viewed','pod_viewed','document_download_requested','appointment_confirmed','appointment_change_requested','notification_preference_changed','tracking_visibility_changed','support_request_created','delivery_issue_created','tracking_link_created','tracking_link_revoked','feedback_submitted','customer_zip_query','customer_user_changed')),entity_type text,entity_id uuid,privacy_metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.portal38_internal(c uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','customer_care','dispatcher','fleet_controller','operations_manager']::public.app_role[]) $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['customer_delivery_preferences','customer_eta_change_events','customer_delivery_windows','customer_milestone_preferences','customer_safe_exception_mappings','customer_tracking_link_records','customer_delivery_feedback','customer_delivery_issue_requests','customer_experience_metrics','customer_audit_logs'] LOOP
 EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t); EXECUTE format('GRANT ALL ON public.%I TO service_role',t); EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t);
END LOOP; END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['customer_delivery_windows','customer_tracking_link_records','customer_delivery_issue_requests','customer_experience_metrics'] LOOP
 EXECUTE format('CREATE POLICY %I_customer_read ON public.%I FOR SELECT TO authenticated USING(public.portal_branch_visible(company_id,customer_id,branch_id))',t,t);
 EXECUTE format('CREATE POLICY %I_internal_read ON public.%I FOR SELECT TO authenticated USING(public.portal38_internal(company_id))',t,t);
END LOOP; END $$;
CREATE POLICY customer_delivery_preferences_customer_read ON public.customer_delivery_preferences FOR SELECT TO authenticated USING(user_id=auth.uid() AND public.portal_branch_visible(company_id,customer_id,branch_id));
CREATE POLICY customer_milestone_preferences_customer_read ON public.customer_milestone_preferences FOR SELECT TO authenticated USING(user_id=auth.uid() AND public.portal_has_access(company_id,customer_id));
CREATE POLICY customer_delivery_feedback_customer_read ON public.customer_delivery_feedback FOR SELECT TO authenticated USING(user_id=auth.uid() AND public.portal_branch_visible(company_id,customer_id,branch_id));
CREATE POLICY customer_audit_logs_customer_read ON public.customer_audit_logs FOR SELECT TO authenticated USING(user_id=auth.uid() AND public.portal_branch_visible(company_id,customer_id,branch_id));
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['customer_delivery_preferences','customer_eta_change_events','customer_milestone_preferences','customer_delivery_feedback','customer_audit_logs'] LOOP
 EXECUTE format('CREATE POLICY %I_internal_read ON public.%I FOR SELECT TO authenticated USING(public.portal38_internal(company_id))',t,t);
END LOOP; END $$;
CREATE POLICY customer_safe_exception_mappings_customer_read ON public.customer_safe_exception_mappings FOR SELECT TO authenticated USING(public.portal_has_access(company_id,(public.portal_membership()).customer_id));
CREATE POLICY customer_safe_exception_mappings_internal_read ON public.customer_safe_exception_mappings FOR SELECT TO authenticated USING(public.portal38_internal(company_id));

CREATE OR REPLACE FUNCTION public.portal38_audit(m public.customer_portal_memberships,e text,et text,eid uuid,branch uuid DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.customer_audit_logs(company_id,customer_id,user_id,branch_id,event_type,entity_type,entity_id) VALUES(m.company_id,m.customer_id,auth.uid(),branch,e,et,eid); END $$;

CREATE OR REPLACE FUNCTION public.portal38_dashboard() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$ DECLARE m public.customer_portal_memberships; BEGIN m:=public.portal_membership();IF m.id IS NULL THEN RAISE EXCEPTION 'No active portal membership';END IF; RETURN jsonb_build_object(
'active_shipments',(SELECT count(*) FROM public.jobs j WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id) AND j.status IN('assigned','accepted','in_progress','arrived')),
'deliveries_today',(SELECT count(*) FROM public.jobs j WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id) AND j.scheduled_at::date=current_date),
'delayed_shipments',(SELECT count(DISTINCT e.job_id) FROM public.customer_eta_change_events e WHERE e.company_id=m.company_id AND e.customer_id=m.customer_id AND e.meaningful AND e.created_at>now()-interval '24 hours' AND public.portal_branch_visible(e.company_id,e.customer_id,e.branch_id)),
'arriving_soon',(SELECT count(DISTINCT w.job_id) FROM public.customer_delivery_windows w WHERE w.company_id=m.company_id AND w.customer_id=m.customer_id AND w.window_start BETWEEN now() AND now()+interval '60 minutes' AND public.portal_branch_visible(w.company_id,w.customer_id,w.branch_id)),
'awaiting_customer_action',(SELECT count(*) FROM public.customer_delivery_issue_requests r WHERE r.company_id=m.company_id AND r.customer_id=m.customer_id AND r.status='waiting_customer' AND public.portal_branch_visible(r.company_id,r.customer_id,r.branch_id)),
'pods_available',(SELECT count(*) FROM public.job_proofs p JOIN public.jobs j ON j.id=p.job_id WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND p.customer_visible AND p.finalized_at IS NOT NULL AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id)),
'open_support_requests',(SELECT count(*) FROM public.customer_service_requests r WHERE r.company_id=m.company_id AND r.customer_id=m.customer_id AND r.status NOT IN('resolved','closed')),
'new_messages',(SELECT count(*) FROM public.customer_portal_messages msg JOIN public.customer_portal_conversations c ON c.id=msg.conversation_id WHERE c.company_id=m.company_id AND c.customer_id=m.customer_id AND msg.sender_type<>'customer' AND msg.read_at IS NULL AND public.portal_branch_visible(c.company_id,c.customer_id,c.branch_id)),
'upcoming_appointments',(SELECT count(*) FROM public.yard_appointments a WHERE a.company_id=m.company_id AND a.payload->>'customer_id'=m.customer_id::text AND coalesce((a.payload->>'scheduled_at')::timestamptz,now()-interval '1 day')>=now()),
'recent_deliveries',(SELECT coalesce(jsonb_agg(x),'[]') FROM(SELECT j.id,j.reference,j.status,j.completed_at,j.updated_at FROM public.jobs j WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND j.status='completed' AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id) ORDER BY j.completed_at DESC NULLS LAST LIMIT 5)x)
);END $$;

CREATE OR REPLACE FUNCTION public.portal38_shipments(_limit integer DEFAULT 25,_offset integer DEFAULT 0) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$ DECLARE m public.customer_portal_memberships;BEGIN m:=public.portal_membership();IF m.id IS NULL THEN RAISE EXCEPTION 'No active portal membership';END IF;RETURN(SELECT coalesce(jsonb_agg(x),'[]') FROM(SELECT j.id,j.reference,j.status,j.pickup_location,j.dropoff_location,j.scheduled_at,j.completed_at,j.updated_at,j.customer_branch_id,w.window_start,w.window_end,w.confidence,w.next_milestone,w.safe_status FROM public.jobs j LEFT JOIN LATERAL(SELECT * FROM public.customer_delivery_windows d WHERE d.job_id=j.id ORDER BY d.calculated_at DESC LIMIT 1)w ON true WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id) ORDER BY j.updated_at DESC LIMIT least(greatest(_limit,1),100) OFFSET greatest(_offset,0))x);END $$;

CREATE OR REPLACE FUNCTION public.portal38_preferences() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE m public.customer_portal_memberships; p public.customer_delivery_preferences;
BEGIN
 m:=public.portal_membership(); IF m.id IS NULL THEN RAISE EXCEPTION 'No active portal membership'; END IF;
 SELECT * INTO p FROM public.customer_delivery_preferences d WHERE d.company_id=m.company_id AND d.customer_id=m.customer_id AND d.user_id=auth.uid() ORDER BY d.updated_at DESC LIMIT 1;
 RETURN jsonb_build_object('eta_change_threshold_minutes',coalesce(p.eta_change_threshold_minutes,15),'delay_threshold_minutes',coalesce(p.delay_threshold_minutes,15),'arriving_soon_minutes',coalesce(p.arriving_soon_minutes,30),'channels',coalesce(p.channels,'["portal"]'::jsonb),'quiet_hours',coalesce(p.quiet_hours,'{}'::jsonb),'language',coalesce(p.language,'en'),'timezone',coalesce(p.timezone,'UTC'),'appointment_reminders',coalesce(p.appointment_reminders,true),'delivery_reminders',coalesce(p.delivery_reminders,true),'pod_available',coalesce(p.pod_available,true),'support_updates',coalesce(p.support_updates,true),'provider_truth','Only configured channels execute; delivery is never inferred from preference.');
END $$;

CREATE OR REPLACE FUNCTION public.portal38_analytics() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE m public.customer_portal_memberships;
BEGIN
 m:=public.portal_membership(); IF m.id IS NULL THEN RAISE EXCEPTION 'No active portal membership'; END IF;
 RETURN jsonb_build_object(
  'shipments',(SELECT count(*) FROM public.jobs j WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id)),
  'completed',(SELECT count(*) FROM public.jobs j WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND j.status='completed' AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id)),
  'delay_frequency',(SELECT count(DISTINCT e.job_id) FROM public.customer_eta_change_events e WHERE e.company_id=m.company_id AND e.customer_id=m.customer_id AND e.meaningful AND public.portal_branch_visible(e.company_id,e.customer_id,e.branch_id)),
  'pod_available',(SELECT count(*) FROM public.job_proofs p JOIN public.jobs j ON j.id=p.job_id WHERE j.company_id=m.company_id AND j.customer_id=m.customer_id AND p.customer_visible AND p.finalized_at IS NOT NULL AND public.portal_branch_visible(j.company_id,j.customer_id,j.customer_branch_id)),
  'support_open',(SELECT count(*) FROM public.customer_service_requests r WHERE r.company_id=m.company_id AND r.customer_id=m.customer_id AND r.status NOT IN('resolved','closed')),
  'governed_metrics',(SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]') FROM(SELECT metric_name,value,unit,methodology,data_coverage,confidence,estimated,period_start,period_end FROM public.customer_experience_metrics e WHERE e.company_id=m.company_id AND e.customer_id=m.customer_id AND public.portal_branch_visible(e.company_id,e.customer_id,e.branch_id) ORDER BY period_end DESC LIMIT 100)x),
  'sla','Only shown in governed_metrics when a real SLA authority supplies it.','sustainability','Estimated metrics include methodology, coverage and confidence; none are certified reporting.');
END $$;

CREATE OR REPLACE FUNCTION public.portal38_shipment(_job_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE m public.customer_portal_memberships;j public.jobs;v record;loc record;win record;yard jsonb;result jsonb;effective_visibility text:='hidden';BEGIN m:=public.portal_membership();IF m.id IS NULL THEN RAISE EXCEPTION 'No active portal membership';END IF;SELECT * INTO j FROM public.jobs WHERE id=_job_id AND company_id=m.company_id AND customer_id=m.customer_id AND public.portal_branch_visible(company_id,customer_id,customer_branch_id);IF j.id IS NULL THEN RETURN NULL;END IF;
 SELECT * INTO v FROM public.tracking_customer_visibility_policies p WHERE p.company_id=j.company_id AND p.customer_id=j.customer_id AND (p.shipment_id=j.id OR (p.shipment_id IS NULL AND p.vehicle_id=j.vehicle_id)) AND p.effective_at<=now() AND(p.expires_at IS NULL OR p.expires_at>now()) ORDER BY p.effective_at DESC LIMIT 1;
 effective_visibility:=CASE WHEN v.visibility_mode IS NULL THEN 'hidden' WHEN v.cargo_sensitivity='hidden_until_delivery' AND j.status<>'completed' THEN 'hidden' WHEN v.cargo_sensitivity IN('milestone_only','restricted_contacts') THEN 'milestone_only' WHEN v.cargo_sensitivity IN('high_value','sensitive') AND v.visibility_mode IN('exact_location','delayed_location') THEN 'approximate_area' ELSE v.visibility_mode END;
 SELECT * INTO loc FROM public.vehicle_latest_locations l WHERE l.company_id=j.company_id AND l.vehicle_id=j.vehicle_id ORDER BY l.device_timestamp DESC LIMIT 1;SELECT * INTO win FROM public.customer_delivery_windows w WHERE w.job_id=j.id ORDER BY w.calculated_at DESC LIMIT 1;SELECT g.payload INTO yard FROM public.yard_gate_visits g WHERE g.company_id=j.company_id AND g.payload->>'job_id'=j.id::text ORDER BY g.created_at DESC LIMIT 1;
 SELECT jsonb_build_object('job',jsonb_build_object('id',j.id,'reference',j.reference,'status',j.status,'pickup_location',j.pickup_location,'dropoff_location',j.dropoff_location,'scheduled_at',j.scheduled_at,'completed_at',j.completed_at,'updated_at',j.updated_at),'eta',CASE WHEN win.id IS NULL THEN NULL ELSE jsonb_build_object('current_eta',win.eta,'window_start',win.window_start,'window_end',win.window_end,'confidence',win.confidence,'last_updated',win.calculated_at,'next_milestone',win.next_milestone,'status',win.safe_status,'general_area',win.general_area) END,
 'tracking',jsonb_build_object('visibility_mode',effective_visibility,'latitude',CASE WHEN effective_visibility='exact_location' OR(effective_visibility='delayed_location' AND loc.device_timestamp<=now()-make_interval(mins=>v.delay_minutes)) THEN loc.latitude WHEN effective_visibility='approximate_area' THEN round(loc.latitude::numeric,2) END,'longitude',CASE WHEN effective_visibility='exact_location' OR(effective_visibility='delayed_location' AND loc.device_timestamp<=now()-make_interval(mins=>v.delay_minutes)) THEN loc.longitude WHEN effective_visibility='approximate_area' THEN round(loc.longitude::numeric,2) END,'general_area',CASE WHEN effective_visibility IN('approximate_area','milestone_only','delayed_location') THEN coalesce(win.general_area,'Approximate operational area') END,'last_update',CASE WHEN effective_visibility<>'hidden' THEN loc.device_timestamp END,'freshness',CASE WHEN effective_visibility='hidden' THEN 'withheld' WHEN loc.device_timestamp>=now()-interval '60 seconds' THEN 'live' WHEN loc.device_timestamp>=now()-interval '5 minutes' THEN 'recent' WHEN loc.device_timestamp>=now()-interval '30 minutes' THEN 'stale' ELSE 'offline' END),
 'eta_history',(SELECT coalesce(jsonb_agg(jsonb_build_object('eta',e.current_eta,'change_minutes',e.change_minutes,'confidence',e.confidence,'safe_reason',e.safe_reason,'timestamp',e.created_at,'notification_state',CASE WHEN msg.delivery_state IN('delivered','read') THEN msg.delivery_state WHEN msg.id IS NULL THEN 'not_prepared' ELSE msg.delivery_state END) ORDER BY e.created_at),'[]') FROM public.customer_eta_change_events e LEFT JOIN public.communication_messages msg ON msg.id=e.communication_message_id WHERE e.job_id=j.id),
 'timeline',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',f.id,'milestone',f.event_type,'timestamp',f.occurred_at,'freshness',f.freshness,'source',f.source,'note',f.operational_label,'evidence',f.evidence) ORDER BY f.occurred_at),'[]') FROM public.fleet_timeline_events f WHERE f.company_id=j.company_id AND f.vehicle_id=j.vehicle_id AND f.event_type IN('eta_updated','customer_arrival','pod_accepted','delay_detected','approaching_gate','gate_in','admitted','loading_started','loading_completed','gate_out','departed_site')),
 'yard',CASE WHEN yard IS NULL THEN NULL ELSE jsonb_build_object('milestone',yard->>'state','completion_percentage',CASE WHEN yard->>'expected_units' IS NOT NULL THEN least(100,round(100*coalesce((yard->>'loaded_units')::numeric,0)/greatest((yard->>'expected_units')::numeric,1))) END,'estimated_completion',yard->>'estimated_completion','estimated_departure',yard->>'estimated_departure','safe_delay_reason',yard->>'safe_delay_reason') END,
 'proof',(SELECT jsonb_build_object('id',p.id,'status','available','recipient',p.recipient_name,'timestamp',p.completed_at,'signature_available',(p.signature_url IS NOT NULL),'photo_available',(p.photo_url IS NOT NULL),'source','job_proofs','integrity',jsonb_build_object('finalized_at',p.finalized_at)) FROM public.job_proofs p WHERE p.job_id=j.id AND p.customer_visible AND p.finalized_at IS NOT NULL ORDER BY p.finalized_at DESC LIMIT 1),
 'documents',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',d.id,'name',d.name,'type',d.document_type,'version',1,'source','documents')),'[]') FROM public.customer_document_links l JOIN public.documents d ON d.id=l.document_id WHERE l.company_id=j.company_id AND l.customer_id=j.customer_id AND l.job_id=j.id AND d.visibility='customer_visible'),
 'exceptions',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',r.id,'type',r.issue_type,'summary',r.summary,'status',r.status,'created_at',r.created_at)),'[]') FROM public.customer_delivery_issue_requests r WHERE r.job_id=j.id),
 'actions',jsonb_build_array(), 'temperature',NULL,'read_only',true) INTO result;PERFORM public.portal38_audit(m,'shipment_viewed','job',j.id,j.customer_branch_id);RETURN result;END $$;

CREATE OR REPLACE FUNCTION public.portal38_action(_action text,_payload jsonb DEFAULT '{}') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE m public.customer_portal_memberships;j public.jobs;new_id uuid;token text;support_id uuid;BEGIN m:=public.portal_membership();IF m.id IS NULL THEN RAISE EXCEPTION 'No active portal membership';END IF;
 IF _payload?'job_id' THEN SELECT * INTO j FROM public.jobs WHERE id=(_payload->>'job_id')::uuid AND company_id=m.company_id AND customer_id=m.customer_id AND public.portal_branch_visible(company_id,customer_id,customer_branch_id);IF j.id IS NULL THEN RAISE EXCEPTION 'Shipment action denied';END IF;END IF;
 CASE _action
 WHEN 'update_preferences' THEN INSERT INTO public.customer_delivery_preferences(company_id,customer_id,user_id,branch_id,eta_change_threshold_minutes,delay_threshold_minutes,arriving_soon_minutes,channels,quiet_hours,language,timezone,appointment_reminders,delivery_reminders,pod_available,support_updates) VALUES(m.company_id,m.customer_id,auth.uid(),nullif(_payload->>'branch_id','')::uuid,coalesce((_payload->>'eta_change_threshold_minutes')::int,15),coalesce((_payload->>'delay_threshold_minutes')::int,15),coalesce((_payload->>'arriving_soon_minutes')::int,30),coalesce(_payload->'channels','["portal"]'),coalesce(_payload->'quiet_hours','{}'),coalesce(nullif(_payload->>'language',''),'en'),coalesce(nullif(_payload->>'timezone',''),'UTC'),coalesce((_payload->>'appointment_reminders')::boolean,true),coalesce((_payload->>'delivery_reminders')::boolean,true),coalesce((_payload->>'pod_available')::boolean,true),coalesce((_payload->>'support_updates')::boolean,true)) ON CONFLICT(company_id,customer_id,user_id,branch_id) DO UPDATE SET eta_change_threshold_minutes=excluded.eta_change_threshold_minutes,delay_threshold_minutes=excluded.delay_threshold_minutes,arriving_soon_minutes=excluded.arriving_soon_minutes,channels=excluded.channels,quiet_hours=excluded.quiet_hours,language=excluded.language,timezone=excluded.timezone,appointment_reminders=excluded.appointment_reminders,delivery_reminders=excluded.delivery_reminders,pod_available=excluded.pod_available,support_updates=excluded.support_updates,updated_at=now() RETURNING id INTO new_id;PERFORM public.portal38_audit(m,'notification_preference_changed','customer_delivery_preferences',new_id,nullif(_payload->>'branch_id','')::uuid);
 WHEN 'feedback' THEN IF j.status<>'completed' THEN RAISE EXCEPTION 'Feedback requires completed delivery';END IF;INSERT INTO public.customer_delivery_feedback(company_id,customer_id,branch_id,job_id,user_id,rating,delivery_comment,portal_comment) VALUES(m.company_id,m.customer_id,j.customer_branch_id,j.id,auth.uid(),(_payload->>'rating')::int,left(_payload->>'delivery_comment',2000),left(_payload->>'portal_comment',2000)) RETURNING id INTO new_id;PERFORM public.portal38_audit(m,'feedback_submitted','customer_delivery_feedback',new_id,j.customer_branch_id);
 WHEN 'delivery_issue','appointment_confirm','appointment_change','site_instruction','delay_acknowledgement' THEN INSERT INTO public.customer_service_requests(company_id,customer_id,created_by_user_id,job_id,subject,category,message,priority) VALUES(m.company_id,m.customer_id,auth.uid(),j.id,left(coalesce(_payload->>'subject','Delivery request'),200),'support',left(coalesce(_payload->>'summary','Customer action submitted'),5000),'medium') RETURNING id INTO support_id;INSERT INTO public.customer_delivery_issue_requests(company_id,customer_id,branch_id,job_id,user_id,issue_type,summary,support_request_id) VALUES(m.company_id,m.customer_id,j.customer_branch_id,j.id,auth.uid(),CASE _action WHEN 'appointment_confirm' THEN 'appointment_confirmation' WHEN 'appointment_change' THEN 'appointment_change' WHEN 'site_instruction' THEN 'site_instruction' WHEN 'delay_acknowledgement' THEN 'delay_acknowledgement' ELSE coalesce(_payload->>'issue_type','delivery_exception') END,left(coalesce(_payload->>'summary','Customer action submitted'),2000),support_id) RETURNING id INTO new_id;PERFORM public.portal38_audit(m,CASE WHEN _action='appointment_confirm' THEN 'appointment_confirmed' WHEN _action='appointment_change' THEN 'appointment_change_requested' WHEN _action='delivery_issue' THEN 'delivery_issue_created' ELSE 'support_request_created' END,'customer_delivery_issue_requests',new_id,j.customer_branch_id);
 WHEN 'create_tracking_link' THEN IF coalesce(_payload->>'visibility_mode','') NOT IN('milestone_only','approximate_area','delayed_location','delivery_window_only') OR nullif(_payload->>'expires_at','')::timestamptz<=now() THEN RAISE EXCEPTION 'Tracking link policy denied';END IF;token:=encode(extensions.gen_random_bytes(32),'hex');INSERT INTO public.customer_tracking_link_records(company_id,customer_id,branch_id,job_id,created_by,token_hash,visibility_mode,expires_at) VALUES(m.company_id,m.customer_id,j.customer_branch_id,j.id,auth.uid(),encode(extensions.digest(token,'sha256'),'hex'),_payload->>'visibility_mode',(_payload->>'expires_at')::timestamptz) RETURNING id INTO new_id;PERFORM public.portal38_audit(m,'tracking_link_created','customer_tracking_link_records',new_id,j.customer_branch_id);
 WHEN 'revoke_tracking_link' THEN UPDATE public.customer_tracking_link_records SET revoked_at=coalesce(revoked_at,now()) WHERE id=(_payload->>'id')::uuid AND company_id=m.company_id AND customer_id=m.customer_id AND created_by=auth.uid() RETURNING id INTO new_id;PERFORM public.portal38_audit(m,'tracking_link_revoked','customer_tracking_link_records',new_id,NULL);
 ELSE RAISE EXCEPTION 'Unsupported Phase 38 customer action';END CASE;IF new_id IS NULL THEN RAISE EXCEPTION 'Customer action was not permitted';END IF;RETURN jsonb_build_object('id',new_id,'status','accepted','direct_schedule_mutation',false,'public_tracking_url',NULL);END $$;

CREATE OR REPLACE FUNCTION public.portal38_zip_answer(_question text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE m public.customer_portal_memberships;q text:=lower(trim(_question));j public.jobs;answer text;refs jsonb:='[]';outcome text:='answered';BEGIN m:=public.portal_membership();IF m.id IS NULL THEN RAISE EXCEPTION 'No active portal membership';END IF;IF q~'(other customer|driver.private|brain|dispatch scor|security detail|margin|pricing rule|employee)' THEN answer:='I cannot provide other-customer, driver-private, internal intelligence, security, employee, margin, or restricted pricing information.';outcome:='refused';ELSE SELECT * INTO j FROM public.jobs WHERE company_id=m.company_id AND customer_id=m.customer_id AND public.portal_branch_visible(company_id,customer_id,customer_branch_id) ORDER BY updated_at DESC LIMIT 1;IF j.id IS NULL THEN answer:='No authorised shipment record is available.';outcome:='unavailable';ELSIF q~'(where|when|arrive|delay|changed|timeline|delivery)' THEN answer:=format('Shipment %s is %s. Open the cited shipment for its policy-controlled location, ETA window, freshness and timeline.',j.reference,replace(j.status::text,'_',' '));refs:=jsonb_build_array(jsonb_build_object('type','shipment','id',j.id,'freshness',j.updated_at));ELSIF q~'pod' THEN answer:=CASE WHEN EXISTS(SELECT 1 FROM public.job_proofs p WHERE p.job_id=j.id AND p.customer_visible AND p.finalized_at IS NOT NULL) THEN 'An authorised POD is available for the cited shipment.' ELSE 'POD is not yet available for the cited shipment.' END;refs:=jsonb_build_array(jsonb_build_object('type','shipment','id',j.id,'freshness',j.updated_at));ELSIF q~'(need to do|missing document)' THEN answer:='Open the Action Centre for authorised appointment, document, exception and support actions.';refs:=jsonb_build_array(jsonb_build_object('type','shipment','id',j.id,'freshness',j.updated_at));ELSIF q~'support request' THEN answer:=format('You have %s open support requests.',(SELECT count(*) FROM public.customer_service_requests r WHERE r.company_id=m.company_id AND r.customer_id=m.customer_id AND r.status NOT IN('resolved','closed')));refs:=jsonb_build_array(jsonb_build_object('type','support','customer_id',m.customer_id,'freshness',now()));ELSE answer:='No authorised cited answer matched this question.';outcome:='unavailable';END IF;END IF;INSERT INTO public.customer_portal_zip_queries(company_id,customer_id,user_id,question_redacted,response_redacted,citations,outcome) VALUES(m.company_id,m.customer_id,auth.uid(),left(_question,500),answer,refs,outcome);PERFORM public.portal38_audit(m,'customer_zip_query','customer_portal_zip_queries',NULL,NULL);RETURN jsonb_build_object('answer',answer,'citations',refs,'outcome',outcome,'freshness',now(),'unknowns',CASE WHEN outcome='unavailable' THEN jsonb_build_array('authorised evidence unavailable') ELSE '[]'::jsonb END,'read_only',true,'deterministic',true);END $$;

CREATE OR REPLACE FUNCTION public.portal38_customer_care(_job_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$ DECLARE j public.jobs;BEGIN SELECT * INTO j FROM public.jobs WHERE id=_job_id;IF j.id IS NULL OR NOT public.portal38_internal(j.company_id) THEN RAISE EXCEPTION 'Customer Care handoff denied';END IF;RETURN jsonb_build_object('customer_id',j.customer_id,'shipment',jsonb_build_object('id',j.id,'reference',j.reference,'status',j.status),'eta',(SELECT to_jsonb(w) - 'company_id' - 'customer_id' FROM public.customer_delivery_windows w WHERE w.job_id=j.id ORDER BY calculated_at DESC LIMIT 1),'last_tracking_update',(SELECT device_timestamp FROM public.vehicle_latest_locations l WHERE l.company_id=j.company_id AND l.vehicle_id=j.vehicle_id),'delay_reason',(SELECT safe_reason FROM public.customer_eta_change_events e WHERE e.job_id=j.id ORDER BY created_at DESC LIMIT 1),'pod_state',CASE WHEN EXISTS(SELECT 1 FROM public.job_proofs p WHERE p.job_id=j.id AND p.finalized_at IS NOT NULL) THEN 'available' ELSE 'pending' END,'support_history',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',r.id,'status',r.status,'subject',r.subject)),'[]') FROM public.customer_service_requests r WHERE r.job_id=j.id),'approved_customer_summary','Customer-safe shipment context assembled from authorised sources.','brain_recommendations',NULL);END $$;

CREATE OR REPLACE FUNCTION public.portal38_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Phase 38 evidence is append-only';END $$;
DO $$ DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['customer_eta_change_events','customer_delivery_windows','customer_delivery_feedback','customer_experience_metrics','customer_audit_logs'] LOOP EXECUTE format('CREATE TRIGGER %I_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.portal38_append_only()',t,t);END LOOP;END $$;
CREATE INDEX customer38_eta_job_idx ON public.customer_eta_change_events(job_id,created_at DESC);CREATE INDEX customer38_window_job_idx ON public.customer_delivery_windows(job_id,calculated_at DESC);CREATE INDEX customer38_issue_job_idx ON public.customer_delivery_issue_requests(job_id,created_at DESC);CREATE INDEX customer38_audit_customer_idx ON public.customer_audit_logs(customer_id,created_at DESC);
REVOKE ALL ON FUNCTION public.portal38_internal(uuid),public.portal38_audit(public.customer_portal_memberships,text,text,uuid,uuid),public.portal38_dashboard(),public.portal38_shipments(integer,integer),public.portal38_preferences(),public.portal38_analytics(),public.portal38_shipment(uuid),public.portal38_action(text,jsonb),public.portal38_zip_answer(text),public.portal38_customer_care(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.portal38_dashboard(),public.portal38_shipments(integer,integer),public.portal38_preferences(),public.portal38_analytics(),public.portal38_shipment(uuid),public.portal38_action(text,jsonb),public.portal38_zip_answer(text),public.portal38_customer_care(uuid) TO authenticated;
