-- Phase 39: Predictive Fleet Intelligence & Early Warning.
-- Derived warnings are advisory, confidence-scored, explainable and human-reviewed.

CREATE OR REPLACE FUNCTION public.predictive39_read(c uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','fleet_manager','fleet_controller','maintenance_manager','maintenance_coordinator','dispatcher','operations_manager','executive','managing_director','analyst','brain_analyst','brain_reviewer','viewer']::public.app_role[])
$$;
CREATE OR REPLACE FUNCTION public.predictive39_review(c uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','fleet_manager','fleet_controller','maintenance_manager','maintenance_coordinator','operations_manager','brain_reviewer']::public.app_role[])
$$;
REVOKE ALL ON FUNCTION public.predictive39_read(uuid),public.predictive39_review(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.predictive39_read(uuid),public.predictive39_review(uuid) TO authenticated;

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY[
 'predictive_vehicle_assessments','predictive_subsystem_assessments','predictive_maintenance_forecasts','predictive_recurrence_findings','predictive_fuel_anomalies','predictive_tyre_assessments','predictive_battery_assessments','predictive_engine_assessments','predictive_driver_risk_trends','predictive_route_risk_assessments','predictive_downtime_estimates','predictive_service_demand_forecasts','predictive_parts_demand_forecasts','predictive_device_health','predictive_eta_calibration_proposals'
] LOOP EXECUTE format($ddl$
 CREATE TABLE public.%I(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  branch_id uuid,subject_type text NOT NULL,subject_id text NOT NULL,vehicle_id uuid REFERENCES public.vehicles(id) ON DELETE SET NULL,driver_id uuid REFERENCES public.drivers(id) ON DELETE SET NULL,
  risk_level text NOT NULL DEFAULT 'unknown' CHECK(risk_level IN('normal','watch','elevated','high','critical','unknown','insufficient_data')),
  confidence numeric NOT NULL DEFAULT 0 CHECK(confidence BETWEEN 0 AND 100),evidence_coverage numeric NOT NULL DEFAULT 0 CHECK(evidence_coverage BETWEEN 0 AND 100),freshness text NOT NULL DEFAULT 'unavailable' CHECK(freshness IN('live','fresh','aging','stale','unavailable')),
  review_horizon_start timestamptz,review_horizon_end timestamptz,model_version text NOT NULL DEFAULT 'phase39-deterministic-v1',governance_status text NOT NULL DEFAULT 'under_review' CHECK(governance_status IN('draft','under_review','approved','active','retired')),
  factors jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(factors)='array'),missing_evidence jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(missing_evidence)='array'),evidence jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(evidence)='array'),result jsonb NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(result)='object'),
  advisory_only boolean NOT NULL DEFAULT true CHECK(advisory_only),requires_human_review boolean NOT NULL DEFAULT true CHECK(requires_human_review),calculated_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now()
 )$ddl$,t);
 EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);
 EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t);
 EXECUTE format('GRANT ALL ON public.%I TO service_role',t);
 EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING(public.predictive39_read(company_id))',t||'_read',t);
 EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK(public.brain_is_service(company_id))',t||'_brain_insert',t);
 EXECUTE format('CREATE INDEX %I ON public.%I(company_id,risk_level,calculated_at DESC)',t||'_queue',t);
 END LOOP; END $$;

CREATE TABLE public.predictive_outcomes(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,assessment_table text NOT NULL,assessment_id uuid NOT NULL,predicted_at timestamptz NOT NULL,horizon_start timestamptz,horizon_end timestamptz,actual_outcome text,outcome_at timestamptz,error_value numeric,confidence numeric NOT NULL CHECK(confidence BETWEEN 0 AND 100),model_version text NOT NULL,evidence_coverage numeric NOT NULL CHECK(evidence_coverage BETWEEN 0 AND 100),metrics jsonb NOT NULL DEFAULT '{}',recorded_at timestamptz NOT NULL DEFAULT now(),recorded_by uuid REFERENCES auth.users(id)
);
CREATE TABLE public.predictive_feedback(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,assessment_table text NOT NULL,assessment_id uuid NOT NULL,feedback text NOT NULL CHECK(feedback IN('useful_warning','correct_but_late','correct_but_too_early','false_positive','insufficient_evidence','dismissed','action_taken')),review_state text NOT NULL DEFAULT 'new' CHECK(review_state IN('new','under_review','accepted','deferred','rejected','inspection_requested','work_order_requested','closed','outcome_recorded')),note text,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.predictive_audit_logs(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,event_type text NOT NULL CHECK(event_type IN('predictive_assessment_created','risk_escalated','risk_reduced','recurrence_detected','fuel_anomaly_raised','maintenance_forecast_created','inspection_requested','recommendation_accepted','recommendation_rejected','false_positive_recorded','outcome_recorded','calibration_proposal_created','forecast_reviewed','risk_cleared')),entity_type text NOT NULL,entity_id uuid,actor_id uuid REFERENCES auth.users(id),evidence jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now()
);

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['predictive_outcomes','predictive_feedback','predictive_audit_logs'] LOOP
 EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t);EXECUTE format('GRANT ALL ON public.%I TO service_role',t);EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING(public.predictive39_read(company_id))',t||'_read',t);
 END LOOP; END $$;

CREATE OR REPLACE FUNCTION public.predictive39_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$BEGIN RAISE EXCEPTION 'Phase 39 predictive evidence is append-only';END$$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY[
 'predictive_vehicle_assessments','predictive_subsystem_assessments','predictive_maintenance_forecasts','predictive_recurrence_findings','predictive_fuel_anomalies','predictive_tyre_assessments','predictive_battery_assessments','predictive_engine_assessments','predictive_driver_risk_trends','predictive_route_risk_assessments','predictive_downtime_estimates','predictive_service_demand_forecasts','predictive_parts_demand_forecasts','predictive_device_health','predictive_eta_calibration_proposals','predictive_outcomes','predictive_feedback','predictive_audit_logs'
] LOOP EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.predictive39_immutable()',t||'_immutable',t);END LOOP;END$$;

CREATE OR REPLACE FUNCTION public.predictive39_dashboard() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$DECLARE c uuid;BEGIN SELECT active_company_id INTO c FROM public.profiles WHERE id=auth.uid();IF NOT public.predictive39_read(c) THEN RAISE EXCEPTION 'Predictive fleet access denied';END IF;RETURN jsonb_build_object(
 'high_risk',(SELECT count(*) FROM public.predictive_vehicle_assessments WHERE company_id=c AND risk_level IN('high','critical')),
 'maintenance_due',(SELECT count(*) FROM public.predictive_maintenance_forecasts WHERE company_id=c AND risk_level IN('elevated','high','critical')),
 'fuel_anomalies',(SELECT count(*) FROM public.predictive_fuel_anomalies WHERE company_id=c AND risk_level<>'normal'),
 'tyre_risks',(SELECT count(*) FROM public.predictive_tyre_assessments WHERE company_id=c AND risk_level IN('elevated','high','critical')),
 'battery_risks',(SELECT count(*) FROM public.predictive_battery_assessments WHERE company_id=c AND risk_level IN('elevated','high','critical')),
 'engine_risks',(SELECT count(*) FROM public.predictive_engine_assessments WHERE company_id=c AND risk_level IN('elevated','high','critical')),
 'device_risks',(SELECT count(*) FROM public.predictive_device_health WHERE company_id=c AND risk_level IN('elevated','high','critical')),
 'stale_evidence',(SELECT count(*) FROM public.predictive_vehicle_assessments WHERE company_id=c AND freshness='stale'),
 'insufficient_data',(SELECT count(*) FROM public.predictive_vehicle_assessments WHERE company_id=c AND risk_level IN('unknown','insufficient_data')),
 'advisory_only',true,'breakdown_probability','unavailable_without_validated_outcomes','remaining_useful_life','unavailable_without_validated_component_evidence');END$$;

CREATE OR REPLACE FUNCTION public.predictive39_assessments(_limit int DEFAULT 100,_offset int DEFAULT 0) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$DECLARE c uuid;BEGIN SELECT active_company_id INTO c FROM public.profiles WHERE id=auth.uid();IF NOT public.predictive39_read(c) THEN RAISE EXCEPTION 'Predictive fleet access denied';END IF;RETURN(SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]') FROM(SELECT a.id,a.vehicle_id,v.registration,a.risk_level,a.confidence,a.evidence_coverage,a.freshness,a.factors,a.missing_evidence,a.result,a.calculated_at,a.model_version,a.governance_status FROM public.predictive_vehicle_assessments a LEFT JOIN public.vehicles v ON v.id=a.vehicle_id WHERE a.company_id=c ORDER BY CASE a.risk_level WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'elevated' THEN 3 WHEN 'watch' THEN 4 ELSE 5 END,a.calculated_at DESC LIMIT least(greatest(_limit,1),100) OFFSET greatest(_offset,0))x);END$$;

CREATE OR REPLACE FUNCTION public.predictive39_review(_assessment_id uuid,_state text,_feedback text,_note text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE c uuid;f uuid;BEGIN SELECT active_company_id INTO c FROM public.profiles WHERE id=auth.uid();IF NOT public.predictive39_review(c) THEN RAISE EXCEPTION 'Predictive review denied';END IF;IF _state NOT IN('new','under_review','accepted','deferred','rejected','inspection_requested','work_order_requested','closed','outcome_recorded') OR _feedback NOT IN('useful_warning','correct_but_late','correct_but_too_early','false_positive','insufficient_evidence','dismissed','action_taken') THEN RAISE EXCEPTION 'Invalid predictive review';END IF;IF NOT EXISTS(SELECT 1 FROM public.predictive_vehicle_assessments WHERE id=_assessment_id AND company_id=c) THEN RAISE EXCEPTION 'Assessment unavailable';END IF;INSERT INTO public.predictive_feedback(company_id,assessment_table,assessment_id,feedback,review_state,note,submitted_by) VALUES(c,'predictive_vehicle_assessments',_assessment_id,_feedback,_state,left(_note,2000),auth.uid()) RETURNING id INTO f;INSERT INTO public.predictive_audit_logs(company_id,event_type,entity_type,entity_id,actor_id,evidence) VALUES(c,CASE WHEN _feedback='false_positive' THEN 'false_positive_recorded' WHEN _state='accepted' THEN 'recommendation_accepted' WHEN _state='rejected' THEN 'recommendation_rejected' ELSE 'forecast_reviewed' END,'predictive_feedback',f,auth.uid(),jsonb_build_array(jsonb_build_object('assessment_id',_assessment_id)));RETURN jsonb_build_object('id',f,'state',_state,'advisory_only',true,'maintenance_mutated',false);END$$;

CREATE OR REPLACE FUNCTION public.predictive39_dispatch(_vehicle_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$DECLARE c uuid;a record;BEGIN SELECT active_company_id INTO c FROM public.profiles WHERE id=auth.uid();IF NOT public.is_company_member(c) OR NOT public.has_any_role(c,ARRAY['admin','dispatcher','fleet_manager','fleet_controller','operations_manager']::public.app_role[]) THEN RAISE EXCEPTION 'Dispatch predictive projection denied';END IF;SELECT * INTO a FROM public.predictive_vehicle_assessments WHERE company_id=c AND vehicle_id=_vehicle_id ORDER BY calculated_at DESC LIMIT 1;RETURN CASE WHEN a.id IS NULL THEN jsonb_build_object('risk','unknown','candidate_confidence_adjustment',0,'hard_eligibility_change',false) ELSE jsonb_build_object('risk',a.risk_level,'confidence',a.confidence,'freshness',a.freshness,'candidate_confidence_adjustment',CASE WHEN a.risk_level IN('high','critical') THEN -20 WHEN a.risk_level='elevated' THEN -10 ELSE 0 END,'hard_eligibility_change',false,'assessment_id',a.id) END;END$$;

CREATE OR REPLACE FUNCTION public.predictive39_driver() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$DECLARE c uuid;d uuid;a record;BEGIN SELECT active_company_id INTO c FROM public.profiles WHERE id=auth.uid();SELECT id INTO d FROM public.drivers WHERE company_id=c AND user_id=auth.uid();IF d IS NULL THEN RAISE EXCEPTION 'Driver projection denied';END IF;SELECT a.* INTO a FROM public.predictive_vehicle_assessments a JOIN public.vehicles v ON v.id=a.vehicle_id WHERE a.company_id=c AND v.assigned_driver_id=d AND a.risk_level IN('high','critical') ORDER BY a.calculated_at DESC LIMIT 1;RETURN CASE WHEN a.id IS NULL THEN jsonb_build_object('inspection_required',false,'instruction','Continue normal vehicle checks.','read_only',true) ELSE jsonb_build_object('inspection_required',true,'instruction','Vehicle check required. Report to the workshop or fleet controller.','read_only',true,'assessment_id',a.id) END;END$$;

CREATE OR REPLACE FUNCTION public.predictive39_customer_care(_vehicle_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$DECLARE c uuid;a record;BEGIN SELECT active_company_id INTO c FROM public.profiles WHERE id=auth.uid();IF NOT public.is_company_member(c) OR NOT public.has_any_role(c,ARRAY['admin','customer_care','operations_manager']::public.app_role[]) THEN RAISE EXCEPTION 'Customer Care predictive projection denied';END IF;SELECT * INTO a FROM public.predictive_vehicle_assessments WHERE company_id=c AND vehicle_id=_vehicle_id AND risk_level IN('high','critical') ORDER BY calculated_at DESC LIMIT 1;RETURN jsonb_build_object('customer_safe_effect',CASE WHEN a.id IS NULL THEN NULL ELSE 'Vehicle requires technical attention; the delivery plan is under review.' END,'raw_risk_score',NULL,'mechanical_detail',NULL,'driver_risk',NULL);END$$;

CREATE OR REPLACE FUNCTION public.predictive39_zip(_question text) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$DECLARE c uuid;a record;BEGIN SELECT active_company_id INTO c FROM public.profiles WHERE id=auth.uid();IF NOT public.predictive39_read(c) THEN RAISE EXCEPTION 'Predictive ZIP access denied';END IF;SELECT * INTO a FROM public.predictive_vehicle_assessments WHERE company_id=c ORDER BY CASE risk_level WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,calculated_at DESC LIMIT 1;RETURN CASE WHEN a.id IS NULL THEN jsonb_build_object('answer','No authorised predictive evidence is available. Risk is unknown, not normal.','citations','[]'::jsonb,'confidence','unavailable','freshness','unavailable','unknowns',jsonb_build_array('predictive evidence'),'read_only',true) ELSE jsonb_build_object('answer',format('The highest current advisory risk is %s. This is a risk signal, not a confirmed failure.',a.risk_level),'citations',jsonb_build_array(jsonb_build_object('table','predictive_vehicle_assessments','id',a.id)),'confidence',a.confidence,'freshness',a.freshness,'unknowns',a.missing_evidence,'read_only',true) END;END$$;

REVOKE ALL ON FUNCTION public.predictive39_dashboard(),public.predictive39_assessments(int,int),public.predictive39_review(uuid,text,text,text),public.predictive39_dispatch(uuid),public.predictive39_driver(),public.predictive39_customer_care(uuid),public.predictive39_zip(text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.predictive39_dashboard(),public.predictive39_assessments(int,int),public.predictive39_review(uuid,text,text,text),public.predictive39_dispatch(uuid),public.predictive39_driver(),public.predictive39_customer_care(uuid),public.predictive39_zip(text) TO authenticated;

INSERT INTO public.brain_feature_registry(company_id,feature_code,name,description,business_domain,experimental)
SELECT c.id,f.code,f.name,'Phase 39 governed predictive feature; advisory and under review.','fleet',true FROM public.companies c CROSS JOIN(VALUES
('vehicle_maintenance_risk','Vehicle maintenance risk'),('vehicle_breakdown_recurrence','Breakdown recurrence'),('fuel_efficiency_change','Fuel efficiency change'),('fuel_anomaly_score','Fuel anomaly score'),('battery_risk','Battery risk'),('cooling_risk','Cooling risk'),('tyre_risk','Tyre risk'),('device_reliability_risk','Device reliability risk'),('route_stress_score','Route stress score'),('driver_risk_trend','Driver risk trend'),('predicted_downtime_range','Predicted downtime range'),('service_demand_score','Service demand score'))f(code,name) ON CONFLICT DO NOTHING;

COMMENT ON TABLE public.predictive_vehicle_assessments IS 'Phase 39 advisory derived evidence. Risk is not proof of failure and never directly mutates operations.';
