-- Phase 32 extends Supabase Auth and existing RBAC. Values, credentials and keys are prohibited.
CREATE OR REPLACE FUNCTION public.security_can_read(c UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','system_administrator','technical_administrator','compliance_manager','executive','managing_director','viewer']::public.app_role[]) AND NOT public.has_any_role(c,ARRAY['driver']::public.app_role[]) AND NOT EXISTS(SELECT 1 FROM public.customer_portal_memberships m WHERE m.company_id=c AND m.user_id=auth.uid() AND m.status='active') $$;
CREATE OR REPLACE FUNCTION public.security_can_write(c UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','system_administrator','technical_administrator','compliance_manager']::public.app_role[]) AND NOT public.has_any_role(c,ARRAY['driver']::public.app_role[]) AND NOT EXISTS(SELECT 1 FROM public.customer_portal_memberships m WHERE m.company_id=c AND m.user_id=auth.uid() AND m.status='active') $$;
CREATE OR REPLACE FUNCTION public.security_can_approve(c UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','system_administrator']::public.app_role[]) $$;

CREATE TABLE public.security_identities(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,auth_user_id UUID REFERENCES auth.users(id),identity_type TEXT NOT NULL CHECK(identity_type IN('user','employee','customer','supplier','service_account','api','integration','brain_service','zip_service')),display_name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('invited','active','suspended','disabled','dormant')),owner_id UUID REFERENCES auth.users(id),branch_id UUID,department_id UUID,metadata JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(company_id,identity_type,display_name),CHECK(identity_type IN('user','employee','customer','supplier') OR auth_user_id IS NULL));
CREATE TABLE public.security_auth_factors(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,identity_id UUID NOT NULL REFERENCES public.security_identities(id) ON DELETE CASCADE,factor_type TEXT NOT NULL CHECK(factor_type IN('password','totp','webauthn','recovery_code')),provider_factor_reference TEXT,verified_at TIMESTAMPTZ,last_challenged_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN('pending','verified','revoked','unavailable')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(provider_factor_reference IS NULL OR length(provider_factor_reference)<200));
CREATE TABLE public.security_sessions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,identity_id UUID NOT NULL REFERENCES public.security_identities(id) ON DELETE CASCADE,provider_session_hash TEXT NOT NULL,device_id UUID,browser_metadata JSONB NOT NULL DEFAULT '{}',country_code TEXT,ip_hash TEXT,last_activity_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,idle_timeout_seconds INTEGER NOT NULL CHECK(idle_timeout_seconds>0),risk_score NUMERIC NOT NULL DEFAULT 0 CHECK(risk_score BETWEEN 0 AND 100),revoked_at TIMESTAMPTZ,revoked_by UUID REFERENCES auth.users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(provider_session_hash !~* 'bearer|eyJ'),CHECK(ip_hash IS NULL OR ip_hash !~ '[.:]'));
CREATE TABLE public.security_trusted_devices(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,identity_id UUID NOT NULL REFERENCES public.security_identities(id) ON DELETE CASCADE,fingerprint_hash TEXT NOT NULL,device_metadata JSONB NOT NULL DEFAULT '{}',registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),approved_at TIMESTAMPTZ,approved_by UUID REFERENCES auth.users(id),expires_at TIMESTAMPTZ NOT NULL,risk_score NUMERIC NOT NULL DEFAULT 0 CHECK(risk_score BETWEEN 0 AND 100),last_reviewed_at TIMESTAMPTZ,revoked_at TIMESTAMPTZ,UNIQUE(company_id,fingerprint_hash));
ALTER TABLE public.security_sessions ADD CONSTRAINT security_session_device_fk FOREIGN KEY(device_id) REFERENCES public.security_trusted_devices(id) ON DELETE SET NULL;
CREATE TABLE public.security_api_identities(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,identity_id UUID NOT NULL REFERENCES public.security_identities(id) ON DELETE CASCADE,name TEXT NOT NULL,environment TEXT NOT NULL,scopes TEXT[] NOT NULL DEFAULT '{}',token_reference_hash TEXT NOT NULL,issued_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,last_rotated_at TIMESTAMPTZ,rotation_due_at TIMESTAMPTZ,last_used_at TIMESTAMPTZ,revoked_at TIMESTAMPTZ,usage_count BIGINT NOT NULL DEFAULT 0,CHECK(token_reference_hash !~* 'bearer|eyJ|sk_'),UNIQUE(company_id,environment,name));
CREATE TABLE public.security_secret_metadata(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,name TEXT NOT NULL,secret_type TEXT NOT NULL,owner_id UUID NOT NULL,environment TEXT NOT NULL,provider_reference TEXT,rotated_at TIMESTAMPTZ,rotation_due_at TIMESTAMPTZ,expires_at TIMESTAMPTZ,usage_metadata JSONB NOT NULL DEFAULT '{}',status TEXT NOT NULL CHECK(status IN('current','rotation_due','expired','revoked','unavailable')),CHECK(provider_reference IS NULL OR provider_reference !~* 'bearer|eyJ|sk_'),UNIQUE(company_id,environment,name));
CREATE TABLE public.security_certificate_metadata(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,name TEXT NOT NULL,owner_id UUID NOT NULL,environment TEXT NOT NULL,fingerprint TEXT NOT NULL,issuer_metadata JSONB NOT NULL DEFAULT '{}',valid_from TIMESTAMPTZ,expires_at TIMESTAMPTZ,rotation_due_at TIMESTAMPTZ,usage_metadata JSONB NOT NULL DEFAULT '{}',status TEXT NOT NULL CHECK(status IN('valid','rotation_due','expired','revoked','unavailable')),UNIQUE(company_id,environment,fingerprint));
CREATE TABLE public.security_permission_grants(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,user_id UUID NOT NULL REFERENCES auth.users(id),existing_role public.app_role,branch_id UUID,department_id UUID,project_id UUID,resource_type TEXT,resource_id UUID,owner_only BOOLEAN NOT NULL DEFAULT false,permission TEXT NOT NULL,starts_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,grant_type TEXT NOT NULL CHECK(grant_type IN('temporary','elevation','emergency','delegation')),delegated_by UUID REFERENCES auth.users(id),reason TEXT NOT NULL,approved_by UUID REFERENCES auth.users(id),revoked_at TIMESTAMPTZ,CHECK(expires_at>starts_at),CHECK(delegated_by IS NULL OR delegated_by<>user_id));
CREATE TABLE public.security_access_reviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,name TEXT NOT NULL,review_type TEXT NOT NULL CHECK(review_type IN('user_access','admin_access','dormant_users','service_accounts','api_tokens','elevated_permissions')),period_start DATE NOT NULL,period_end DATE NOT NULL,due_at TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','in_review','completed','cancelled')),reviewer_id UUID NOT NULL,approved_by UUID REFERENCES auth.users(id),approved_at TIMESTAMPTZ,summary JSONB NOT NULL DEFAULT '{}',CHECK(period_end>=period_start),CHECK(approved_by IS NULL OR approved_by<>reviewer_id));
CREATE TABLE public.security_access_review_items(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,review_id UUID NOT NULL REFERENCES public.security_access_reviews(id) ON DELETE CASCADE,identity_id UUID REFERENCES public.security_identities(id),subject_reference UUID,decision TEXT CHECK(decision IN('retain','revoke','modify')),decision_reason TEXT,reviewed_by UUID REFERENCES auth.users(id),reviewed_at TIMESTAMPTZ,evidence JSONB NOT NULL DEFAULT '{}');
CREATE TABLE public.security_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,event_type TEXT NOT NULL CHECK(event_type IN('login','logout','mfa','password_reset','role_change','permission_change','token_created','token_revoked','device_registered','session_revoked','failed_authorization','policy_violation')),identity_id UUID REFERENCES public.security_identities(id),actor_id UUID REFERENCES auth.users(id),occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),correlation_id TEXT,severity TEXT NOT NULL CHECK(severity IN('low','moderate','high','critical')),safe_metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE public.security_threat_findings(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,finding_type TEXT NOT NULL CHECK(finding_type IN('impossible_travel','excessive_failures','privilege_escalation','suspicious_api_use','session_anomaly','cross_company_attempt','excessive_downloads','automation_abuse')),source_event_ids UUID[] NOT NULL DEFAULT '{}',risk TEXT NOT NULL CHECK(risk IN('low','moderate','high','critical')),status TEXT NOT NULL DEFAULT 'open' CHECK(status IN('open','acknowledged','investigating','resolved','false_positive')),owner_id UUID REFERENCES auth.users(id),brain_advice JSONB NOT NULL DEFAULT '{}',resolution TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.security_data_classifications(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,resource_kind TEXT NOT NULL CHECK(resource_kind IN('table','document','report','zip','brain','api')),resource_reference TEXT NOT NULL,classification TEXT NOT NULL CHECK(classification IN('public','internal','confidential','restricted','highly_restricted')),owner_id UUID NOT NULL,minimum_fields JSONB NOT NULL DEFAULT '{}',policy_reference TEXT NOT NULL,reviewed_at TIMESTAMPTZ,UNIQUE(company_id,resource_kind,resource_reference));
CREATE TABLE public.security_retention_policies(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,record_type TEXT NOT NULL CHECK(record_type IN('logs','audit','documents','messages','telemetry','bi','incidents','communications')),classification TEXT NOT NULL,retention_days INTEGER NOT NULL CHECK(retention_days>0),disposition TEXT NOT NULL DEFAULT 'human_review' CHECK(disposition IN('human_review','archive','anonymise','approved_delete')),owner_id UUID NOT NULL,approved_by UUID REFERENCES auth.users(id),effective_at TIMESTAMPTZ NOT NULL,legal_basis TEXT NOT NULL,UNIQUE(company_id,record_type,classification));
CREATE TABLE public.security_legal_holds(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,name TEXT NOT NULL,scope JSONB NOT NULL,reason TEXT NOT NULL,starts_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ,created_by UUID NOT NULL DEFAULT auth.uid(),approved_by UUID REFERENCES auth.users(id),approved_at TIMESTAMPTZ,released_by UUID REFERENCES auth.users(id),released_at TIMESTAMPTZ,release_reason TEXT,CHECK(released_at IS NULL OR approved_at IS NOT NULL));
CREATE TABLE public.security_privacy_requests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,request_type TEXT NOT NULL CHECK(request_type IN('access','export','delete','consent_change')),subject_reference_hash TEXT NOT NULL,scope JSONB NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'received' CHECK(status IN('received','identity_verification','in_review','approved','restricted_or_anonymised','fulfilled','rejected','cancelled')),requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),due_at TIMESTAMPTZ,reviewed_by UUID REFERENCES auth.users(id),approved_by UUID REFERENCES auth.users(id),resolution TEXT,evidence JSONB NOT NULL DEFAULT '{}',CHECK(subject_reference_hash !~* '@|bearer|eyJ'));
CREATE TABLE public.security_encryption_coverage(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,resource_type TEXT NOT NULL,environment TEXT NOT NULL,at_rest_state TEXT NOT NULL CHECK(at_rest_state IN('verified','expected','unavailable','not_applicable')),in_transit_state TEXT NOT NULL CHECK(in_transit_state IN('verified','expected','unavailable','not_applicable')),key_provider_metadata JSONB NOT NULL DEFAULT '{}',key_version_reference TEXT,rotated_at TIMESTAMPTZ,rotation_due_at TIMESTAMPTZ,coverage NUMERIC CHECK(coverage BETWEEN 0 AND 1),evidence_source TEXT,checked_at TIMESTAMPTZ,UNIQUE(company_id,environment,resource_type));
CREATE TABLE public.security_score_snapshots(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,score INTEGER CHECK(score BETWEEN 0 AND 100),mfa_adoption NUMERIC,dormant_accounts INTEGER,expired_tokens INTEGER,old_certificates INTEGER,access_review_completion NUMERIC,high_risk_findings INTEGER,open_incidents INTEGER,policy_compliance NUMERIC,source_record_ids UUID[] NOT NULL DEFAULT '{}',calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),confidence TEXT NOT NULL CHECK(confidence IN('high','medium','low','unavailable')));

CREATE OR REPLACE FUNCTION public.security_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Security evidence is append-only'; END $$;
CREATE TRIGGER security_events_append_only BEFORE UPDATE OR DELETE ON public.security_events FOR EACH ROW EXECUTE FUNCTION public.security_immutable();
CREATE OR REPLACE FUNCTION public.security_hold_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.approved_at IS NOT NULL AND OLD.released_at IS NULL AND (TG_OP='DELETE' OR NEW.scope IS DISTINCT FROM OLD.scope OR NEW.reason IS DISTINCT FROM OLD.reason) THEN RAISE EXCEPTION 'Active legal holds are immutable'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
CREATE TRIGGER security_active_hold_guard BEFORE UPDATE OR DELETE ON public.security_legal_holds FOR EACH ROW EXECUTE FUNCTION public.security_hold_guard();

DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['security_identities','security_auth_factors','security_sessions','security_trusted_devices','security_api_identities','security_secret_metadata','security_certificate_metadata','security_permission_grants','security_access_reviews','security_access_review_items','security_events','security_threat_findings','security_data_classifications','security_retention_policies','security_legal_holds','security_privacy_requests','security_encryption_coverage','security_score_snapshots'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon',t); EXECUTE format('GRANT ALL ON public.%I TO service_role',t); EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING(public.security_can_read(company_id))',t||'_read',t); END LOOP; END $$;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['security_identities','security_auth_factors','security_sessions','security_trusted_devices','security_api_identities','security_secret_metadata','security_certificate_metadata','security_permission_grants','security_access_reviews','security_access_review_items','security_threat_findings','security_data_classifications','security_retention_policies','security_legal_holds','security_privacy_requests','security_encryption_coverage','security_score_snapshots'] LOOP EXECUTE format('GRANT INSERT,UPDATE,DELETE ON public.%I TO authenticated',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING(public.security_can_write(company_id)) WITH CHECK(public.security_can_write(company_id))',t||'_write',t); END LOOP; END $$;
GRANT INSERT ON public.security_events TO authenticated;
CREATE POLICY security_events_insert ON public.security_events FOR INSERT TO authenticated WITH CHECK(public.security_can_write(company_id));
REVOKE UPDATE,DELETE ON public.security_events FROM authenticated;

COMMENT ON TABLE public.security_auth_factors IS 'Supabase Auth factor metadata only. A missing provider verification must never be reported as successful MFA.';
COMMENT ON TABLE public.security_api_identities IS 'Hashes and provider references only; plaintext tokens are prohibited.';
COMMENT ON TABLE public.security_secret_metadata IS 'Metadata only. Secret values and credentials are prohibited.';
COMMENT ON TABLE public.security_legal_holds IS 'Active approved holds prevent governed disposition; deletion remains a controlled human process.';
