-- Phase 23D runtime lifecycle. Brain jobs reference Phase 22 delivery/retry/DLQ records; they do not create a general workflow queue.
CREATE TABLE public.brain_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')),
  job_type TEXT NOT NULL CHECK(job_type IN ('event_analysis','scheduled_analysis','manual_analysis','recovery_replay','evaluation_replay','quality_scan','stale_insight_scan','rule_health_scan','dataset_freshness_scan','recommendation_expiry_scan','drift_scan')),
  execution_classification TEXT NOT NULL CHECK(execution_classification IN ('production_deterministic','production_quality_control','administrative_recovery','experimental_evaluation','manual_review_support')),
  trigger_type TEXT NOT NULL CHECK(trigger_type IN ('event','schedule','manual','recovery','evaluation')),
  trigger_event_id UUID REFERENCES public.integration_event_bus(id) ON DELETE SET NULL,
  schedule_id UUID, requested_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  dataset_contract_id UUID, rule_pack_code TEXT, rule_version_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(rule_version_ids)='array'), feature_version_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(feature_version_ids)='array'),
  priority INTEGER NOT NULL DEFAULT 50 CHECK(priority BETWEEN 0 AND 100), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','available','claimed','running','succeeded','failed','retry_scheduled','dead_letter','cancelled','expired','blocked','skipped_duplicate')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count >= 0), maximum_attempts INTEGER NOT NULL DEFAULT 3 CHECK(maximum_attempts > 0), available_at TIMESTAMPTZ NOT NULL DEFAULT now(), claimed_at TIMESTAMPTZ, claim_expires_at TIMESTAMPTZ, claimed_by TEXT, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, failed_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ,
  brain_run_id UUID, correlation_id TEXT, causation_id TEXT, idempotency_key TEXT NOT NULL, input_hash TEXT NOT NULL, output_hash TEXT, error_classification TEXT CHECK(error_classification IN ('validation_error','unsupported_event','contract_disabled','permission_failure','source_record_missing','dataset_temporarily_unavailable','database_transient_failure','integration_transient_failure','rate_limit','resource_limit','deterministic_logic_failure','schema_mismatch','unknown_failure')),
  error_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(error_metadata)='object'), resource_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(resource_metadata)='object'), dry_run BOOLEAN NOT NULL DEFAULT false, experimental BOOLEAN NOT NULL DEFAULT false, phase22_retry_id UUID REFERENCES public.integration_retry_queue(id) ON DELETE SET NULL, phase22_dlq_id UUID REFERENCES public.integration_dead_letter_queue(id) ON DELETE SET NULL, recovery_of_job_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(company_id,environment,idempotency_key), UNIQUE(company_id,id),
  FOREIGN KEY(company_id,dataset_contract_id) REFERENCES public.brain_dataset_contracts(company_id,id) ON DELETE RESTRICT,
  FOREIGN KEY(company_id,brain_run_id) REFERENCES public.zapp_brain_runs(company_id,id) ON DELETE SET NULL,
  CHECK(NOT experimental OR execution_classification='experimental_evaluation')
);

CREATE TABLE public.brain_job_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, job_id UUID NOT NULL, attempt_number INTEGER NOT NULL CHECK(attempt_number > 0), worker_id TEXT, status TEXT NOT NULL CHECK(status IN ('claimed','running','succeeded','failed','retry_scheduled','dead_letter','cancelled','expired','skipped_duplicate')), started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, duration_ms INTEGER CHECK(duration_ms IS NULL OR duration_ms >= 0), error_classification TEXT, error_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(error_metadata)='object'), phase22_retry_id UUID REFERENCES public.integration_retry_queue(id) ON DELETE SET NULL, phase22_dlq_id UUID REFERENCES public.integration_dead_letter_queue(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,job_id,attempt_number), FOREIGN KEY(company_id,job_id) REFERENCES public.brain_jobs(company_id,id) ON DELETE CASCADE
);

CREATE TABLE public.brain_worker_heartbeats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, worker_id TEXT NOT NULL, worker_type TEXT NOT NULL CHECK(worker_type IN ('consumer','scheduler','executor','recovery','quality','evaluation')), environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), runtime_version TEXT NOT NULL, started_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT now(), current_job_id UUID, jobs_completed INTEGER NOT NULL DEFAULT 0 CHECK(jobs_completed >= 0), jobs_failed INTEGER NOT NULL DEFAULT 0 CHECK(jobs_failed >= 0), drain_state TEXT NOT NULL DEFAULT 'active' CHECK(drain_state IN ('active','draining','stopped')), health_state TEXT NOT NULL DEFAULT 'unknown' CHECK(health_state IN ('healthy','degraded','backlogged','paused','draining','failed','unknown')), host_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(host_metadata)='object'), process_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(process_metadata)='object'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,environment,worker_id), FOREIGN KEY(company_id,current_job_id) REFERENCES public.brain_jobs(company_id,id) ON DELETE SET NULL
);

CREATE TABLE public.brain_consumers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, consumer_code TEXT NOT NULL, version TEXT NOT NULL, event_subscriptions JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(event_subscriptions)='array'), supported_event_versions JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(supported_event_versions)='array'), processing_mode TEXT NOT NULL CHECK(processing_mode IN ('event_driven','batch','manual')), concurrency_limit INTEGER NOT NULL DEFAULT 1 CHECK(concurrency_limit > 0), rate_limit_per_minute INTEGER NOT NULL DEFAULT 60 CHECK(rate_limit_per_minute > 0), paused BOOLEAN NOT NULL DEFAULT false, draining BOOLEAN NOT NULL DEFAULT false, last_heartbeat_at TIMESTAMPTZ, last_successful_event_at TIMESTAMPTZ, current_lag_seconds INTEGER, backlog_count INTEGER, error_rate_percent NUMERIC(5,2), dlq_count INTEGER NOT NULL DEFAULT 0 CHECK(dlq_count >= 0), health_state TEXT NOT NULL DEFAULT 'unknown' CHECK(health_state IN ('healthy','degraded','backlogged','paused','draining','failed','unknown')), owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,consumer_code,version), UNIQUE(company_id,id)
);

CREATE TABLE public.brain_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, schedule_code TEXT NOT NULL, name TEXT NOT NULL, purpose TEXT NOT NULL, analysis_type TEXT NOT NULL, environment TEXT NOT NULL CHECK(environment IN ('local','development','test','staging','production')), dataset_contract_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(dataset_contract_ids)='array'), rule_pack_code TEXT, schedule_kind TEXT NOT NULL CHECK(schedule_kind IN ('one_time','hourly','daily','weekly','monthly','cron','event_triggered','manual_only')), schedule_expression TEXT, time_zone TEXT NOT NULL DEFAULT 'UTC', start_at TIMESTAMPTZ, end_at TIMESTAMPTZ, enabled BOOLEAN NOT NULL DEFAULT false, maximum_runtime_seconds INTEGER NOT NULL DEFAULT 300 CHECK(maximum_runtime_seconds > 0), maximum_concurrent_runs INTEGER NOT NULL DEFAULT 1 CHECK(maximum_concurrent_runs > 0), catch_up_policy TEXT NOT NULL DEFAULT 'skip' CHECK(catch_up_policy IN ('skip','single_catch_up','bounded_catch_up')), overlap_policy TEXT NOT NULL DEFAULT 'skip' CHECK(overlap_policy IN ('skip','queue','replace_pending','block_until_complete')), last_scheduled_at TIMESTAMPTZ, next_scheduled_at TIMESTAMPTZ, owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, reviewer_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, production_approval_status TEXT NOT NULL DEFAULT 'draft' CHECK(production_approval_status IN ('draft','under_review','approved_for_staging','staging','staging_verified','approved_for_production','production','suspended','rolled_back','retired')), readiness_status TEXT NOT NULL DEFAULT 'unknown' CHECK(readiness_status IN ('ready','ready_with_warnings','not_ready','unknown')), experimental BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id,schedule_code), UNIQUE(company_id,id), CHECK(schedule_kind NOT IN ('cron') OR (schedule_expression IS NOT NULL AND schedule_expression ~ '^\*/[0-9]{1,2} \* \* \* \*$')), CHECK(NOT enabled OR environment <> 'production' OR production_approval_status IN ('approved_for_production','production'))
);
ALTER TABLE public.brain_jobs ADD CONSTRAINT brain_jobs_schedule_fk FOREIGN KEY(company_id,schedule_id) REFERENCES public.brain_schedules(company_id,id) ON DELETE SET NULL;

CREATE TABLE public.brain_schedule_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL, schedule_id UUID NOT NULL, job_id UUID, scheduled_for TIMESTAMPTZ NOT NULL, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, status TEXT NOT NULL CHECK(status IN ('pending','skipped','blocked','running','succeeded','failed','cancelled')), overlap_action TEXT CHECK(overlap_action IN ('start','skip','queue','replace_pending','block')), error_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(error_metadata)='object'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY(company_id,schedule_id) REFERENCES public.brain_schedules(company_id,id) ON DELETE CASCADE, FOREIGN KEY(company_id,job_id) REFERENCES public.brain_jobs(company_id,id) ON DELETE SET NULL
);

CREATE INDEX brain_jobs_claimable_idx ON public.brain_jobs(company_id,environment,available_at,priority DESC) WHERE status IN ('available','retry_scheduled');
CREATE UNIQUE INDEX brain_jobs_active_idempotency_idx ON public.brain_jobs(company_id,environment,idempotency_key) WHERE status IN ('pending','available','claimed','running','retry_scheduled');
CREATE INDEX brain_job_attempts_job_idx ON public.brain_job_attempts(company_id,job_id,attempt_number DESC);
CREATE INDEX brain_schedule_due_idx ON public.brain_schedules(company_id,environment,next_scheduled_at) WHERE enabled;
