-- Phase 33 records governed cross-domain observations only. BI, platform twins,
-- Brain, ZIP, Command Centre, Phase 22 and reliability remain authoritative.
CREATE OR REPLACE FUNCTION public.operations_intelligence_can_read(c UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','executive','managing_director','operations_manager','analyst','viewer','fleet_manager','warehouse_manager','finance_manager','commercial_manager','procurement_manager','crm_manager','hr_manager']::public.app_role[]) AND NOT public.has_any_role(c,ARRAY['driver']::public.app_role[]) AND NOT EXISTS(SELECT 1 FROM public.customer_portal_memberships m WHERE m.company_id=c AND m.user_id=auth.uid() AND m.status='active') $$;
CREATE OR REPLACE FUNCTION public.operations_intelligence_can_write(c UUID) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.operations_intelligence_can_read(c) AND public.has_any_role(c,ARRAY['admin','executive','managing_director','operations_manager','analyst','fleet_manager','warehouse_manager']::public.app_role[]) $$;

CREATE TABLE public.operations_intelligence_observations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,observation_type TEXT NOT NULL CHECK(observation_type IN('cross_domain_correlation','trend','enterprise_risk','priority')),scope_type TEXT NOT NULL CHECK(scope_type IN('company','branch','warehouse','fleet','region','team','asset','customer','supplier','process')),scope_id UUID,metric_code TEXT NOT NULL,bi_snapshot_ids UUID[] NOT NULL DEFAULT '{}',source_references JSONB NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(source_references)='array'),observed_value NUMERIC,observed_at TIMESTAMPTZ NOT NULL,confidence TEXT NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),explanation TEXT NOT NULL,non_causal BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(confidence='unavailable' OR cardinality(bi_snapshot_ids)>0 OR jsonb_array_length(source_references)>0));
CREATE TABLE public.operations_intelligence_forecasts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,forecast_type TEXT NOT NULL CHECK(forecast_type IN('maintenance_demand','warehouse_workload','shipment_volume','customer_demand','fleet_demand','staffing','inventory_pressure','telemetry_growth')),scope_type TEXT NOT NULL,scope_id UUID,period_start TIMESTAMPTZ NOT NULL,period_end TIMESTAMPTZ NOT NULL,predicted_value NUMERIC,confidence TEXT NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),assumptions JSONB NOT NULL DEFAULT '[]',missing_data JSONB NOT NULL DEFAULT '[]',explanation TEXT NOT NULL,evidence_references JSONB NOT NULL DEFAULT '[]',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(period_end>period_start),CHECK(confidence='unavailable' OR jsonb_array_length(evidence_references)>0));
CREATE TABLE public.operations_intelligence_bottlenecks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,bottleneck_type TEXT NOT NULL CHECK(bottleneck_type IN('warehouse_overload','route_overload','repeated_delay','repeated_failure','queue_growth','staffing_imbalance','vehicle_shortage','asset_contention')),scope_type TEXT NOT NULL,scope_id UUID,severity TEXT NOT NULL CHECK(severity IN('informational','warning','critical','unavailable')),status TEXT NOT NULL DEFAULT 'detected' CHECK(status IN('detected','acknowledged','investigating','resolved','dismissed')),evidence_references JSONB NOT NULL DEFAULT '[]',explanation TEXT NOT NULL,recommended_review TEXT,detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),resolved_at TIMESTAMPTZ,owner_id UUID REFERENCES auth.users(id),CHECK(severity='unavailable' OR jsonb_array_length(evidence_references)>0));
CREATE TABLE public.operations_intelligence_benchmarks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,benchmark_type TEXT NOT NULL CHECK(benchmark_type IN('branch','warehouse','fleet','region','team')),metric_code TEXT NOT NULL,period_start TIMESTAMPTZ NOT NULL,period_end TIMESTAMPTZ NOT NULL,rank INTEGER,percentile NUMERIC CHECK(percentile BETWEEN 0 AND 100),scope_id UUID NOT NULL,value NUMERIC,evidence_references JSONB NOT NULL DEFAULT '[]',confidence TEXT NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(period_end>period_start),CHECK(confidence='unavailable' OR jsonb_array_length(evidence_references)>0),UNIQUE(company_id,benchmark_type,metric_code,period_start,period_end,scope_id));
CREATE TABLE public.operations_intelligence_briefings(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,briefing_type TEXT NOT NULL CHECK(briefing_type IN('daily','weekly')),period_start TIMESTAMPTZ NOT NULL,period_end TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','under_review','published','retired')),sections JSONB NOT NULL DEFAULT '{}',evidence_references JSONB NOT NULL DEFAULT '[]',confidence TEXT NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),prepared_by UUID REFERENCES auth.users(id),reviewed_by UUID REFERENCES auth.users(id),published_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(period_end>period_start),CHECK(status<>'published' OR (reviewed_by IS NOT NULL AND jsonb_array_length(evidence_references)>0)));
CREATE TABLE public.operations_intelligence_simulations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,scenario_type TEXT NOT NULL CHECK(scenario_type IN('add_vehicles','remove_warehouse','increase_demand','lose_supplier','hire_drivers')),input_metadata JSONB NOT NULL,estimated_impact JSONB NOT NULL DEFAULT '{}',affected_kpi_codes TEXT[] NOT NULL DEFAULT '{}',assumptions JSONB NOT NULL DEFAULT '[]',evidence_references JSONB NOT NULL DEFAULT '[]',confidence TEXT NOT NULL CHECK(confidence IN('high','medium','low','unavailable')),requested_by UUID REFERENCES auth.users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),advisory_only BOOLEAN NOT NULL DEFAULT true,CHECK(advisory_only),CHECK(confidence='unavailable' OR jsonb_array_length(evidence_references)>0));

CREATE OR REPLACE FUNCTION public.operations_intelligence_evidence_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Operations intelligence evidence is append-only'; END $$;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['operations_intelligence_observations','operations_intelligence_forecasts','operations_intelligence_benchmarks','operations_intelligence_simulations'] LOOP EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.operations_intelligence_evidence_immutable()',t||'_immutable',t); END LOOP; END $$;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['operations_intelligence_observations','operations_intelligence_forecasts','operations_intelligence_bottlenecks','operations_intelligence_benchmarks','operations_intelligence_briefings','operations_intelligence_simulations'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon',t); EXECUTE format('GRANT ALL ON public.%I TO service_role',t); EXECUTE format('GRANT SELECT,INSERT ON public.%I TO authenticated',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING(public.operations_intelligence_can_read(company_id))',t||'_read',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK(public.operations_intelligence_can_write(company_id))',t||'_insert',t); END LOOP; END $$;
GRANT UPDATE ON public.operations_intelligence_bottlenecks,public.operations_intelligence_briefings TO authenticated;
CREATE POLICY operations_intelligence_bottlenecks_update ON public.operations_intelligence_bottlenecks FOR UPDATE TO authenticated USING(public.operations_intelligence_can_write(company_id)) WITH CHECK(public.operations_intelligence_can_write(company_id));
CREATE POLICY operations_intelligence_briefings_update ON public.operations_intelligence_briefings FOR UPDATE TO authenticated USING(public.operations_intelligence_can_write(company_id)) WITH CHECK(public.operations_intelligence_can_write(company_id));
CREATE INDEX operations_intelligence_observations_scope_idx ON public.operations_intelligence_observations(company_id,scope_type,scope_id,observed_at DESC);
CREATE INDEX operations_intelligence_bottlenecks_status_idx ON public.operations_intelligence_bottlenecks(company_id,status,severity,detected_at DESC);
COMMENT ON TABLE public.operations_intelligence_observations IS 'Non-causal links to existing authoritative evidence; not a replacement KPI store.';
COMMENT ON TABLE public.operations_intelligence_simulations IS 'Deterministic advisory estimates only. Records cannot execute operational changes.';
