-- Phase 36.5 is a derived presentation layer. It never replaces tracking,
-- jobs, trips, dispatch, customer, or driver operational records.
CREATE OR REPLACE FUNCTION public.fleet_board365_read(c uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.is_company_member(c) AND public.has_any_role(c,ARRAY['admin','dispatcher','fleet_controller','operations_manager','fleet_manager','customer_care','viewer','executive','brain_analyst','brain_reviewer']::public.app_role[]) $$;
CREATE OR REPLACE FUNCTION public.fleet_board365_write(c uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.fleet_board365_read(c) AND public.has_any_role(c,ARRAY['admin','dispatcher','fleet_controller','operations_manager','fleet_manager']::public.app_role[]) $$;
CREATE TABLE public.fleet_timeline_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,trip_id uuid,vehicle_id uuid,driver_id uuid,event_type text NOT NULL,occurred_at timestamptz NOT NULL,source text NOT NULL,confidence text NOT NULL CHECK(confidence IN('high','medium','low','unknown')),freshness text NOT NULL,evidence jsonb NOT NULL DEFAULT '[]',generated boolean NOT NULL DEFAULT true,severity text NOT NULL DEFAULT 'info',operational_label text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.fleet_hourly_board_snapshots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,hour_start timestamptz NOT NULL,vehicle_rows jsonb NOT NULL DEFAULT '[]',summary jsonb NOT NULL DEFAULT '{}',generated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,hour_start));
CREATE TABLE public.fleet_handover_reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,period_start timestamptz NOT NULL,period_end timestamptz NOT NULL,summary jsonb NOT NULL DEFAULT '{}',source_event_ids uuid[] NOT NULL DEFAULT '{}',generated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.fleet_timeline_metrics(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,metric_date date NOT NULL,metric_name text NOT NULL,value numeric,dimensions jsonb NOT NULL DEFAULT '{}',quality jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,metric_date,metric_name,dimensions));
CREATE OR REPLACE FUNCTION public.fleet_board365_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Fleet timeline evidence is append-only'; END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['fleet_timeline_events','fleet_hourly_board_snapshots','fleet_handover_reports','fleet_timeline_metrics'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon',t); EXECUTE format('GRANT SELECT,INSERT ON public.%I TO authenticated',t); EXECUTE format('CREATE POLICY %I_read ON public.%I FOR SELECT TO authenticated USING(public.fleet_board365_read(company_id))',t,t); EXECUTE format('CREATE POLICY %I_insert ON public.%I FOR INSERT TO authenticated WITH CHECK(public.fleet_board365_write(company_id))',t,t); EXECUTE format('CREATE TRIGGER %I_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.fleet_board365_append_only()',t,t); END LOOP; END $$;
CREATE POLICY fleet_timeline_customer_safe_read ON public.fleet_timeline_events FOR SELECT TO authenticated USING(public.is_company_member(company_id) AND EXISTS(SELECT 1 FROM public.customer_portal_memberships m WHERE m.company_id=fleet_timeline_events.company_id AND m.user_id=auth.uid() AND m.status='active') AND event_type IN('eta_updated','customer_arrival','pod_accepted','delay_detected'));
